org_portals_errors = {
     19001:["Failed to get portal data.", " User: {}, Failed to get portal data, Exception :{} "],
     19002:["ID not found.", "User: {} Failed to retrieve portal details for id: {}, Error: {} "],
     19003:["Failed to retrieve portal details.", " User: {}, Failed to retrieve portal details for id: {}, Error: {} "],
     19004:["Portal with this name already exists", " User: {}, Failed to create new portal, due to: Portal with name {} already exists. "],
     19005:["Failed to create new portal.", " User: {}, Failed to create new portal, due to:{} "],
     19006:["Failed to add portal to organisation.", " User: {}, Failed to create new portal, due to:{} "],
     19007:["ID not found.", " User: {}, Failed to update Portal for id: {}, Error: {} "],
     19008:["Portal with this name already exists.", " User: {}, Failed to update portal, due to: Portal with name {} already exists. "],
     19009:["Failed to update portal details.", " User: {}, Failed to update portal details for id: {}, Error: {} "],
     19010:["Failed to update portal details.", " User: {}, Failed to update portal details for id: {}, Error: {} "],
     19011:["ID not found.", " User: {}, Faliled to delete Portal for id: {}, Error: {} "],
     19012:["Failed to delete portal data", " User: {}, Faliled to delete Portal for id: {}, Error: {} "],
     19013:["Failed to get content data.", " User: {}, Failed to get content data, Error: {} "],
     19014:["ID not found.", " User: {}, Falied to retrieve Content details for id: {}"],
     19015:["Failed to retrieve content details.", " User: {}, Falied to retrieve Content details for id: {}, Error: {} "],
     19016:["Content with this name already exists.", " User: {}, Failed to create Content, due to: Content with name {} already exists. "],
     19017:["Failed to create content.", " User: {}, Failed to create content, Error: {} "],
     19018:["Failed to create content.", " User: {}, Failed to create content, Error: {} "],
     19019:["ID not found", " User: {}, Failed to update Content details for id: {}, Error: {} "],
     19020:["Content with this name already exists.", " User: {}, Failed to update Content, due to: Content with name {} already exists. "],
     19021:["This content is already being used in some of your portals. Please remove this content from the related portals and then unpublish.", " User: {} "],
     19022:["Failed to update content.", " User: {}, Id: {}, Error: {} "],
     19023:["Failed to update content details.", " User: {}, Id: {} , Error: {} "],
     19024:["ID not found.", " User: {}, Failed to update Content details for id: {}, Error: {} "],
     19025:["Failed to delete content data", " User: {}, Id: {}, Error: {} "],
     19026:["No Portal associated for the involved process.", " User: {}, Error: {} "],
     19027:["Failed to retrieve portal details.", " User: {}, Error: {} "],
     19028:["Failed to get portal content order details.", " User: {}, Error: {} "],
     19029:["Content with the given portal Id does not exist.", " User: {}, Id: {}, Error: {} "],
     19030:["Failed to update portal content order.", " User: {}, Id: {}, Error: {} "],
     19031:["Failed to change portal content order.", " User: {}, Id: {}, Error: {} "],
     19032:["Failed to create portal content order.", " User: {}, Error: {} "],
     19033:["Failed to create portal content order.", " User: {}, Error: {} "],
     19034:["ID not found", " User: {}, Failed to delete Portal Content Order for id: {}, Error: {} "],
     19035:["Failed to delete Portal content order.", " User: {}, Id: {}, Error: {} "],
}
