export const INIT_STATE = 'INIT_TAG_TRAVERSE_STATE';

export const GET_TAG_TRAVERSE_LOADING = 'GET_TAG_TRAVERSE_LOADING';
export const GET_TAG_TRAVERSE_SUCCESS = 'GET_TAG_TRAVERSE_SUCCESS';
export const GET_TAG_TRAVERSE_ERROR = 'GET_TAG_TRAVERSE_ERROR';

export const GET_SUBTAGS_TRAVERSE_LOADING = 'GET_SUBTAGS_TRAVERSE_LOADING';
export const GET_SUBTAGS_TRAVERSE_SUCCESS = 'GET_SUBTAGS_TRAVERSE_SUCCESS';
export const GET_SUBTAGS_TRAVERSE_ERROR = 'GET_SUBTAGS_TRAVERSE_ERROR';
