/* eslint-disable import/no-extraneous-dependencies */
import Base from '@ezedoxbp/formiojs/components/base/Base';

export default class EducationRecords extends Base {
    static schema() {
        return Base.schema({
            "validateOn": "change",
            "labelPosition": "top",
            "widget": null,
            "customConditional": "",
            "logic": [],
            "dataGridLabel": false,
            "label": "Panel",
            "labelMargin": 3,
            "tableView": false,
            "collapsed": false,
            "allowCalculateOverride": false,
            "alwaysEnabled": false,
            "components": [
                {
                    "validateOn": "change",
                    "labelPosition": "top",
                    "customConditional": "",
                    "logic": [],
                    "dataGridLabel": false,
                    "label": "Columns",
                    "columns": [
                        {
                            "validateOn": "change",
                            "labelPosition": "top",
                            "push": 0,
                            "dataGridLabel": false,
                            "label": "Column",
                            "disabled": false,
                            "tableView": true,
                            "allowCalculateOverride": false,
                            "components": [
                                {
                                    "validateOn": "change",
                                    "labelPosition": "left-left",
                                    "searchEnabled": true,
                                    "readOnlyValue": false,
                                    "validate": {
                                        "customPrivate": false,
                                        "select": false,
                                        "customMessage": "",
                                        "required": false,
                                        "custom": "",
                                        "json": ""
                                    },
                                    "customConditional": "",
                                    "logic": [
                                        {
                                            "trigger": {
                                                "event": "onCreateEducationalRecordsBtnClick",
                                                "type": "event"
                                            },
                                            "name": "Filling data to the datagrid",
                                            "actions": [
                                                {
                                                    "value": "if (data.qualification !== '') {\n    var iterable_values = [...component.data.values];\n    if (iterable_values !== null) {\n        var data_grid_single_record = {...data.educationRecords[0]};\n        Object.keys(data_grid_single_record).map(item => {\n            data_grid_single_record[item] = '';\n        })\n        var data_grid_values = [];\n        var flag = false;\n        iterable_values.map(item => {\n            if (item.value === data.qualification) {\n                flag = true;\n            }\n            if (flag) {\n                var each_row_data = {...data_grid_single_record};\n                each_row_data.level = item.value;\n                data_grid_values.push(each_row_data);\n                }\n            return null;\n        });\n\n        if (flag) {\n            data['educationRecords'] = data_grid_values;\n        }\n    }\n}",
                                                    "type": "value",
                                                    "name": "Setting datagrid value"
                                                }
                                            ]
                                        }
                                    ],
                                    "dataGridLabel": false,
                                    "customOptions": {},
                                    "disableLimit": false,
                                    "label": "Qualification (Highest Level)",
                                    "filter": "",
                                    "valueProperty": "value",
                                    "reference": false,
                                    "tableView": true,
                                    "allowCalculateOverride": false,
                                    "alwaysEnabled": false,
                                    "prefix": "",
                                    "widget": null,
                                    "tags": [],
                                    "labelWidth": 30,
                                    "autofocus": false,
                                    "defaultValue": "",
                                    "labelMargin": 3,
                                    "searchThreshold": 0.3,
                                    "refreshOn": "",
                                    "errorLabel": "",
                                    "selectFields": "",
                                    "selectThreshold": 0.3,
                                    "hideLabel": false,
                                    "input": true,
                                    "multiple": false,
                                    "suffix": "",
                                    "limit": 100,
                                    "searchField": "",
                                    "placeholder": "",
                                    "mask": false,
                                    "authenticate": false,
                                    "data": {
                                        "resource": "",
                                        "values": [
                                            {
                                                "value": "POST_DOC",
                                                "label": "Post Doctoral"
                                            },
                                            {
                                                "value": "PHD",
                                                "label": "Phd"
                                            },
                                            {
                                                "value": "MASTERS",
                                                "label": "Masters"
                                            },
                                            {
                                                "value": "POST_GRADUATE_DIPLOMA",
                                                "label": "Post Graduation / Diploma"
                                            },
                                            {
                                                "value": "GRADUATE",
                                                "label": "Graduate"
                                            },
                                            {
                                                "value": "DIPLOMA",
                                                "label": "Diploma"
                                            },
                                            {
                                                "value": "TWELFTH_STD",
                                                "label": "12th Standard"
                                            },
                                            {
                                                "value": "TENTH_STD",
                                                "label": "10th Standard"
                                            }
                                        ],
                                        "custom": "",
                                        "json": "",
                                        "url": ""
                                    },
                                    "minSearch": 0,
                                    "calculateValue": "",
                                    "id": "e2iaioq",
                                    "reorder": false,
                                    "protected": false,
                                    "hidden": false,
                                    "selectValues": "",
                                    "customClass": "",
                                    "lazyLoad": false,
                                    "encrypted": false,
                                    "persistent": true,
                                    "unique": false,
                                    "fuseOptions": {},
                                    "clearOnRefresh": false,
                                    "description": "",
                                    "dbIndex": false,
                                    "template": "<span>{{ item.label }}</span>",
                                    "sort": "",
                                    "type": "select",
                                    "properties": {},
                                    "disabled": false,
                                    "key": "qualification",
                                    "attributes": {},
                                    "tabindex": "",
                                    "conditional": {
                                        "when": "",
                                        "show": "",
                                        "json": "",
                                        "eq": ""
                                    },
                                    "tooltip": "",
                                    "customDefaultValue": "",
                                    "clearOnHide": true,
                                    "dataSrc": "values"
                                }
                            ],
                            "prefix": "",
                            "widget": null,
                            "labelWidth": 30,
                            "autofocus": false,
                            "refreshOn": "",
                            "errorLabel": "",
                            "calculateValue": "",
                            "conditional": {
                                "show": null,
                                "when": null,
                                "eq": ""
                            },
                            "description": "",
                            "tabindex": "",
                            "input": false,
                            "suffix": "",
                            "validate": {
                                "required": false,
                                "customPrivate": false,
                                "custom": ""
                            },
                            "tooltip": "",
                            "placeholder": "",
                            "offset": 0,
                            "clearOnRefresh": false,
                            "id": "eeqx91",
                            "customDefaultValue": "",
                            "protected": false,
                            "hidden": false,
                            "customClass": "",
                            "defaultValue": null,
                            "persistent": true,
                            "unique": false,
                            "dbIndex": false,
                            "pull": 0,
                            "hideLabel": false,
                            "type": "column",
                            "labelMargin": 3,
                            "key": "column",
                            "width": 6,
                            "hideOnChildrenHidden": false,
                            "multiple": false,
                            "clearOnHide": true
                        },
                        {
                            "validateOn": "change",
                            "labelPosition": "top",
                            "push": 0,
                            "dataGridLabel": false,
                            "label": "Column",
                            "disabled": false,
                            "tableView": true,
                            "allowCalculateOverride": false,
                            "components": [
                                {
                                    "validateOn": "change",
                                    "labelPosition": "top",
                                    "widget": null,
                                    "customConditional": "",
                                    "logic": [
                                        {
                                            "trigger": {
                                                "event": "DrawData",
                                                "type": "event"
                                            },
                                            "name": "Make it disable",
                                            "actions": [
                                                {
                                                    "property": {
                                                        "value": "disabled",
                                                        "label": "Disabled",
                                                        "type": "boolean"
                                                    },
                                                    "type": "property",
                                                    "name": "Setting disabled true",
                                                    "state": "true"
                                                }
                                            ]
                                        }
                                    ],
                                    "dataGridLabel": true,
                                    "defaultValue": false,
                                    "label": "Create Educational Record Entries",
                                    "labelMargin": 3,
                                    "tableView": true,
                                    "disableOnInvalid": false,
                                    "clearOnHide": true,
                                    "state": "",
                                    "allowCalculateOverride": false,
                                    "alwaysEnabled": false,
                                    "prefix": "",
                                    "theme": "success",
                                    "tags": [],
                                    "labelWidth": 30,
                                    "autofocus": false,
                                    "block": true,
                                    "refreshOn": "",
                                    "shortcut": "",
                                    "errorLabel": "",
                                    "calculateValue": "",
                                    "hideLabel": false,
                                    "action": "event",
                                    "input": true,
                                    "size": "md",
                                    "suffix": "",
                                    "validate": {
                                        "required": false,
                                        "customPrivate": false,
                                        "custom": "",
                                        "json": "",
                                        "customMessage": ""
                                    },
                                    "rightIcon": "",
                                    "placeholder": "",
                                    "mask": false,
                                    "leftIcon": "",
                                    "custom": "",
                                    "url": "",
                                    "clearOnRefresh": false,
                                    "id": "eyxabzg",
                                    "reorder": false,
                                    "protected": false,
                                    "showValidations": false,
                                    "hidden": false,
                                    "customClass": "",
                                    "encrypted": false,
                                    "persistent": false,
                                    "unique": false,
                                    "event": "onCreateEducationalRecordsBtnClick",
                                    "description": "",
                                    "dbIndex": false,
                                    "type": "button",
                                    "properties": {},
                                    "disabled": false,
                                    "key": "createEducationalRecordEntries",
                                    "attributes": {},
                                    "tabindex": "",
                                    "conditional": {
                                        "when": "",
                                        "show": "",
                                        "json": "",
                                        "eq": ""
                                    },
                                    "multiple": false,
                                    "customDefaultValue": "",
                                    "tooltip": ""
                                }
                            ],
                            "prefix": "",
                            "widget": null,
                            "labelWidth": 30,
                            "autofocus": false,
                            "refreshOn": "",
                            "errorLabel": "",
                            "calculateValue": "",
                            "conditional": {
                                "show": null,
                                "when": null,
                                "eq": ""
                            },
                            "description": "",
                            "tabindex": "",
                            "input": false,
                            "suffix": "",
                            "validate": {
                                "required": false,
                                "customPrivate": false,
                                "custom": ""
                            },
                            "tooltip": "",
                            "placeholder": "",
                            "offset": 0,
                            "clearOnRefresh": false,
                            "id": "ekggjx",
                            "customDefaultValue": "",
                            "protected": false,
                            "hidden": false,
                            "customClass": "",
                            "defaultValue": null,
                            "persistent": true,
                            "unique": false,
                            "dbIndex": false,
                            "pull": 0,
                            "hideLabel": false,
                            "type": "column",
                            "labelMargin": 3,
                            "key": "column",
                            "width": 6,
                            "hideOnChildrenHidden": false,
                            "multiple": false,
                            "clearOnHide": true
                        }
                    ],
                    "hideOnChildrenHidden": false,
                    "tableView": false,
                    "allowCalculateOverride": false,
                    "attributes": {},
                    "prefix": "",
                    "widget": null,
                    "labelWidth": 30,
                    "autofocus": false,
                    "labelMargin": 3,
                    "refreshOn": "",
                    "errorLabel": "",
                    "calculateValue": "",
                    "hideLabel": true,
                    "input": false,
                    "suffix": "",
                    "validate": {
                        "required": false,
                        "customPrivate": false,
                        "custom": ""
                    },
                    "tooltip": "",
                    "placeholder": "",
                    "mask": false,
                    "clearOnRefresh": false,
                    "id": "e5qbxhr",
                    "reorder": false,
                    "protected": false,
                    "hidden": false,
                    "customClass": "",
                    "defaultValue": null,
                    "persistent": false,
                    "unique": false,
                    "dbIndex": false,
                    "description": "",
                    "autoAdjust": false,
                    "type": "columns",
                    "properties": {},
                    "disabled": false,
                    "key": "columns2",
                    "alwaysEnabled": false,
                    "tabindex": "",
                    "conditional": {
                        "when": "",
                        "show": "",
                        "json": "",
                        "eq": ""
                    },
                    "multiple": false,
                    "customDefaultValue": "",
                    "clearOnHide": false
                },
                {
                    "addAnother": "",
                    "validateOn": "change",
                    "labelPosition": "top",
                    "groupToggle": false,
                    "enableRowGroups": false,
                    "logic": [],
                    "dataGridLabel": false,
                    "label": "Table of Educational Details",
                    "labelMargin": 3,
                    "tableView": true,
                    "layoutFixed": false,
                    "allowCalculateOverride": false,
                    "alwaysEnabled": false,
                    "components": [
                        {
                            "validate": {
                                "required": false,
                                "customPrivate": false,
                                "custom": "",
                                "json": "",
                                "customMessage": ""
                            },
                            "properties": {},
                            "row": "0-0",
                            "label": "BGV Required",
                            "type": "checkbox",
                            "alwaysEnabled": false,
                            "tags": [],
                            "logic": [],
                            "key": "bgv_required",
                            "attributes": {},
                            "mask": false,
                            "reorder": false,
                            "defaultValue": false,
                            "shortcut": "",
                            "customConditional": "",
                            "tableView": true,
                            "encrypted": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "hideLabel": true,
                            "input": true
                        },
                        {
                            "validate": {
                                "customPrivate": false,
                                "select": false,
                                "customMessage": "",
                                "required": true,
                                "custom": "",
                                "json": ""
                            },
                            "labelPosition": "left-left",
                            "row": "0-1",
                            "mask": false,
                            "type": "select",
                            "data": {
                                "resource": "",
                                "values": [
                                    {
                                        "value": "POST_DOC",
                                        "label": "Post Doctoral"
                                    },
                                    {
                                        "value": "PHD",
                                        "label": "Phd"
                                    },
                                    {
                                        "value": "MASTERS",
                                        "label": "Masters"
                                    },
                                    {
                                        "value": "POST_GRADUATE_DIPLOMA",
                                        "label": "Post Graduation / Diploma"
                                    },
                                    {
                                        "value": "GRADUATE",
                                        "label": "Graduate"
                                    },
                                    {
                                        "value": "DIPLOMA",
                                        "label": "Diploma"
                                    },
                                    {
                                        "value": "TWELFTH_STD",
                                        "label": "12th Standard"
                                    },
                                    {
                                        "value": "TENTH_STD",
                                        "label": "10th Standard"
                                    }
                                ],
                                "custom": "",
                                "json": "",
                                "url": ""
                            },
                            "customConditional": "",
                            "logic": [],
                            "disableLimit": false,
                            "label": "Level",
                            "valueProperty": "value",
                            "reference": false,
                            "tableView": true,
                            "selectValues": "",
                            "lazyLoad": false,
                            "defaultValue": "",
                            "alwaysEnabled": false,
                            "sort": "",
                            "tags": [],
                            "properties": {},
                            "disabled": true,
                            "key": "level",
                            "attributes": {},
                            "reorder": false,
                            "selectThreshold": 0.3,
                            "encrypted": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "input": true
                        },
                        {
                            "validate": {
                                "minWords": "",
                                "required": true,
                                "customMessage": "",
                                "minLength": "",
                                "customPrivate": false,
                                "pattern": "",
                                "maxWords": "",
                                "maxLength": "",
                                "custom": "",
                                "json": ""
                            },
                            "defaultValue": "",
                            "row": "0-2",
                            "tags": [],
                            "allowMultipleMasks": false,
                            "logic": [],
                            "label": "School / College / Institute Name",
                            "inputFormat": "plain",
                            "customConditional": "",
                            "tableView": true,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "showWordCount": false,
                            "attributes": {},
                            "widget": {
                                "minDate": "",
                                "hourIncrement": 1,
                                "defaultDate": null,
                                "format": "dd MMM yyyy",
                                "minuteIncrement": 5,
                                "enableDate": true,
                                "timezone": "",
                                "clickOpens": true,
                                "disableMobile": true,
                                "allowInput": true,
                                "language": "us-en",
                                "dateFormat": "dd MMM yyyy",
                                "enableTime": false,
                                "time_24hr": false,
                                "type": "",
                                "useLocaleSettings": false,
                                "maxDate": "",
                                "saveAs": "date",
                                "mode": "single",
                                "altInput": true,
                                "displayInTimezone": "",
                                "noCalendar": false
                            },
                            "type": "textfield",
                            "properties": {},
                            "key": "nameOfInstitute",
                            "alwaysEnabled": false,
                            "reorder": false,
                            "showCharCount": false,
                            "encrypted": false,
                            "input": true
                        },
                        {
                            "validate": {
                                "minWords": "",
                                "required": true,
                                "customMessage": "",
                                "minLength": "",
                                "customPrivate": false,
                                "pattern": "",
                                "maxWords": "",
                                "maxLength": "",
                                "custom": "",
                                "json": ""
                            },
                            "defaultValue": "",
                            "row": "0-3",
                            "tags": [],
                            "allowMultipleMasks": false,
                            "logic": [],
                            "label": "Student Name as per the Document",
                            "inputFormat": "plain",
                            "customConditional": "",
                            "tableView": true,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "showWordCount": false,
                            "attributes": {},
                            "widget": {
                                "minDate": "",
                                "hourIncrement": 1,
                                "defaultDate": null,
                                "format": "dd MMM yyyy",
                                "minuteIncrement": 5,
                                "enableDate": true,
                                "timezone": "",
                                "clickOpens": true,
                                "disableMobile": true,
                                "allowInput": true,
                                "language": "us-en",
                                "dateFormat": "dd MMM yyyy",
                                "enableTime": false,
                                "time_24hr": false,
                                "type": "",
                                "useLocaleSettings": false,
                                "maxDate": "",
                                "saveAs": "date",
                                "mode": "single",
                                "altInput": true,
                                "displayInTimezone": "",
                                "noCalendar": false
                            },
                            "type": "textfield",
                            "properties": {},
                            "key": "record_name",
                            "alwaysEnabled": false,
                            "reorder": false,
                            "showCharCount": false,
                            "encrypted": false,
                            "input": true
                        },
                        {
                            "validate": {
                                "minWords": "",
                                "required": true,
                                "customMessage": "",
                                "minLength": "",
                                "customPrivate": false,
                                "pattern": "",
                                "maxWords": "",
                                "maxLength": "",
                                "custom": "",
                                "json": ""
                            },
                            "defaultValue": "",
                            "row": "0-4",
                            "tags": [],
                            "allowMultipleMasks": false,
                            "logic": [],
                            "label": "Registration Number",
                            "inputFormat": "plain",
                            "customConditional": "",
                            "tableView": true,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "showWordCount": false,
                            "attributes": {},
                            "widget": {
                                "minDate": "",
                                "hourIncrement": 1,
                                "defaultDate": null,
                                "format": "dd MMM yyyy",
                                "minuteIncrement": 5,
                                "enableDate": true,
                                "timezone": "",
                                "clickOpens": true,
                                "disableMobile": true,
                                "allowInput": true,
                                "language": "us-en",
                                "dateFormat": "dd MMM yyyy",
                                "enableTime": false,
                                "time_24hr": false,
                                "type": "",
                                "useLocaleSettings": false,
                                "maxDate": "",
                                "saveAs": "date",
                                "mode": "single",
                                "altInput": true,
                                "displayInTimezone": "",
                                "noCalendar": false
                            },
                            "type": "textfield",
                            "properties": {},
                            "key": "registrationNumber",
                            "alwaysEnabled": false,
                            "reorder": false,
                            "showCharCount": false,
                            "encrypted": false,
                            "input": true
                        },
                        {
                            "suffix": true,
                            "validate": {
                                "minWords": "",
                                "required": false,
                                "customMessage": "",
                                "minLength": "",
                                "customPrivate": false,
                                "pattern": "",
                                "maxWords": "",
                                "maxLength": "",
                                "custom": "",
                                "json": ""
                            },
                            "defaultValue": "",
                            "row": "0-5",
                            "tags": [],
                            "allowMultipleMasks": false,
                            "logic": [],
                            "label": "Date on the Document",
                            "inputFormat": "plain",
                            "customConditional": "",
                            "tableView": true,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "showWordCount": false,
                            "attributes": {},
                            "widget": {
                                "icons": "",
                                "minDate": "",
                                "hourIncrement": 1,
                                "defaultDate": null,
                                "i18n": {
                                    "lng": "en",
                                    "resources": {
                                        "en": {
                                            "translation": {
                                                "minSelectedCount": "You must select at least {{minCount}} items to continue.",
                                                "cancel": "Cancel",
                                                "next": "Next",
                                                "minDate": "{{field}} should not contain date before {{- minDate}}",
                                                "month": "Month",
                                                "maxSelectedCount": "You can only select up to {{maxCount}} items to continue.",
                                                "mask": "{{field}} does not match the mask.",
                                                "day": "Day",
                                                "previous": "Previous",
                                                "year": "Year",
                                                "minWords": "{{field}} must have more than {{length}} words.",
                                                "required": "{{field}} is required",
                                                "april": "April",
                                                "invalid_email": "{{field}} must be a valid email.",
                                                "invalid_day": "{{field}} is not a valid day.",
                                                "max": "{{field}} cannot be greater than {{max}}.",
                                                "error": "Please fix the following errors before submitting.",
                                                "invalid_url": "{{field}} must be a valid url.",
                                                "january": "January",
                                                "invalid_regex": "{{field}} does not match the pattern {{regex}}.",
                                                "minLength": "{{field}} must be longer than {{length}} characters.",
                                                "complete": "Submission Complete",
                                                "pattern": "{{field}} does not match the pattern {{pattern}}",
                                                "maxWords": "{{field}} must have less than {{length}} words.",
                                                "june": "June",
                                                "november": "November",
                                                "maxLength": "{{field}} must be shorter than {{length}} characters.",
                                                "min": "{{field}} cannot be less than {{min}}.",
                                                "invalid_date": "{{field}} is not a valid date.",
                                                "maxDate": "{{field}} should not contain date after {{- maxDate}}",
                                                "august": "August",
                                                "september": "September",
                                                "submit": "Submit Form",
                                                "december": "December",
                                                "may": "May",
                                                "october": "October",
                                                "july": "July",
                                                "february": "February",
                                                "stripe": "{{stripe}}",
                                                "march": "March"
                                            }
                                        }
                                    }
                                },
                                "format": "dd MMM yyyy",
                                "minuteIncrement": 5,
                                "enableDate": true,
                                "timezone": "",
                                "clickOpens": true,
                                "disableMobile": true,
                                "allowInput": true,
                                "language": "en",
                                "dateFormat": "dd MMM yyyy",
                                "enableTime": false,
                                "time_24hr": false,
                                "type": "calendar",
                                "useLocaleSettings": false,
                                "maxDate": "",
                                "saveAs": "date",
                                "mode": "single",
                                "altInput": true,
                                "displayInTimezone": "",
                                "noCalendar": false
                            },
                            "type": "textfield",
                            "properties": {},
                            "key": "eduDocIssueDate",
                            "alwaysEnabled": false,
                            "reorder": false,
                            "showCharCount": false,
                            "encrypted": false,
                            "input": true
                        },
                        {
                            "validate": {
                                "required": true,
                                "customPrivate": false,
                                "custom": "",
                                "json": "",
                                "customMessage": ""
                            },
                            "defaultValue": [],
                            "row": "0-6",
                            "mask": false,
                            "type": "file",
                            "logic": [],
                            "fileTypes": [
                                {
                                    "value": "",
                                    "label": ""
                                }
                            ],
                            "url": "/api/forms/files?token=",
                            "options": "",
                            "webcamSize": "",
                            "reorder": false,
                            "dir": "",
                            "customConditional": "",
                            "tableView": true,
                            "webcam": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "fileMaxSize": "10MB",
                            "storage": "url",
                            "alwaysEnabled": false,
                            "tags": [],
                            "properties": {},
                            "key": "eduDocUrl",
                            "attributes": {},
                            "label": "Upload Document",
                            "fileNameTemplate": "",
                            "encrypted": false,
                            "input": true
                        },
                        {
                            "validate": {
                                "minWords": "",
                                "required": false,
                                "customMessage": "",
                                "minLength": "",
                                "customPrivate": false,
                                "pattern": "",
                                "maxWords": "",
                                "maxLength": "",
                                "custom": "",
                                "json": ""
                            },
                            "defaultValue": "",
                            "row": "0-7",
                            "tags": [],
                            "allowMultipleMasks": false,
                            "logic": [],
                            "label": "Grade / Percentage",
                            "inputFormat": "plain",
                            "customConditional": "",
                            "tableView": true,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "showWordCount": false,
                            "attributes": {},
                            "widget": {
                                "minDate": "",
                                "hourIncrement": 1,
                                "defaultDate": null,
                                "format": "dd MMM yyyy",
                                "minuteIncrement": 5,
                                "enableDate": true,
                                "timezone": "",
                                "clickOpens": true,
                                "disableMobile": true,
                                "allowInput": true,
                                "language": "us-en",
                                "dateFormat": "dd MMM yyyy",
                                "enableTime": false,
                                "time_24hr": false,
                                "type": "",
                                "useLocaleSettings": false,
                                "maxDate": "",
                                "saveAs": "date",
                                "mode": "single",
                                "altInput": true,
                                "displayInTimezone": "",
                                "noCalendar": false
                            },
                            "type": "textfield",
                            "properties": {},
                            "key": "grade",
                            "alwaysEnabled": false,
                            "reorder": false,
                            "showCharCount": false,
                            "encrypted": false,
                            "input": true
                        }
                    ],
                    "prefix": "",
                    "widget": null,
                    "tags": [],
                    "labelWidth": 30,
                    "autofocus": false,
                    "defaultValue": [
                        {
                            "level": "",
                            "nameOfInstitute": "",
                            "record_name": "",
                            "registrationNumber": "",
                            "eduDocIssueDate": "",
                            "eduDocUrl": [],
                            "grade": "",
                            "bgv_required": false
                        }
                    ],
                    "mask": false,
                    "customConditional": "show = data.qualification !== '';",
                    "refreshOn": "",
                    "errorLabel": "",
                    "calculateValue": "",
                    "hideLabel": true,
                    "input": true,
                    "multiple": false,
                    "suffix": "",
                    "validate": {
                        "required": false,
                        "customPrivate": false,
                        "custom": "",
                        "json": "",
                        "customMessage": ""
                    },
                    "placeholder": "",
                    "tree": true,
                    "defaultOpen": false,
                    "clearOnRefresh": false,
                    "id": "eo4fa92",
                    "reorder": false,
                    "protected": false,
                    "showAddRowButton": false,
                    "hidden": false,
                    "customClass": "horizontal-scroll-data-grid",
                    "encrypted": false,
                    "persistent": true,
                    "unique": false,
                    "addAnotherPosition": "bottom",
                    "dbIndex": false,
                    "description": "",
                    "disableAddingRemovingRows": false,
                    "type": "datagrid",
                    "properties": {},
                    "disabled": false,
                    "key": "educationRecords",
                    "attributes": {},
                    "tabindex": "",
                    "conditional": {
                        "when": "",
                        "show": "",
                        "json": "",
                        "eq": ""
                    },
                    "clearOnHide": true,
                    "customDefaultValue": "",
                    "removePlacement": "col",
                    "tooltip": ""
                }
            ],
            "prefix": "",
            "theme": "default",
            "tags": [],
            "labelWidth": 30,
            "autofocus": false,
            "defaultValue": null,
            "refreshOn": "",
            "errorLabel": "",
            "calculateValue": "",
            "hideLabel": false,
            "input": false,
            "multiple": false,
            "suffix": "",
            "validate": {
                "required": false,
                "customPrivate": false,
                "custom": ""
            },
            "tooltip": "",
            "placeholder": "",
            "mask": false,
            "clearOnRefresh": false,
            "id": "eqxs2wd",
            "reorder": false,
            "protected": false,
            "hidden": false,
            "customClass": "",
            "lazyLoad": false,
            "conditional": {
                "when": "",
                "show": "",
                "json": "",
                "eq": ""
            },
            "persistent": false,
            "unique": false,
            "title": "Education Records",
            "dbIndex": false,
            "description": "",
            "type": "panel",
            "properties": {},
            "disabled": false,
            "key": "educationalRecordsPanel",
            "attributes": {},
            "tabindex": "",
            "customDefaultValue": "",
            "breadcrumb": "default",
            "collapsible": false,
            "clearOnHide": false
        });
    }

    static builderInfo = {
        title: 'Education Records',
        group: 'basic',
        icon: 'fa fa-book',
        weight: 70,
        documentation: 'https://formio.github.io/formio.js/app/examples/customcomponent.html',
        schema: EducationRecords.schema()
    }
}
