import subprocess

def get_resigned_users(user_list):
    # The specific group signature to look for
    target_group = "GALL-DL-ResignedOutbo"
    
    # List to store users who match the criteria
    resigned_users_found = []
    print(f"Developed by @trixsearch , check github for more \n")
    print(f"Processing {len(user_list)} users...\n")

    for username in user_list:
        try:
            # Construct the command: net user /do <username>
            # capture_output=True captures stdout/stderr
            # text=True decodes the output to string automatically
            result = subprocess.run(
                ["net", "user", "/do", username], 
                capture_output=True, 
                text=True, 
                check=False # Don't crash if user not found, we handle it manually
            )

            # Get the standard output
            output = result.stdout

            # Check if the command was successful before parsing
            if result.returncode != 0:
                print(f"[-] Could not retrieve info for: {username}")
                continue

            # Check if the target group string exists in the output
            # We use distinct checking to ensure we don't catch partial matches randomly
            if target_group in output:
                print(f"[+] Found resignation group for: {username}")
                resigned_users_found.append(username)
            else:
                print(f"[ ] Active/No resignation group: {username}")

        except Exception as e:
            print(f"[!] Error processing {username}: {e}")

    return resigned_users_found

# --- Main Execution ---
if __name__ == "__main__":
    # Add your list of usernames here
    users_to_check = [
    "Janarthanan7.S",
    "Abhilash2.Nair",
    "Srushti.Wankhede",
    "Pratik15.Patil",
    "Yash.Khanke",
    "Jaydeep.Sondarva",
    "SHISHIR.JUVEKAR",
    "Ashwini.Sonkamble",
    "Shraddha1.Shinde",
    "Bharath.Vittal",
    "Rajkumar.Kunta",
    "Bhabatosh.Mahanta",
    "Suyog.Raut",
    "Soyam.Ram",
    "Abhinav37.Kumar",
    "Soumya1.Pattanaik",
    "Aman5.Raj",
    "Akash79.Kumar",
    "Harsh8.Raj",
    "Shubham96.Kumar",
    "Saksham.Tejaswi",
    "Arnab3.Saha",
    "Abhishek292.Kumar",
    "Aditya.Khatei",
    "Aniket.Pal",
    "Satyam10.Gupta",
    "Yuvraj14.Singh",
    "Shubham107.Kumar",
    "Nirmal25.Kumar",
    "Praveen3.Shukla",
    "Tanishq3.Jain",
    "Shubham3.Maurya",
    "Achalesh.Lakhotiya",
    "Pallav.Dubey",
    "Mehul.Saxena",
    "Aniket.Kishor",
    "Harini1.K",
    "Khushwant.Jangir",
    "Margani.Rohith",
    "Shubham27.Pandey",
    "Luckman.Shaik",
    "Sonu.Ola",
    "Ashwani70.Kumar",
    "ARADHYA.GARG",
    "Aniket.Sethiya",
    "Yash.Tawde",
    "Devarapally.Sushma",
    "Diwanker.Singh",
    "Ekansh.Singh",
    "Ganji.Sreenija",
    "Gautam4.Gupta",
    "Harshit.Keshari",
    "Jasmeet.Kaur",
    "Jonnalagadda.Babu",
    "Katakam.Likhitha",
    "Kaushik.Kundar",
    "Keshav1.Bhardwaj",
    "Shubham14.Shinde",
    "Yadav.Jaiprakash",
    "Ajinkya4.Patil",
    "Vishal4.Rai",
    "Sumit12.Tiwari",
    "Syed4.Raza",
    "Dharam.Sagar",
    "Nishita.Tamkhane",
    "Ashish6.Kushwaha",
    "Bushra2.Khan",
    "Divyanshu.Upadhyay",
    "Aditya2.Dubey",
    "Eklavya.Mahato",
    "Abhinav1.Sahu",
    "Akash.Khatik",
    "Rajul.Koshta",
    "Vaishnavi.Sharma",
    "Soumya.Yadav",
    "Harshpal.Singh",
    "Gaurav4.More",
    "Chirayu.Goyal",
    "Kushagra1.Gupta",
    "Kuldeep.Lodhi",
    "Manjinder5.Singh",
    "Tajuddin1.Alam",
    "Sanjeev.Nayak",
    "Tapas.Pradhan",
    "Chaitanya.Shah",
    "Rakesh.Parab",
    "Ashish.Jadhav",
    "Parag.Murudkar",
    "Neeraj.Sood",
    "Laxman.Prabhudesai",
    "Sunil.Nandwana",
    "Imran.Raynee",
    "Swapnil.Durgesht",
    "Praveen.Guntu",
    "Ranjan.Das",
    "Vinay.Verma",
    "Abhijeet.Mahajan",
    "Sujan.Singh",
    "Sandeshkumar.Lodha",
    "Anil.Kodag",
    "Vasudeo.Chari",
    "Sumeet.Pol",
    "Amit.Sinha",
    "Vishal7.Shah",
    "Zeeshan.Khurshid",
    "Sumeet.Chavan",
    "Jay.Pabari",
    "Sachin6.Chavan",
    "Vikram.Paul",
    "Girish.Kataria",
    "Vishal4.Patil",
    "Ankit.Arora",
    "Narendra.Shukla",
    "Mitul1.Desai",
    "Shubhada.Gawand",
    "Shubham.Manjrekar",
    "Divya.Manwani",
    "Kapoor.H",
    "Aman1.Bansal",
    "Mamta.Khubchandani",
    "Akash1.Mahajan",
    "Suprada.Shetty",
    "Prabhukalyan1.Dash",
    "Mohit2.Mahajan",
    "Sudhir29.Kumar",
    "Raza.Khan",
    "Vishal1.Sirsodiya",
    "Pinak.Desai",
    "Jayesh.Varadkar",
    "Kiran2.B",
    "Ram19.Singh",
    "Sameer1.Masalkar",
    "Raja.Reddy",
    "Rishabh9.Srivastava",
    "Himani.Chhallare",
    "Omkar3.Joshi",
    "Vinay1.Vishwakarma",
    "Prashant.Kumavat",
    "Mohammad.Alam",
    "Divyam.Bajaj",
    "Vipin1.Damle",
    "Amit.Dhavale",
    "Pooja.Prasannan",
    "Babu.Jayaraj",
    "Prathamesh.Adarkar",
    "Suvra.Mallick",
    "Yogesh2.Shah",
    "Badrinath.S",
    "Rajiv.Katira",
    "Khasim.Shaik",
    "Amol.Chhallare",
    "Abhinav4.Chaturvedi",
    "Juhi.Jha",
    "Hitesh1.Paliwal",
    "Kajal1.Mishra",
    "Balachandar.A",
    "Soumya2.Das",
    "Mohit79.Kumar",
    "Pradeep1.Tiwari",
    "Ajay.Nimbolkar",
    "Jeetendra.Pradhan",
    "Tanmay1.Trivedi",
    "Minakshi1.Raul",
    "Deepesh3.Kumar",
    "Kamal2.Sahu",
    "Praveen183.Kumar",
    "Gaurav1.Devkar",
    "Deep.Darji",
    "Vasundhara.Patil",
    "Rachana.Jadhav",
    "Riddhi1.Rane",
    "Joydeep.Mukherjee",
    "Chirag.Gujarathi",
    "Jay.Paruthi",
    "Viraj.Ghatge",
    "Tejas.Patel",
    "Vishal.Sodvadiya",
    "Poonam.Agarkar",
    "Lalita.Rajput",
    "Anurag2.Shukla",
    "Tejas.Paradkar",
    "Pournima.Kadav",
    "Saleem.Syed",
    "Shaik.Riazuddin",
    "Suraj37.Singh",
    "Deepti.Sonawane",
    "Harshita.Sandhu",
    "Prasad.Gadhave",
    "Azhar.Dalwai",
    "Ratan.Jawale",
    "Shubham1.Monga",
    "Arvind.Tilgule",
    "Iti.Madan",
    "Anirudh.Sharma",
    "Pravin3.Rathod",
    "Sneha.Mhatre",
    "Primas.Gonsalves",
    "Amol1.Rathod",
    "Nitesh2.Shukla",
    "Sai.Jn",
    "Shikha1.Sahu",
    "Soumodeep.Mandal",
    "Vivek.Pant",
    "Darshan3.Kumar",
    "Baddam.Reddy",
    "Akshay1.Dumbre",
    "Raju7.Gupta",
    "Ayushi.Pal",
    "Vandana1.Mishra",
    "Shivanand1.Katkol",
    "Dakshata.Pawar",
    "Heena.Purohit",
    "Shailesh.Mankar",
    "Sujata.Nimbolkar",
    "Dhananjay.Mulay",
    "Amit3.Mathur",
    "Eadala.Laxman",
    "Mukesh1.Babu",
    "Samreen.Fatma",
    "Debasish.Panda",
    "Shiva.Shrivastav",
    "Tanmay.Rane",
    "Omkar2.Rane",
    "Narendra.Purohit",
    "Pralhad.Dharmadhikari",
    "Sushant.Dukhande",
    "Kalluri.Mallesh",
    "Snehal.Barge",
    "Akashkumar.R",
    "Dhanushkrishnan.A",
    "Kalaiselvan.S",
    "Sandeep.C.Gupta",
    "khushi.nigam",
    "Alquama.Khan",
    "shatakshi.s"
]

    # Run the check
    final_list = get_resigned_users(users_to_check)

    print("-" * 30)
    print("Final List of Resigned Users:")
    print(final_list)
    print("Total No. of persons : ",len(final_list))