# Generated by Django 3.1.4 on 2022-06-27 12:44

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationLists',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField()),
                ('list', models.JSONField(blank=True, default=dict, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Organisation List',
                'verbose_name_plural': 'Organisation Lists',
            },
        ),
        migrations.CreateModel(
            name='OrganisationAdvancedLists',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField()),
                ('lists', models.JSONField(blank=True, default=dict, null=True)),
                ('schema', models.JSONField(blank=True, default=dict, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Organisation Advanced List',
                'verbose_name_plural': 'Organisation Advanced Lists',
            },
        ),
        migrations.AddIndex(
            model_name='organisationlists',
            index=django.contrib.postgres.indexes.GinIndex(fields=['list'], name='org_lists_o_list_cbab97_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='organisationlists',
            unique_together={('key', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='organisationadvancedlists',
            index=django.contrib.postgres.indexes.GinIndex(fields=['lists'], name='org_lists_o_lists_62e145_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='organisationadvancedlists',
            unique_together={('key', 'tenant')},
        ),
    ]
