org_third_party_errors = {
    22001: ["Retrieve OCR Data Failed.", " Error: {} "],
    22002: ["OCR Data Fetched failed.", " Response: {} "],
    22003: ["Retrieve OCR Data Failed.", " Exception: {} "],
    22004: ["Failed to read the aadhaar front image URL", " Error: {} "],
    22005: ["Unsupported Filetype :"],
    22006: ["ID not found.", " Failed to update File of id : {}, Error: {} "],
    22007: ["Aadhaar masking FRS API Failed", " Exception: {} "],
    22008: ["unique reference id fetch failed."],
    22009: ["Getting bank reference id for bank account details Failed.", " Exception: {} "],
    22010: ["Bank details status verify failed."],
    22011: ["Verify bank details status Failed.", " Exception: {} "],
    22012: ["Error - code is not present."," Error: {}"],
    22013: ["Unable to get access token from Digilocker."," Error : {}"],
    22014: ["Unable to get issued doc for aadhaar from Digilocker.", " Error : {}"],
    22015: ["Unable to get issued document from Digilocker.", " Error : {}"],
    22016: ["Unable to get xml data for aadhaar from Digilocker."," Error: {}"],
    22017: ["Error - Unable to parse Digilocker response, Internal error."," Error: {}"],
    22018: ["Unable to get pdf data for aadhaar from Digilocker."," Error: {}"],
    22019: ["Unable to parse Digilocker response for aadhaar."," Error: {}"],
    22020: ["Error - Transaction id not found."," Error: {}"],
    22021: ["Unable to get issued doc for pan from Digilocker.", " Error : {}"],
    22022: ["Unable to get xml data for pan from Digilocker."," Error: {}"],
    22023: ["Unable to parse Digilocker response for PAN."," Error: {}"],
    22024: ["Unable to get pdf data for pan from Digilocker."," Error: {}"],
    22025: ["Unable to get issued doc for driving license from Digilocker.", "  Error : {}"],
    22026: ["Unable to get xml data for driving license."," Error: {}"],
    22027: ["Unable to parse Digilocker response for Driving License."," Error: {}"],
    22028: ["Unable to get pdf data for driving license from Digilocker."," Error: {}"],
    22029: ["Unable to pull the PAN document from DIgilocker."," Error: {}"],
    22030: ["Unable to pull the Driving License document from DIgilocker."," Error: {}"],
    22031: ["Unable to pull the RC document from Digilocker."," Error: {}"],
    22032: ["Unable to get issued doc for RC from Digilocker.", " Error : {}"],
    22033: ["Unable to get pdf data for RC from Digilocker."," Error: {}"],
    22034: ["Unable to get xml data for RC from Digilocker."," Error: {}"],
    22035: ["Unable to parse Digilocker response for RC."," Error: {}"],
    22036: ["Failed to get PAN - Aadhaar linkage status.","Error: {}"],
    22037: ["Failed to get PAN - Aadhaar linkage status.","Error: {}"],
    22038: ["Failed to get otp.","Error: {}"],
    22039: ["Failed to get otp","Error: {}"],
    22040: ["Failed to verify otp.","Error: {}"],
    22041: ["Failed to verify otp","Error: {}"],
    22042: ["Failed to verify otp","Error: {}"],
    22043: ["Failed to start Process","Error: {}"],
    22044: ["Failed to start Process","Error: {}"],
    22045: ["Failed to get onboard config", "Error: {}"],
    22046: ["Failed to get onboard config", "Error: {}"],
    22047: ["Failed to get onboard config", "Error: {}"],
    22048: ["Failed to save onboard document", "Error: {}"],
    22049: ["Failed to save onboard document", "Error: {}"],
    22050: ["Failed to save onboard document", "Error: {}"],
    22051: ["Failed to generate document", "Error {}"],
    22052: ["Failed to generate document", "Error {}"],
    22053: ["Failed to generate document", "Error {}"],
    22054: ["Failed to subscribe to product hire", "Error {}"],
    22055: ["Failed to assign policy to user", "Error {}"],
    22056: ["Failed to create org user", "Error {}"],
    22057: ["Failed to create new policy" ,"Error {}"],
    22058: ["Failed to create new employee", "Error {}"],
    22059: ["Failed to create new org", "Error {}"],
    22060: ["Organisation already present with this pan number. add different document or review it"],
    22061: ["Failed to onboard new organisation", "Error {}"],
    22062: ["Failed to complete self signup process", "Error {}"],
    22063:["Mobile number is required.", " Unable to generate OTP. "],
    22064:["Failed to create External user.", " User: {}, Error: {} "],
    22065:["Unable to send OTP.", " Error: {} "],
    22066:["Unable to generate OTP.", " Error: {} "],
    22067:["User with this mobile number does not exist"],
    22068:["Authentication failed!", " Unable to validate OTP."],
    22069:["Unable to validate OTP.", " Error: {} "],
}
