# coding: utf-8

"""
    Flowable REST API

    # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CommentResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'author': 'str',
        'message': 'str',
        'time': 'datetime',
        'task_id': 'str',
        'task_url': 'str',
        'process_instance_id': 'str',
        'process_instance_url': 'str'
    }

    attribute_map = {
        'id': 'id',
        'author': 'author',
        'message': 'message',
        'time': 'time',
        'task_id': 'taskId',
        'task_url': 'taskUrl',
        'process_instance_id': 'processInstanceId',
        'process_instance_url': 'processInstanceUrl'
    }

    def __init__(self, id=None, author=None, message=None, time=None, task_id=None, task_url=None, process_instance_id=None, process_instance_url=None):  # noqa: E501
        """CommentResponse - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._author = None
        self._message = None
        self._time = None
        self._task_id = None
        self._task_url = None
        self._process_instance_id = None
        self._process_instance_url = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if author is not None:
            self.author = author
        if message is not None:
            self.message = message
        if time is not None:
            self.time = time
        if task_id is not None:
            self.task_id = task_id
        if task_url is not None:
            self.task_url = task_url
        if process_instance_id is not None:
            self.process_instance_id = process_instance_id
        if process_instance_url is not None:
            self.process_instance_url = process_instance_url

    @property
    def id(self):
        """Gets the id of this CommentResponse.  # noqa: E501


        :return: The id of this CommentResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CommentResponse.


        :param id: The id of this CommentResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def author(self):
        """Gets the author of this CommentResponse.  # noqa: E501


        :return: The author of this CommentResponse.  # noqa: E501
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author):
        """Sets the author of this CommentResponse.


        :param author: The author of this CommentResponse.  # noqa: E501
        :type: str
        """

        self._author = author

    @property
    def message(self):
        """Gets the message of this CommentResponse.  # noqa: E501


        :return: The message of this CommentResponse.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this CommentResponse.


        :param message: The message of this CommentResponse.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def time(self):
        """Gets the time of this CommentResponse.  # noqa: E501


        :return: The time of this CommentResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this CommentResponse.


        :param time: The time of this CommentResponse.  # noqa: E501
        :type: datetime
        """

        self._time = time

    @property
    def task_id(self):
        """Gets the task_id of this CommentResponse.  # noqa: E501


        :return: The task_id of this CommentResponse.  # noqa: E501
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this CommentResponse.


        :param task_id: The task_id of this CommentResponse.  # noqa: E501
        :type: str
        """

        self._task_id = task_id

    @property
    def task_url(self):
        """Gets the task_url of this CommentResponse.  # noqa: E501


        :return: The task_url of this CommentResponse.  # noqa: E501
        :rtype: str
        """
        return self._task_url

    @task_url.setter
    def task_url(self, task_url):
        """Sets the task_url of this CommentResponse.


        :param task_url: The task_url of this CommentResponse.  # noqa: E501
        :type: str
        """

        self._task_url = task_url

    @property
    def process_instance_id(self):
        """Gets the process_instance_id of this CommentResponse.  # noqa: E501


        :return: The process_instance_id of this CommentResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_instance_id

    @process_instance_id.setter
    def process_instance_id(self, process_instance_id):
        """Sets the process_instance_id of this CommentResponse.


        :param process_instance_id: The process_instance_id of this CommentResponse.  # noqa: E501
        :type: str
        """

        self._process_instance_id = process_instance_id

    @property
    def process_instance_url(self):
        """Gets the process_instance_url of this CommentResponse.  # noqa: E501


        :return: The process_instance_url of this CommentResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_instance_url

    @process_instance_url.setter
    def process_instance_url(self, process_instance_url):
        """Sets the process_instance_url of this CommentResponse.


        :param process_instance_url: The process_instance_url of this CommentResponse.  # noqa: E501
        :type: str
        """

        self._process_instance_url = process_instance_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CommentResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CommentResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
