# coding: utf-8

"""
    Flowable REST API

    # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EventResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'str',
        'id': 'str',
        'action': 'str',
        'user_id': 'str',
        'time': 'datetime',
        'task_url': 'str',
        'process_instance_url': 'str',
        'message': 'list[str]'
    }

    attribute_map = {
        'url': 'url',
        'id': 'id',
        'action': 'action',
        'user_id': 'userId',
        'time': 'time',
        'task_url': 'taskUrl',
        'process_instance_url': 'processInstanceUrl',
        'message': 'message'
    }

    def __init__(self, url=None, id=None, action=None, user_id=None, time=None, task_url=None, process_instance_url=None, message=None):  # noqa: E501
        """EventResponse - a model defined in Swagger"""  # noqa: E501

        self._url = None
        self._id = None
        self._action = None
        self._user_id = None
        self._time = None
        self._task_url = None
        self._process_instance_url = None
        self._message = None
        self.discriminator = None

        if url is not None:
            self.url = url
        if id is not None:
            self.id = id
        if action is not None:
            self.action = action
        if user_id is not None:
            self.user_id = user_id
        if time is not None:
            self.time = time
        if task_url is not None:
            self.task_url = task_url
        if process_instance_url is not None:
            self.process_instance_url = process_instance_url
        if message is not None:
            self.message = message

    @property
    def url(self):
        """Gets the url of this EventResponse.  # noqa: E501


        :return: The url of this EventResponse.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this EventResponse.


        :param url: The url of this EventResponse.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def id(self):
        """Gets the id of this EventResponse.  # noqa: E501


        :return: The id of this EventResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EventResponse.


        :param id: The id of this EventResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def action(self):
        """Gets the action of this EventResponse.  # noqa: E501


        :return: The action of this EventResponse.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this EventResponse.


        :param action: The action of this EventResponse.  # noqa: E501
        :type: str
        """

        self._action = action

    @property
    def user_id(self):
        """Gets the user_id of this EventResponse.  # noqa: E501


        :return: The user_id of this EventResponse.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this EventResponse.


        :param user_id: The user_id of this EventResponse.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def time(self):
        """Gets the time of this EventResponse.  # noqa: E501


        :return: The time of this EventResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this EventResponse.


        :param time: The time of this EventResponse.  # noqa: E501
        :type: datetime
        """

        self._time = time

    @property
    def task_url(self):
        """Gets the task_url of this EventResponse.  # noqa: E501


        :return: The task_url of this EventResponse.  # noqa: E501
        :rtype: str
        """
        return self._task_url

    @task_url.setter
    def task_url(self, task_url):
        """Sets the task_url of this EventResponse.


        :param task_url: The task_url of this EventResponse.  # noqa: E501
        :type: str
        """

        self._task_url = task_url

    @property
    def process_instance_url(self):
        """Gets the process_instance_url of this EventResponse.  # noqa: E501


        :return: The process_instance_url of this EventResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_instance_url

    @process_instance_url.setter
    def process_instance_url(self, process_instance_url):
        """Sets the process_instance_url of this EventResponse.


        :param process_instance_url: The process_instance_url of this EventResponse.  # noqa: E501
        :type: str
        """

        self._process_instance_url = process_instance_url

    @property
    def message(self):
        """Gets the message of this EventResponse.  # noqa: E501


        :return: The message of this EventResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this EventResponse.


        :param message: The message of this EventResponse.  # noqa: E501
        :type: list[str]
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EventResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
