# coding: utf-8

"""
    Flowable REST API

    # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ExecutionQueryRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start': 'int',
        'size': 'int',
        'sort': 'str',
        'order': 'str',
        'id': 'str',
        'activity_id': 'str',
        'parent_id': 'str',
        'process_instance_id': 'str',
        'process_business_key': 'str',
        'process_definition_id': 'str',
        'process_definition_key': 'str',
        'signal_event_subscription_name': 'str',
        'message_event_subscription_name': 'str',
        'variables': 'list[QueryVariable]',
        'process_instance_variables': 'list[QueryVariable]',
        'tenant_id': 'str',
        'tenant_id_like': 'str',
        'without_tenant_id': 'bool'
    }

    attribute_map = {
        'start': 'start',
        'size': 'size',
        'sort': 'sort',
        'order': 'order',
        'id': 'id',
        'activity_id': 'activityId',
        'parent_id': 'parentId',
        'process_instance_id': 'processInstanceId',
        'process_business_key': 'processBusinessKey',
        'process_definition_id': 'processDefinitionId',
        'process_definition_key': 'processDefinitionKey',
        'signal_event_subscription_name': 'signalEventSubscriptionName',
        'message_event_subscription_name': 'messageEventSubscriptionName',
        'variables': 'variables',
        'process_instance_variables': 'processInstanceVariables',
        'tenant_id': 'tenantId',
        'tenant_id_like': 'tenantIdLike',
        'without_tenant_id': 'withoutTenantId'
    }

    def __init__(self, start=None, size=None, sort=None, order=None, id=None, activity_id=None, parent_id=None, process_instance_id=None, process_business_key=None, process_definition_id=None, process_definition_key=None, signal_event_subscription_name=None, message_event_subscription_name=None, variables=None, process_instance_variables=None, tenant_id=None, tenant_id_like=None, without_tenant_id=None):  # noqa: E501
        """ExecutionQueryRequest - a model defined in Swagger"""  # noqa: E501

        self._start = None
        self._size = None
        self._sort = None
        self._order = None
        self._id = None
        self._activity_id = None
        self._parent_id = None
        self._process_instance_id = None
        self._process_business_key = None
        self._process_definition_id = None
        self._process_definition_key = None
        self._signal_event_subscription_name = None
        self._message_event_subscription_name = None
        self._variables = None
        self._process_instance_variables = None
        self._tenant_id = None
        self._tenant_id_like = None
        self._without_tenant_id = None
        self.discriminator = None

        if start is not None:
            self.start = start
        if size is not None:
            self.size = size
        if sort is not None:
            self.sort = sort
        if order is not None:
            self.order = order
        if id is not None:
            self.id = id
        if activity_id is not None:
            self.activity_id = activity_id
        if parent_id is not None:
            self.parent_id = parent_id
        if process_instance_id is not None:
            self.process_instance_id = process_instance_id
        if process_business_key is not None:
            self.process_business_key = process_business_key
        if process_definition_id is not None:
            self.process_definition_id = process_definition_id
        if process_definition_key is not None:
            self.process_definition_key = process_definition_key
        if signal_event_subscription_name is not None:
            self.signal_event_subscription_name = signal_event_subscription_name
        if message_event_subscription_name is not None:
            self.message_event_subscription_name = message_event_subscription_name
        if variables is not None:
            self.variables = variables
        if process_instance_variables is not None:
            self.process_instance_variables = process_instance_variables
        if tenant_id is not None:
            self.tenant_id = tenant_id
        if tenant_id_like is not None:
            self.tenant_id_like = tenant_id_like
        if without_tenant_id is not None:
            self.without_tenant_id = without_tenant_id

    @property
    def start(self):
        """Gets the start of this ExecutionQueryRequest.  # noqa: E501


        :return: The start of this ExecutionQueryRequest.  # noqa: E501
        :rtype: int
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this ExecutionQueryRequest.


        :param start: The start of this ExecutionQueryRequest.  # noqa: E501
        :type: int
        """

        self._start = start

    @property
    def size(self):
        """Gets the size of this ExecutionQueryRequest.  # noqa: E501


        :return: The size of this ExecutionQueryRequest.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this ExecutionQueryRequest.


        :param size: The size of this ExecutionQueryRequest.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def sort(self):
        """Gets the sort of this ExecutionQueryRequest.  # noqa: E501


        :return: The sort of this ExecutionQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._sort

    @sort.setter
    def sort(self, sort):
        """Sets the sort of this ExecutionQueryRequest.


        :param sort: The sort of this ExecutionQueryRequest.  # noqa: E501
        :type: str
        """

        self._sort = sort

    @property
    def order(self):
        """Gets the order of this ExecutionQueryRequest.  # noqa: E501


        :return: The order of this ExecutionQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this ExecutionQueryRequest.


        :param order: The order of this ExecutionQueryRequest.  # noqa: E501
        :type: str
        """

        self._order = order

    @property
    def id(self):
        """Gets the id of this ExecutionQueryRequest.  # noqa: E501


        :return: The id of this ExecutionQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ExecutionQueryRequest.


        :param id: The id of this ExecutionQueryRequest.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def activity_id(self):
        """Gets the activity_id of this ExecutionQueryRequest.  # noqa: E501


        :return: The activity_id of this ExecutionQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._activity_id

    @activity_id.setter
    def activity_id(self, activity_id):
        """Sets the activity_id of this ExecutionQueryRequest.


        :param activity_id: The activity_id of this ExecutionQueryRequest.  # noqa: E501
        :type: str
        """

        self._activity_id = activity_id

    @property
    def parent_id(self):
        """Gets the parent_id of this ExecutionQueryRequest.  # noqa: E501


        :return: The parent_id of this ExecutionQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id):
        """Sets the parent_id of this ExecutionQueryRequest.


        :param parent_id: The parent_id of this ExecutionQueryRequest.  # noqa: E501
        :type: str
        """

        self._parent_id = parent_id

    @property
    def process_instance_id(self):
        """Gets the process_instance_id of this ExecutionQueryRequest.  # noqa: E501


        :return: The process_instance_id of this ExecutionQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._process_instance_id

    @process_instance_id.setter
    def process_instance_id(self, process_instance_id):
        """Sets the process_instance_id of this ExecutionQueryRequest.


        :param process_instance_id: The process_instance_id of this ExecutionQueryRequest.  # noqa: E501
        :type: str
        """

        self._process_instance_id = process_instance_id

    @property
    def process_business_key(self):
        """Gets the process_business_key of this ExecutionQueryRequest.  # noqa: E501


        :return: The process_business_key of this ExecutionQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._process_business_key

    @process_business_key.setter
    def process_business_key(self, process_business_key):
        """Sets the process_business_key of this ExecutionQueryRequest.


        :param process_business_key: The process_business_key of this ExecutionQueryRequest.  # noqa: E501
        :type: str
        """

        self._process_business_key = process_business_key

    @property
    def process_definition_id(self):
        """Gets the process_definition_id of this ExecutionQueryRequest.  # noqa: E501


        :return: The process_definition_id of this ExecutionQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._process_definition_id

    @process_definition_id.setter
    def process_definition_id(self, process_definition_id):
        """Sets the process_definition_id of this ExecutionQueryRequest.


        :param process_definition_id: The process_definition_id of this ExecutionQueryRequest.  # noqa: E501
        :type: str
        """

        self._process_definition_id = process_definition_id

    @property
    def process_definition_key(self):
        """Gets the process_definition_key of this ExecutionQueryRequest.  # noqa: E501


        :return: The process_definition_key of this ExecutionQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._process_definition_key

    @process_definition_key.setter
    def process_definition_key(self, process_definition_key):
        """Sets the process_definition_key of this ExecutionQueryRequest.


        :param process_definition_key: The process_definition_key of this ExecutionQueryRequest.  # noqa: E501
        :type: str
        """

        self._process_definition_key = process_definition_key

    @property
    def signal_event_subscription_name(self):
        """Gets the signal_event_subscription_name of this ExecutionQueryRequest.  # noqa: E501


        :return: The signal_event_subscription_name of this ExecutionQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._signal_event_subscription_name

    @signal_event_subscription_name.setter
    def signal_event_subscription_name(self, signal_event_subscription_name):
        """Sets the signal_event_subscription_name of this ExecutionQueryRequest.


        :param signal_event_subscription_name: The signal_event_subscription_name of this ExecutionQueryRequest.  # noqa: E501
        :type: str
        """

        self._signal_event_subscription_name = signal_event_subscription_name

    @property
    def message_event_subscription_name(self):
        """Gets the message_event_subscription_name of this ExecutionQueryRequest.  # noqa: E501


        :return: The message_event_subscription_name of this ExecutionQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._message_event_subscription_name

    @message_event_subscription_name.setter
    def message_event_subscription_name(self, message_event_subscription_name):
        """Sets the message_event_subscription_name of this ExecutionQueryRequest.


        :param message_event_subscription_name: The message_event_subscription_name of this ExecutionQueryRequest.  # noqa: E501
        :type: str
        """

        self._message_event_subscription_name = message_event_subscription_name

    @property
    def variables(self):
        """Gets the variables of this ExecutionQueryRequest.  # noqa: E501


        :return: The variables of this ExecutionQueryRequest.  # noqa: E501
        :rtype: list[QueryVariable]
        """
        return self._variables

    @variables.setter
    def variables(self, variables):
        """Sets the variables of this ExecutionQueryRequest.


        :param variables: The variables of this ExecutionQueryRequest.  # noqa: E501
        :type: list[QueryVariable]
        """

        self._variables = variables

    @property
    def process_instance_variables(self):
        """Gets the process_instance_variables of this ExecutionQueryRequest.  # noqa: E501


        :return: The process_instance_variables of this ExecutionQueryRequest.  # noqa: E501
        :rtype: list[QueryVariable]
        """
        return self._process_instance_variables

    @process_instance_variables.setter
    def process_instance_variables(self, process_instance_variables):
        """Sets the process_instance_variables of this ExecutionQueryRequest.


        :param process_instance_variables: The process_instance_variables of this ExecutionQueryRequest.  # noqa: E501
        :type: list[QueryVariable]
        """

        self._process_instance_variables = process_instance_variables

    @property
    def tenant_id(self):
        """Gets the tenant_id of this ExecutionQueryRequest.  # noqa: E501


        :return: The tenant_id of this ExecutionQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this ExecutionQueryRequest.


        :param tenant_id: The tenant_id of this ExecutionQueryRequest.  # noqa: E501
        :type: str
        """

        self._tenant_id = tenant_id

    @property
    def tenant_id_like(self):
        """Gets the tenant_id_like of this ExecutionQueryRequest.  # noqa: E501


        :return: The tenant_id_like of this ExecutionQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id_like

    @tenant_id_like.setter
    def tenant_id_like(self, tenant_id_like):
        """Sets the tenant_id_like of this ExecutionQueryRequest.


        :param tenant_id_like: The tenant_id_like of this ExecutionQueryRequest.  # noqa: E501
        :type: str
        """

        self._tenant_id_like = tenant_id_like

    @property
    def without_tenant_id(self):
        """Gets the without_tenant_id of this ExecutionQueryRequest.  # noqa: E501


        :return: The without_tenant_id of this ExecutionQueryRequest.  # noqa: E501
        :rtype: bool
        """
        return self._without_tenant_id

    @without_tenant_id.setter
    def without_tenant_id(self, without_tenant_id):
        """Sets the without_tenant_id of this ExecutionQueryRequest.


        :param without_tenant_id: The without_tenant_id of this ExecutionQueryRequest.  # noqa: E501
        :type: bool
        """

        self._without_tenant_id = without_tenant_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExecutionQueryRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExecutionQueryRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
