# coding: utf-8

"""
    Flowable REST API

    # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ExecutionActionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'action': 'str',
        'signal_name': 'str',
        'message_name': 'str',
        'variables': 'list[RestVariable]',
        'transient_variables': 'list[RestVariable]'
    }

    attribute_map = {
        'action': 'action',
        'signal_name': 'signalName',
        'message_name': 'messageName',
        'variables': 'variables',
        'transient_variables': 'transientVariables'
    }

    def __init__(self, action=None, signal_name=None, message_name=None, variables=None, transient_variables=None):  # noqa: E501
        """ExecutionActionRequest - a model defined in Swagger"""  # noqa: E501

        self._action = None
        self._signal_name = None
        self._message_name = None
        self._variables = None
        self._transient_variables = None
        self.discriminator = None

        self.action = action
        if signal_name is not None:
            self.signal_name = signal_name
        if message_name is not None:
            self.message_name = message_name
        if variables is not None:
            self.variables = variables
        if transient_variables is not None:
            self.transient_variables = transient_variables

    @property
    def action(self):
        """Gets the action of this ExecutionActionRequest.  # noqa: E501

        Action to perform: Either signal, trigger, signalEventReceived or messageEventReceived  # noqa: E501

        :return: The action of this ExecutionActionRequest.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this ExecutionActionRequest.

        Action to perform: Either signal, trigger, signalEventReceived or messageEventReceived  # noqa: E501

        :param action: The action of this ExecutionActionRequest.  # noqa: E501
        :type: str
        """
        if action is None:
            raise ValueError("Invalid value for `action`, must not be `None`")  # noqa: E501

        self._action = action

    @property
    def signal_name(self):
        """Gets the signal_name of this ExecutionActionRequest.  # noqa: E501

        Name of the signal  # noqa: E501

        :return: The signal_name of this ExecutionActionRequest.  # noqa: E501
        :rtype: str
        """
        return self._signal_name

    @signal_name.setter
    def signal_name(self, signal_name):
        """Sets the signal_name of this ExecutionActionRequest.

        Name of the signal  # noqa: E501

        :param signal_name: The signal_name of this ExecutionActionRequest.  # noqa: E501
        :type: str
        """

        self._signal_name = signal_name

    @property
    def message_name(self):
        """Gets the message_name of this ExecutionActionRequest.  # noqa: E501

        Message of the signal  # noqa: E501

        :return: The message_name of this ExecutionActionRequest.  # noqa: E501
        :rtype: str
        """
        return self._message_name

    @message_name.setter
    def message_name(self, message_name):
        """Sets the message_name of this ExecutionActionRequest.

        Message of the signal  # noqa: E501

        :param message_name: The message_name of this ExecutionActionRequest.  # noqa: E501
        :type: str
        """

        self._message_name = message_name

    @property
    def variables(self):
        """Gets the variables of this ExecutionActionRequest.  # noqa: E501


        :return: The variables of this ExecutionActionRequest.  # noqa: E501
        :rtype: list[RestVariable]
        """
        return self._variables

    @variables.setter
    def variables(self, variables):
        """Sets the variables of this ExecutionActionRequest.


        :param variables: The variables of this ExecutionActionRequest.  # noqa: E501
        :type: list[RestVariable]
        """

        self._variables = variables

    @property
    def transient_variables(self):
        """Gets the transient_variables of this ExecutionActionRequest.  # noqa: E501


        :return: The transient_variables of this ExecutionActionRequest.  # noqa: E501
        :rtype: list[RestVariable]
        """
        return self._transient_variables

    @transient_variables.setter
    def transient_variables(self, transient_variables):
        """Sets the transient_variables of this ExecutionActionRequest.


        :param transient_variables: The transient_variables of this ExecutionActionRequest.  # noqa: E501
        :type: list[RestVariable]
        """

        self._transient_variables = transient_variables

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExecutionActionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExecutionActionRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
