# coding: utf-8

"""
    Flowable REST API

    # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class HistoricTaskInstanceResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'process_definition_id': 'str',
        'process_definition_url': 'str',
        'process_instance_id': 'str',
        'process_instance_url': 'str',
        'execution_id': 'str',
        'name': 'str',
        'description': 'str',
        'delete_reason': 'str',
        'owner': 'str',
        'assignee': 'str',
        'start_time': 'datetime',
        'end_time': 'datetime',
        'duration_in_millis': 'int',
        'work_time_in_millis': 'int',
        'claim_time': 'datetime',
        'task_definition_key': 'str',
        'form_key': 'str',
        'priority': 'int',
        'due_date': 'datetime',
        'parent_task_id': 'str',
        'url': 'str',
        'variables': 'list[RestVariable]',
        'scope_definition_id': 'str',
        'scope_id': 'str',
        'scope_type': 'str',
        'tenant_id': 'str',
        'category': 'str'
    }

    attribute_map = {
        'id': 'id',
        'process_definition_id': 'processDefinitionId',
        'process_definition_url': 'processDefinitionUrl',
        'process_instance_id': 'processInstanceId',
        'process_instance_url': 'processInstanceUrl',
        'execution_id': 'executionId',
        'name': 'name',
        'description': 'description',
        'delete_reason': 'deleteReason',
        'owner': 'owner',
        'assignee': 'assignee',
        'start_time': 'startTime',
        'end_time': 'endTime',
        'duration_in_millis': 'durationInMillis',
        'work_time_in_millis': 'workTimeInMillis',
        'claim_time': 'claimTime',
        'task_definition_key': 'taskDefinitionKey',
        'form_key': 'formKey',
        'priority': 'priority',
        'due_date': 'dueDate',
        'parent_task_id': 'parentTaskId',
        'url': 'url',
        'variables': 'variables',
        'scope_definition_id': 'scopeDefinitionId',
        'scope_id': 'scopeId',
        'scope_type': 'scopeType',
        'tenant_id': 'tenantId',
        'category': 'category'
    }

    def __init__(self, id=None, process_definition_id=None, process_definition_url=None, process_instance_id=None, process_instance_url=None, execution_id=None, name=None, description=None, delete_reason=None, owner=None, assignee=None, start_time=None, end_time=None, duration_in_millis=None, work_time_in_millis=None, claim_time=None, task_definition_key=None, form_key=None, priority=None, due_date=None, parent_task_id=None, url=None, variables=None, scope_definition_id=None, scope_id=None, scope_type=None, tenant_id=None, category=None):  # noqa: E501
        """HistoricTaskInstanceResponse - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._process_definition_id = None
        self._process_definition_url = None
        self._process_instance_id = None
        self._process_instance_url = None
        self._execution_id = None
        self._name = None
        self._description = None
        self._delete_reason = None
        self._owner = None
        self._assignee = None
        self._start_time = None
        self._end_time = None
        self._duration_in_millis = None
        self._work_time_in_millis = None
        self._claim_time = None
        self._task_definition_key = None
        self._form_key = None
        self._priority = None
        self._due_date = None
        self._parent_task_id = None
        self._url = None
        self._variables = None
        self._scope_definition_id = None
        self._scope_id = None
        self._scope_type = None
        self._tenant_id = None
        self._category = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if process_definition_id is not None:
            self.process_definition_id = process_definition_id
        if process_definition_url is not None:
            self.process_definition_url = process_definition_url
        if process_instance_id is not None:
            self.process_instance_id = process_instance_id
        if process_instance_url is not None:
            self.process_instance_url = process_instance_url
        if execution_id is not None:
            self.execution_id = execution_id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if delete_reason is not None:
            self.delete_reason = delete_reason
        if owner is not None:
            self.owner = owner
        if assignee is not None:
            self.assignee = assignee
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time
        if duration_in_millis is not None:
            self.duration_in_millis = duration_in_millis
        if work_time_in_millis is not None:
            self.work_time_in_millis = work_time_in_millis
        if claim_time is not None:
            self.claim_time = claim_time
        if task_definition_key is not None:
            self.task_definition_key = task_definition_key
        if form_key is not None:
            self.form_key = form_key
        if priority is not None:
            self.priority = priority
        if due_date is not None:
            self.due_date = due_date
        if parent_task_id is not None:
            self.parent_task_id = parent_task_id
        if url is not None:
            self.url = url
        if variables is not None:
            self.variables = variables
        if scope_definition_id is not None:
            self.scope_definition_id = scope_definition_id
        if scope_id is not None:
            self.scope_id = scope_id
        if scope_type is not None:
            self.scope_type = scope_type
        if tenant_id is not None:
            self.tenant_id = tenant_id
        if category is not None:
            self.category = category

    @property
    def id(self):
        """Gets the id of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The id of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this HistoricTaskInstanceResponse.


        :param id: The id of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def process_definition_id(self):
        """Gets the process_definition_id of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The process_definition_id of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_definition_id

    @process_definition_id.setter
    def process_definition_id(self, process_definition_id):
        """Sets the process_definition_id of this HistoricTaskInstanceResponse.


        :param process_definition_id: The process_definition_id of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._process_definition_id = process_definition_id

    @property
    def process_definition_url(self):
        """Gets the process_definition_url of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The process_definition_url of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_definition_url

    @process_definition_url.setter
    def process_definition_url(self, process_definition_url):
        """Sets the process_definition_url of this HistoricTaskInstanceResponse.


        :param process_definition_url: The process_definition_url of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._process_definition_url = process_definition_url

    @property
    def process_instance_id(self):
        """Gets the process_instance_id of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The process_instance_id of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_instance_id

    @process_instance_id.setter
    def process_instance_id(self, process_instance_id):
        """Sets the process_instance_id of this HistoricTaskInstanceResponse.


        :param process_instance_id: The process_instance_id of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._process_instance_id = process_instance_id

    @property
    def process_instance_url(self):
        """Gets the process_instance_url of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The process_instance_url of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_instance_url

    @process_instance_url.setter
    def process_instance_url(self, process_instance_url):
        """Sets the process_instance_url of this HistoricTaskInstanceResponse.


        :param process_instance_url: The process_instance_url of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._process_instance_url = process_instance_url

    @property
    def execution_id(self):
        """Gets the execution_id of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The execution_id of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._execution_id

    @execution_id.setter
    def execution_id(self, execution_id):
        """Sets the execution_id of this HistoricTaskInstanceResponse.


        :param execution_id: The execution_id of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._execution_id = execution_id

    @property
    def name(self):
        """Gets the name of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The name of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this HistoricTaskInstanceResponse.


        :param name: The name of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The description of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this HistoricTaskInstanceResponse.


        :param description: The description of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def delete_reason(self):
        """Gets the delete_reason of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The delete_reason of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._delete_reason

    @delete_reason.setter
    def delete_reason(self, delete_reason):
        """Sets the delete_reason of this HistoricTaskInstanceResponse.


        :param delete_reason: The delete_reason of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._delete_reason = delete_reason

    @property
    def owner(self):
        """Gets the owner of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The owner of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this HistoricTaskInstanceResponse.


        :param owner: The owner of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def assignee(self):
        """Gets the assignee of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The assignee of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._assignee

    @assignee.setter
    def assignee(self, assignee):
        """Sets the assignee of this HistoricTaskInstanceResponse.


        :param assignee: The assignee of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._assignee = assignee

    @property
    def start_time(self):
        """Gets the start_time of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The start_time of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this HistoricTaskInstanceResponse.


        :param start_time: The start_time of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The end_time of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this HistoricTaskInstanceResponse.


        :param end_time: The end_time of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: datetime
        """

        self._end_time = end_time

    @property
    def duration_in_millis(self):
        """Gets the duration_in_millis of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The duration_in_millis of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: int
        """
        return self._duration_in_millis

    @duration_in_millis.setter
    def duration_in_millis(self, duration_in_millis):
        """Sets the duration_in_millis of this HistoricTaskInstanceResponse.


        :param duration_in_millis: The duration_in_millis of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: int
        """

        self._duration_in_millis = duration_in_millis

    @property
    def work_time_in_millis(self):
        """Gets the work_time_in_millis of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The work_time_in_millis of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: int
        """
        return self._work_time_in_millis

    @work_time_in_millis.setter
    def work_time_in_millis(self, work_time_in_millis):
        """Sets the work_time_in_millis of this HistoricTaskInstanceResponse.


        :param work_time_in_millis: The work_time_in_millis of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: int
        """

        self._work_time_in_millis = work_time_in_millis

    @property
    def claim_time(self):
        """Gets the claim_time of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The claim_time of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._claim_time

    @claim_time.setter
    def claim_time(self, claim_time):
        """Sets the claim_time of this HistoricTaskInstanceResponse.


        :param claim_time: The claim_time of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: datetime
        """

        self._claim_time = claim_time

    @property
    def task_definition_key(self):
        """Gets the task_definition_key of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The task_definition_key of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._task_definition_key

    @task_definition_key.setter
    def task_definition_key(self, task_definition_key):
        """Sets the task_definition_key of this HistoricTaskInstanceResponse.


        :param task_definition_key: The task_definition_key of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._task_definition_key = task_definition_key

    @property
    def form_key(self):
        """Gets the form_key of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The form_key of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._form_key

    @form_key.setter
    def form_key(self, form_key):
        """Sets the form_key of this HistoricTaskInstanceResponse.


        :param form_key: The form_key of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._form_key = form_key

    @property
    def priority(self):
        """Gets the priority of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The priority of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: int
        """
        return self._priority

    @priority.setter
    def priority(self, priority):
        """Sets the priority of this HistoricTaskInstanceResponse.


        :param priority: The priority of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: int
        """

        self._priority = priority

    @property
    def due_date(self):
        """Gets the due_date of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The due_date of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._due_date

    @due_date.setter
    def due_date(self, due_date):
        """Sets the due_date of this HistoricTaskInstanceResponse.


        :param due_date: The due_date of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: datetime
        """

        self._due_date = due_date

    @property
    def parent_task_id(self):
        """Gets the parent_task_id of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The parent_task_id of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._parent_task_id

    @parent_task_id.setter
    def parent_task_id(self, parent_task_id):
        """Sets the parent_task_id of this HistoricTaskInstanceResponse.


        :param parent_task_id: The parent_task_id of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._parent_task_id = parent_task_id

    @property
    def url(self):
        """Gets the url of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The url of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this HistoricTaskInstanceResponse.


        :param url: The url of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def variables(self):
        """Gets the variables of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The variables of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: list[RestVariable]
        """
        return self._variables

    @variables.setter
    def variables(self, variables):
        """Sets the variables of this HistoricTaskInstanceResponse.


        :param variables: The variables of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: list[RestVariable]
        """

        self._variables = variables

    @property
    def scope_definition_id(self):
        """Gets the scope_definition_id of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The scope_definition_id of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._scope_definition_id

    @scope_definition_id.setter
    def scope_definition_id(self, scope_definition_id):
        """Sets the scope_definition_id of this HistoricTaskInstanceResponse.


        :param scope_definition_id: The scope_definition_id of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._scope_definition_id = scope_definition_id

    @property
    def scope_id(self):
        """Gets the scope_id of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The scope_id of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._scope_id

    @scope_id.setter
    def scope_id(self, scope_id):
        """Sets the scope_id of this HistoricTaskInstanceResponse.


        :param scope_id: The scope_id of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._scope_id = scope_id

    @property
    def scope_type(self):
        """Gets the scope_type of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The scope_type of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._scope_type

    @scope_type.setter
    def scope_type(self, scope_type):
        """Sets the scope_type of this HistoricTaskInstanceResponse.


        :param scope_type: The scope_type of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._scope_type = scope_type

    @property
    def tenant_id(self):
        """Gets the tenant_id of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The tenant_id of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this HistoricTaskInstanceResponse.


        :param tenant_id: The tenant_id of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._tenant_id = tenant_id

    @property
    def category(self):
        """Gets the category of this HistoricTaskInstanceResponse.  # noqa: E501


        :return: The category of this HistoricTaskInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this HistoricTaskInstanceResponse.


        :param category: The category of this HistoricTaskInstanceResponse.  # noqa: E501
        :type: str
        """

        self._category = category

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HistoricTaskInstanceResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HistoricTaskInstanceResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
