# coding: utf-8

"""
    Flowable REST API

    # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class HistoricActivityInstanceResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'activity_id': 'str',
        'activity_name': 'str',
        'activity_type': 'str',
        'process_definition_id': 'str',
        'process_definition_url': 'str',
        'process_instance_id': 'str',
        'process_instance_url': 'str',
        'execution_id': 'str',
        'task_id': 'str',
        'called_process_instance_id': 'str',
        'assignee': 'str',
        'start_time': 'datetime',
        'end_time': 'datetime',
        'duration_in_millis': 'int',
        'tenant_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'activity_id': 'activityId',
        'activity_name': 'activityName',
        'activity_type': 'activityType',
        'process_definition_id': 'processDefinitionId',
        'process_definition_url': 'processDefinitionUrl',
        'process_instance_id': 'processInstanceId',
        'process_instance_url': 'processInstanceUrl',
        'execution_id': 'executionId',
        'task_id': 'taskId',
        'called_process_instance_id': 'calledProcessInstanceId',
        'assignee': 'assignee',
        'start_time': 'startTime',
        'end_time': 'endTime',
        'duration_in_millis': 'durationInMillis',
        'tenant_id': 'tenantId'
    }

    def __init__(self, id=None, activity_id=None, activity_name=None, activity_type=None, process_definition_id=None, process_definition_url=None, process_instance_id=None, process_instance_url=None, execution_id=None, task_id=None, called_process_instance_id=None, assignee=None, start_time=None, end_time=None, duration_in_millis=None, tenant_id=None):  # noqa: E501
        """HistoricActivityInstanceResponse - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._activity_id = None
        self._activity_name = None
        self._activity_type = None
        self._process_definition_id = None
        self._process_definition_url = None
        self._process_instance_id = None
        self._process_instance_url = None
        self._execution_id = None
        self._task_id = None
        self._called_process_instance_id = None
        self._assignee = None
        self._start_time = None
        self._end_time = None
        self._duration_in_millis = None
        self._tenant_id = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if activity_id is not None:
            self.activity_id = activity_id
        if activity_name is not None:
            self.activity_name = activity_name
        if activity_type is not None:
            self.activity_type = activity_type
        if process_definition_id is not None:
            self.process_definition_id = process_definition_id
        if process_definition_url is not None:
            self.process_definition_url = process_definition_url
        if process_instance_id is not None:
            self.process_instance_id = process_instance_id
        if process_instance_url is not None:
            self.process_instance_url = process_instance_url
        if execution_id is not None:
            self.execution_id = execution_id
        if task_id is not None:
            self.task_id = task_id
        if called_process_instance_id is not None:
            self.called_process_instance_id = called_process_instance_id
        if assignee is not None:
            self.assignee = assignee
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time
        if duration_in_millis is not None:
            self.duration_in_millis = duration_in_millis
        if tenant_id is not None:
            self.tenant_id = tenant_id

    @property
    def id(self):
        """Gets the id of this HistoricActivityInstanceResponse.  # noqa: E501


        :return: The id of this HistoricActivityInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this HistoricActivityInstanceResponse.


        :param id: The id of this HistoricActivityInstanceResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def activity_id(self):
        """Gets the activity_id of this HistoricActivityInstanceResponse.  # noqa: E501


        :return: The activity_id of this HistoricActivityInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._activity_id

    @activity_id.setter
    def activity_id(self, activity_id):
        """Sets the activity_id of this HistoricActivityInstanceResponse.


        :param activity_id: The activity_id of this HistoricActivityInstanceResponse.  # noqa: E501
        :type: str
        """

        self._activity_id = activity_id

    @property
    def activity_name(self):
        """Gets the activity_name of this HistoricActivityInstanceResponse.  # noqa: E501


        :return: The activity_name of this HistoricActivityInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._activity_name

    @activity_name.setter
    def activity_name(self, activity_name):
        """Sets the activity_name of this HistoricActivityInstanceResponse.


        :param activity_name: The activity_name of this HistoricActivityInstanceResponse.  # noqa: E501
        :type: str
        """

        self._activity_name = activity_name

    @property
    def activity_type(self):
        """Gets the activity_type of this HistoricActivityInstanceResponse.  # noqa: E501


        :return: The activity_type of this HistoricActivityInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._activity_type

    @activity_type.setter
    def activity_type(self, activity_type):
        """Sets the activity_type of this HistoricActivityInstanceResponse.


        :param activity_type: The activity_type of this HistoricActivityInstanceResponse.  # noqa: E501
        :type: str
        """

        self._activity_type = activity_type

    @property
    def process_definition_id(self):
        """Gets the process_definition_id of this HistoricActivityInstanceResponse.  # noqa: E501


        :return: The process_definition_id of this HistoricActivityInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_definition_id

    @process_definition_id.setter
    def process_definition_id(self, process_definition_id):
        """Sets the process_definition_id of this HistoricActivityInstanceResponse.


        :param process_definition_id: The process_definition_id of this HistoricActivityInstanceResponse.  # noqa: E501
        :type: str
        """

        self._process_definition_id = process_definition_id

    @property
    def process_definition_url(self):
        """Gets the process_definition_url of this HistoricActivityInstanceResponse.  # noqa: E501


        :return: The process_definition_url of this HistoricActivityInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_definition_url

    @process_definition_url.setter
    def process_definition_url(self, process_definition_url):
        """Sets the process_definition_url of this HistoricActivityInstanceResponse.


        :param process_definition_url: The process_definition_url of this HistoricActivityInstanceResponse.  # noqa: E501
        :type: str
        """

        self._process_definition_url = process_definition_url

    @property
    def process_instance_id(self):
        """Gets the process_instance_id of this HistoricActivityInstanceResponse.  # noqa: E501


        :return: The process_instance_id of this HistoricActivityInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_instance_id

    @process_instance_id.setter
    def process_instance_id(self, process_instance_id):
        """Sets the process_instance_id of this HistoricActivityInstanceResponse.


        :param process_instance_id: The process_instance_id of this HistoricActivityInstanceResponse.  # noqa: E501
        :type: str
        """

        self._process_instance_id = process_instance_id

    @property
    def process_instance_url(self):
        """Gets the process_instance_url of this HistoricActivityInstanceResponse.  # noqa: E501


        :return: The process_instance_url of this HistoricActivityInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_instance_url

    @process_instance_url.setter
    def process_instance_url(self, process_instance_url):
        """Sets the process_instance_url of this HistoricActivityInstanceResponse.


        :param process_instance_url: The process_instance_url of this HistoricActivityInstanceResponse.  # noqa: E501
        :type: str
        """

        self._process_instance_url = process_instance_url

    @property
    def execution_id(self):
        """Gets the execution_id of this HistoricActivityInstanceResponse.  # noqa: E501


        :return: The execution_id of this HistoricActivityInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._execution_id

    @execution_id.setter
    def execution_id(self, execution_id):
        """Sets the execution_id of this HistoricActivityInstanceResponse.


        :param execution_id: The execution_id of this HistoricActivityInstanceResponse.  # noqa: E501
        :type: str
        """

        self._execution_id = execution_id

    @property
    def task_id(self):
        """Gets the task_id of this HistoricActivityInstanceResponse.  # noqa: E501


        :return: The task_id of this HistoricActivityInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this HistoricActivityInstanceResponse.


        :param task_id: The task_id of this HistoricActivityInstanceResponse.  # noqa: E501
        :type: str
        """

        self._task_id = task_id

    @property
    def called_process_instance_id(self):
        """Gets the called_process_instance_id of this HistoricActivityInstanceResponse.  # noqa: E501


        :return: The called_process_instance_id of this HistoricActivityInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._called_process_instance_id

    @called_process_instance_id.setter
    def called_process_instance_id(self, called_process_instance_id):
        """Sets the called_process_instance_id of this HistoricActivityInstanceResponse.


        :param called_process_instance_id: The called_process_instance_id of this HistoricActivityInstanceResponse.  # noqa: E501
        :type: str
        """

        self._called_process_instance_id = called_process_instance_id

    @property
    def assignee(self):
        """Gets the assignee of this HistoricActivityInstanceResponse.  # noqa: E501


        :return: The assignee of this HistoricActivityInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._assignee

    @assignee.setter
    def assignee(self, assignee):
        """Sets the assignee of this HistoricActivityInstanceResponse.


        :param assignee: The assignee of this HistoricActivityInstanceResponse.  # noqa: E501
        :type: str
        """

        self._assignee = assignee

    @property
    def start_time(self):
        """Gets the start_time of this HistoricActivityInstanceResponse.  # noqa: E501


        :return: The start_time of this HistoricActivityInstanceResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this HistoricActivityInstanceResponse.


        :param start_time: The start_time of this HistoricActivityInstanceResponse.  # noqa: E501
        :type: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this HistoricActivityInstanceResponse.  # noqa: E501


        :return: The end_time of this HistoricActivityInstanceResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this HistoricActivityInstanceResponse.


        :param end_time: The end_time of this HistoricActivityInstanceResponse.  # noqa: E501
        :type: datetime
        """

        self._end_time = end_time

    @property
    def duration_in_millis(self):
        """Gets the duration_in_millis of this HistoricActivityInstanceResponse.  # noqa: E501


        :return: The duration_in_millis of this HistoricActivityInstanceResponse.  # noqa: E501
        :rtype: int
        """
        return self._duration_in_millis

    @duration_in_millis.setter
    def duration_in_millis(self, duration_in_millis):
        """Sets the duration_in_millis of this HistoricActivityInstanceResponse.


        :param duration_in_millis: The duration_in_millis of this HistoricActivityInstanceResponse.  # noqa: E501
        :type: int
        """

        self._duration_in_millis = duration_in_millis

    @property
    def tenant_id(self):
        """Gets the tenant_id of this HistoricActivityInstanceResponse.  # noqa: E501


        :return: The tenant_id of this HistoricActivityInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this HistoricActivityInstanceResponse.


        :param tenant_id: The tenant_id of this HistoricActivityInstanceResponse.  # noqa: E501
        :type: str
        """

        self._tenant_id = tenant_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HistoricActivityInstanceResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HistoricActivityInstanceResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
