# coding: utf-8

"""
    Flowable REST API

    # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class HistoricProcessInstanceResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'url': 'str',
        'name': 'str',
        'business_key': 'str',
        'process_definition_id': 'str',
        'process_definition_url': 'str',
        'process_definition_name': 'str',
        'process_definition_description': 'str',
        'start_time': 'datetime',
        'end_time': 'datetime',
        'duration_in_millis': 'int',
        'start_user_id': 'str',
        'start_activity_id': 'str',
        'end_activity_id': 'str',
        'delete_reason': 'str',
        'super_process_instance_id': 'str',
        'variables': 'list[RestVariable]',
        'callback_id': 'str',
        'callback_type': 'str',
        'tenant_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'url': 'url',
        'name': 'name',
        'business_key': 'businessKey',
        'process_definition_id': 'processDefinitionId',
        'process_definition_url': 'processDefinitionUrl',
        'process_definition_name': 'processDefinitionName',
        'process_definition_description': 'processDefinitionDescription',
        'start_time': 'startTime',
        'end_time': 'endTime',
        'duration_in_millis': 'durationInMillis',
        'start_user_id': 'startUserId',
        'start_activity_id': 'startActivityId',
        'end_activity_id': 'endActivityId',
        'delete_reason': 'deleteReason',
        'super_process_instance_id': 'superProcessInstanceId',
        'variables': 'variables',
        'callback_id': 'callbackId',
        'callback_type': 'callbackType',
        'tenant_id': 'tenantId'
    }

    def __init__(self, id=None, url=None, name=None, business_key=None, process_definition_id=None, process_definition_url=None, process_definition_name=None, process_definition_description=None, start_time=None, end_time=None, duration_in_millis=None, start_user_id=None, start_activity_id=None, end_activity_id=None, delete_reason=None, super_process_instance_id=None, variables=None, callback_id=None, callback_type=None, tenant_id=None):  # noqa: E501
        """HistoricProcessInstanceResponse - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._url = None
        self._name = None
        self._business_key = None
        self._process_definition_id = None
        self._process_definition_url = None
        self._process_definition_name = None
        self._process_definition_description = None
        self._start_time = None
        self._end_time = None
        self._duration_in_millis = None
        self._start_user_id = None
        self._start_activity_id = None
        self._end_activity_id = None
        self._delete_reason = None
        self._super_process_instance_id = None
        self._variables = None
        self._callback_id = None
        self._callback_type = None
        self._tenant_id = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if url is not None:
            self.url = url
        if name is not None:
            self.name = name
        if business_key is not None:
            self.business_key = business_key
        if process_definition_id is not None:
            self.process_definition_id = process_definition_id
        if process_definition_url is not None:
            self.process_definition_url = process_definition_url
        if process_definition_name is not None:
            self.process_definition_name = process_definition_name
        if process_definition_description is not None:
            self.process_definition_description = process_definition_description
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time
        if duration_in_millis is not None:
            self.duration_in_millis = duration_in_millis
        if start_user_id is not None:
            self.start_user_id = start_user_id
        if start_activity_id is not None:
            self.start_activity_id = start_activity_id
        if end_activity_id is not None:
            self.end_activity_id = end_activity_id
        if delete_reason is not None:
            self.delete_reason = delete_reason
        if super_process_instance_id is not None:
            self.super_process_instance_id = super_process_instance_id
        if variables is not None:
            self.variables = variables
        if callback_id is not None:
            self.callback_id = callback_id
        if callback_type is not None:
            self.callback_type = callback_type
        if tenant_id is not None:
            self.tenant_id = tenant_id

    @property
    def id(self):
        """Gets the id of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The id of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this HistoricProcessInstanceResponse.


        :param id: The id of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def url(self):
        """Gets the url of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The url of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this HistoricProcessInstanceResponse.


        :param url: The url of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def name(self):
        """Gets the name of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The name of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this HistoricProcessInstanceResponse.


        :param name: The name of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def business_key(self):
        """Gets the business_key of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The business_key of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._business_key

    @business_key.setter
    def business_key(self, business_key):
        """Sets the business_key of this HistoricProcessInstanceResponse.


        :param business_key: The business_key of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: str
        """

        self._business_key = business_key

    @property
    def process_definition_id(self):
        """Gets the process_definition_id of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The process_definition_id of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_definition_id

    @process_definition_id.setter
    def process_definition_id(self, process_definition_id):
        """Sets the process_definition_id of this HistoricProcessInstanceResponse.


        :param process_definition_id: The process_definition_id of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: str
        """

        self._process_definition_id = process_definition_id

    @property
    def process_definition_url(self):
        """Gets the process_definition_url of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The process_definition_url of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_definition_url

    @process_definition_url.setter
    def process_definition_url(self, process_definition_url):
        """Sets the process_definition_url of this HistoricProcessInstanceResponse.


        :param process_definition_url: The process_definition_url of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: str
        """

        self._process_definition_url = process_definition_url

    @property
    def process_definition_name(self):
        """Gets the process_definition_name of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The process_definition_name of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_definition_name

    @process_definition_name.setter
    def process_definition_name(self, process_definition_name):
        """Sets the process_definition_name of this HistoricProcessInstanceResponse.


        :param process_definition_name: The process_definition_name of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: str
        """

        self._process_definition_name = process_definition_name

    @property
    def process_definition_description(self):
        """Gets the process_definition_description of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The process_definition_description of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_definition_description

    @process_definition_description.setter
    def process_definition_description(self, process_definition_description):
        """Sets the process_definition_description of this HistoricProcessInstanceResponse.


        :param process_definition_description: The process_definition_description of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: str
        """

        self._process_definition_description = process_definition_description

    @property
    def start_time(self):
        """Gets the start_time of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The start_time of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this HistoricProcessInstanceResponse.


        :param start_time: The start_time of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The end_time of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this HistoricProcessInstanceResponse.


        :param end_time: The end_time of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: datetime
        """

        self._end_time = end_time

    @property
    def duration_in_millis(self):
        """Gets the duration_in_millis of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The duration_in_millis of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: int
        """
        return self._duration_in_millis

    @duration_in_millis.setter
    def duration_in_millis(self, duration_in_millis):
        """Sets the duration_in_millis of this HistoricProcessInstanceResponse.


        :param duration_in_millis: The duration_in_millis of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: int
        """

        self._duration_in_millis = duration_in_millis

    @property
    def start_user_id(self):
        """Gets the start_user_id of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The start_user_id of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._start_user_id

    @start_user_id.setter
    def start_user_id(self, start_user_id):
        """Sets the start_user_id of this HistoricProcessInstanceResponse.


        :param start_user_id: The start_user_id of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: str
        """

        self._start_user_id = start_user_id

    @property
    def start_activity_id(self):
        """Gets the start_activity_id of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The start_activity_id of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._start_activity_id

    @start_activity_id.setter
    def start_activity_id(self, start_activity_id):
        """Sets the start_activity_id of this HistoricProcessInstanceResponse.


        :param start_activity_id: The start_activity_id of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: str
        """

        self._start_activity_id = start_activity_id

    @property
    def end_activity_id(self):
        """Gets the end_activity_id of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The end_activity_id of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._end_activity_id

    @end_activity_id.setter
    def end_activity_id(self, end_activity_id):
        """Sets the end_activity_id of this HistoricProcessInstanceResponse.


        :param end_activity_id: The end_activity_id of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: str
        """

        self._end_activity_id = end_activity_id

    @property
    def delete_reason(self):
        """Gets the delete_reason of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The delete_reason of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._delete_reason

    @delete_reason.setter
    def delete_reason(self, delete_reason):
        """Sets the delete_reason of this HistoricProcessInstanceResponse.


        :param delete_reason: The delete_reason of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: str
        """

        self._delete_reason = delete_reason

    @property
    def super_process_instance_id(self):
        """Gets the super_process_instance_id of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The super_process_instance_id of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._super_process_instance_id

    @super_process_instance_id.setter
    def super_process_instance_id(self, super_process_instance_id):
        """Sets the super_process_instance_id of this HistoricProcessInstanceResponse.


        :param super_process_instance_id: The super_process_instance_id of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: str
        """

        self._super_process_instance_id = super_process_instance_id

    @property
    def variables(self):
        """Gets the variables of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The variables of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: list[RestVariable]
        """
        return self._variables

    @variables.setter
    def variables(self, variables):
        """Sets the variables of this HistoricProcessInstanceResponse.


        :param variables: The variables of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: list[RestVariable]
        """

        self._variables = variables

    @property
    def callback_id(self):
        """Gets the callback_id of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The callback_id of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._callback_id

    @callback_id.setter
    def callback_id(self, callback_id):
        """Sets the callback_id of this HistoricProcessInstanceResponse.


        :param callback_id: The callback_id of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: str
        """

        self._callback_id = callback_id

    @property
    def callback_type(self):
        """Gets the callback_type of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The callback_type of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._callback_type

    @callback_type.setter
    def callback_type(self, callback_type):
        """Sets the callback_type of this HistoricProcessInstanceResponse.


        :param callback_type: The callback_type of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: str
        """

        self._callback_type = callback_type

    @property
    def tenant_id(self):
        """Gets the tenant_id of this HistoricProcessInstanceResponse.  # noqa: E501


        :return: The tenant_id of this HistoricProcessInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this HistoricProcessInstanceResponse.


        :param tenant_id: The tenant_id of this HistoricProcessInstanceResponse.  # noqa: E501
        :type: str
        """

        self._tenant_id = tenant_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HistoricProcessInstanceResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HistoricProcessInstanceResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
