# coding: utf-8

"""
    Flowable REST API

    # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class HistoricActivityInstanceQueryRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start': 'int',
        'size': 'int',
        'sort': 'str',
        'order': 'str',
        'activity_id': 'str',
        'activity_instance_id': 'str',
        'activity_name': 'str',
        'activity_type': 'str',
        'execution_id': 'str',
        'finished': 'bool',
        'task_assignee': 'str',
        'process_instance_id': 'str',
        'process_definition_id': 'str',
        'tenant_id': 'str',
        'tenant_id_like': 'str',
        'without_tenant_id': 'bool'
    }

    attribute_map = {
        'start': 'start',
        'size': 'size',
        'sort': 'sort',
        'order': 'order',
        'activity_id': 'activityId',
        'activity_instance_id': 'activityInstanceId',
        'activity_name': 'activityName',
        'activity_type': 'activityType',
        'execution_id': 'executionId',
        'finished': 'finished',
        'task_assignee': 'taskAssignee',
        'process_instance_id': 'processInstanceId',
        'process_definition_id': 'processDefinitionId',
        'tenant_id': 'tenantId',
        'tenant_id_like': 'tenantIdLike',
        'without_tenant_id': 'withoutTenantId'
    }

    def __init__(self, start=None, size=None, sort=None, order=None, activity_id=None, activity_instance_id=None, activity_name=None, activity_type=None, execution_id=None, finished=None, task_assignee=None, process_instance_id=None, process_definition_id=None, tenant_id=None, tenant_id_like=None, without_tenant_id=None):  # noqa: E501
        """HistoricActivityInstanceQueryRequest - a model defined in Swagger"""  # noqa: E501

        self._start = None
        self._size = None
        self._sort = None
        self._order = None
        self._activity_id = None
        self._activity_instance_id = None
        self._activity_name = None
        self._activity_type = None
        self._execution_id = None
        self._finished = None
        self._task_assignee = None
        self._process_instance_id = None
        self._process_definition_id = None
        self._tenant_id = None
        self._tenant_id_like = None
        self._without_tenant_id = None
        self.discriminator = None

        if start is not None:
            self.start = start
        if size is not None:
            self.size = size
        if sort is not None:
            self.sort = sort
        if order is not None:
            self.order = order
        if activity_id is not None:
            self.activity_id = activity_id
        if activity_instance_id is not None:
            self.activity_instance_id = activity_instance_id
        if activity_name is not None:
            self.activity_name = activity_name
        if activity_type is not None:
            self.activity_type = activity_type
        if execution_id is not None:
            self.execution_id = execution_id
        if finished is not None:
            self.finished = finished
        if task_assignee is not None:
            self.task_assignee = task_assignee
        if process_instance_id is not None:
            self.process_instance_id = process_instance_id
        if process_definition_id is not None:
            self.process_definition_id = process_definition_id
        if tenant_id is not None:
            self.tenant_id = tenant_id
        if tenant_id_like is not None:
            self.tenant_id_like = tenant_id_like
        if without_tenant_id is not None:
            self.without_tenant_id = without_tenant_id

    @property
    def start(self):
        """Gets the start of this HistoricActivityInstanceQueryRequest.  # noqa: E501


        :return: The start of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :rtype: int
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this HistoricActivityInstanceQueryRequest.


        :param start: The start of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :type: int
        """

        self._start = start

    @property
    def size(self):
        """Gets the size of this HistoricActivityInstanceQueryRequest.  # noqa: E501


        :return: The size of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this HistoricActivityInstanceQueryRequest.


        :param size: The size of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def sort(self):
        """Gets the sort of this HistoricActivityInstanceQueryRequest.  # noqa: E501


        :return: The sort of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._sort

    @sort.setter
    def sort(self, sort):
        """Sets the sort of this HistoricActivityInstanceQueryRequest.


        :param sort: The sort of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._sort = sort

    @property
    def order(self):
        """Gets the order of this HistoricActivityInstanceQueryRequest.  # noqa: E501


        :return: The order of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this HistoricActivityInstanceQueryRequest.


        :param order: The order of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._order = order

    @property
    def activity_id(self):
        """Gets the activity_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501


        :return: The activity_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._activity_id

    @activity_id.setter
    def activity_id(self, activity_id):
        """Sets the activity_id of this HistoricActivityInstanceQueryRequest.


        :param activity_id: The activity_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._activity_id = activity_id

    @property
    def activity_instance_id(self):
        """Gets the activity_instance_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501


        :return: The activity_instance_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._activity_instance_id

    @activity_instance_id.setter
    def activity_instance_id(self, activity_instance_id):
        """Sets the activity_instance_id of this HistoricActivityInstanceQueryRequest.


        :param activity_instance_id: The activity_instance_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._activity_instance_id = activity_instance_id

    @property
    def activity_name(self):
        """Gets the activity_name of this HistoricActivityInstanceQueryRequest.  # noqa: E501


        :return: The activity_name of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._activity_name

    @activity_name.setter
    def activity_name(self, activity_name):
        """Sets the activity_name of this HistoricActivityInstanceQueryRequest.


        :param activity_name: The activity_name of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._activity_name = activity_name

    @property
    def activity_type(self):
        """Gets the activity_type of this HistoricActivityInstanceQueryRequest.  # noqa: E501


        :return: The activity_type of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._activity_type

    @activity_type.setter
    def activity_type(self, activity_type):
        """Sets the activity_type of this HistoricActivityInstanceQueryRequest.


        :param activity_type: The activity_type of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._activity_type = activity_type

    @property
    def execution_id(self):
        """Gets the execution_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501


        :return: The execution_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._execution_id

    @execution_id.setter
    def execution_id(self, execution_id):
        """Sets the execution_id of this HistoricActivityInstanceQueryRequest.


        :param execution_id: The execution_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._execution_id = execution_id

    @property
    def finished(self):
        """Gets the finished of this HistoricActivityInstanceQueryRequest.  # noqa: E501


        :return: The finished of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :rtype: bool
        """
        return self._finished

    @finished.setter
    def finished(self, finished):
        """Sets the finished of this HistoricActivityInstanceQueryRequest.


        :param finished: The finished of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :type: bool
        """

        self._finished = finished

    @property
    def task_assignee(self):
        """Gets the task_assignee of this HistoricActivityInstanceQueryRequest.  # noqa: E501


        :return: The task_assignee of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_assignee

    @task_assignee.setter
    def task_assignee(self, task_assignee):
        """Sets the task_assignee of this HistoricActivityInstanceQueryRequest.


        :param task_assignee: The task_assignee of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_assignee = task_assignee

    @property
    def process_instance_id(self):
        """Gets the process_instance_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501


        :return: The process_instance_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._process_instance_id

    @process_instance_id.setter
    def process_instance_id(self, process_instance_id):
        """Sets the process_instance_id of this HistoricActivityInstanceQueryRequest.


        :param process_instance_id: The process_instance_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._process_instance_id = process_instance_id

    @property
    def process_definition_id(self):
        """Gets the process_definition_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501


        :return: The process_definition_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._process_definition_id

    @process_definition_id.setter
    def process_definition_id(self, process_definition_id):
        """Sets the process_definition_id of this HistoricActivityInstanceQueryRequest.


        :param process_definition_id: The process_definition_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._process_definition_id = process_definition_id

    @property
    def tenant_id(self):
        """Gets the tenant_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501


        :return: The tenant_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this HistoricActivityInstanceQueryRequest.


        :param tenant_id: The tenant_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._tenant_id = tenant_id

    @property
    def tenant_id_like(self):
        """Gets the tenant_id_like of this HistoricActivityInstanceQueryRequest.  # noqa: E501


        :return: The tenant_id_like of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id_like

    @tenant_id_like.setter
    def tenant_id_like(self, tenant_id_like):
        """Sets the tenant_id_like of this HistoricActivityInstanceQueryRequest.


        :param tenant_id_like: The tenant_id_like of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._tenant_id_like = tenant_id_like

    @property
    def without_tenant_id(self):
        """Gets the without_tenant_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501


        :return: The without_tenant_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :rtype: bool
        """
        return self._without_tenant_id

    @without_tenant_id.setter
    def without_tenant_id(self, without_tenant_id):
        """Sets the without_tenant_id of this HistoricActivityInstanceQueryRequest.


        :param without_tenant_id: The without_tenant_id of this HistoricActivityInstanceQueryRequest.  # noqa: E501
        :type: bool
        """

        self._without_tenant_id = without_tenant_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HistoricActivityInstanceQueryRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HistoricActivityInstanceQueryRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
