# coding: utf-8

"""
    Flowable REST API

    # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class HistoricTaskInstanceQueryRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start': 'int',
        'size': 'int',
        'sort': 'str',
        'order': 'str',
        'task_id': 'str',
        'process_instance_id': 'str',
        'process_instance_id_with_children': 'str',
        'process_business_key': 'str',
        'process_business_key_like': 'str',
        'process_definition_id': 'str',
        'process_definition_key': 'str',
        'process_definition_key_like': 'str',
        'process_definition_name': 'str',
        'process_definition_name_like': 'str',
        'execution_id': 'str',
        'task_name': 'str',
        'task_name_like': 'str',
        'task_description': 'str',
        'task_description_like': 'str',
        'task_definition_key': 'str',
        'task_definition_key_like': 'str',
        'task_category': 'str',
        'task_delete_reason': 'str',
        'task_delete_reason_like': 'str',
        'task_assignee': 'str',
        'task_assignee_like': 'str',
        'task_owner': 'str',
        'task_owner_like': 'str',
        'task_involved_user': 'str',
        'task_priority': 'int',
        'task_min_priority': 'int',
        'task_max_priority': 'int',
        'finished': 'bool',
        'process_finished': 'bool',
        'parent_task_id': 'str',
        'due_date': 'datetime',
        'due_date_after': 'datetime',
        'due_date_before': 'datetime',
        'without_due_date': 'bool',
        'task_created_on': 'datetime',
        'task_created_before': 'datetime',
        'task_created_after': 'datetime',
        'task_completed_on': 'datetime',
        'task_completed_before': 'datetime',
        'task_completed_after': 'datetime',
        'include_task_local_variables': 'bool',
        'include_process_variables': 'bool',
        'task_variables': 'list[QueryVariable]',
        'process_variables': 'list[QueryVariable]',
        'scope_definition_id': 'str',
        'scope_id': 'str',
        'scope_type': 'str',
        'tenant_id': 'str',
        'tenant_id_like': 'str',
        'without_tenant_id': 'bool',
        'task_candidate_group': 'str'
    }

    attribute_map = {
        'start': 'start',
        'size': 'size',
        'sort': 'sort',
        'order': 'order',
        'task_id': 'taskId',
        'process_instance_id': 'processInstanceId',
        'process_instance_id_with_children': 'processInstanceIdWithChildren',
        'process_business_key': 'processBusinessKey',
        'process_business_key_like': 'processBusinessKeyLike',
        'process_definition_id': 'processDefinitionId',
        'process_definition_key': 'processDefinitionKey',
        'process_definition_key_like': 'processDefinitionKeyLike',
        'process_definition_name': 'processDefinitionName',
        'process_definition_name_like': 'processDefinitionNameLike',
        'execution_id': 'executionId',
        'task_name': 'taskName',
        'task_name_like': 'taskNameLike',
        'task_description': 'taskDescription',
        'task_description_like': 'taskDescriptionLike',
        'task_definition_key': 'taskDefinitionKey',
        'task_definition_key_like': 'taskDefinitionKeyLike',
        'task_category': 'taskCategory',
        'task_delete_reason': 'taskDeleteReason',
        'task_delete_reason_like': 'taskDeleteReasonLike',
        'task_assignee': 'taskAssignee',
        'task_assignee_like': 'taskAssigneeLike',
        'task_owner': 'taskOwner',
        'task_owner_like': 'taskOwnerLike',
        'task_involved_user': 'taskInvolvedUser',
        'task_priority': 'taskPriority',
        'task_min_priority': 'taskMinPriority',
        'task_max_priority': 'taskMaxPriority',
        'finished': 'finished',
        'process_finished': 'processFinished',
        'parent_task_id': 'parentTaskId',
        'due_date': 'dueDate',
        'due_date_after': 'dueDateAfter',
        'due_date_before': 'dueDateBefore',
        'without_due_date': 'withoutDueDate',
        'task_created_on': 'taskCreatedOn',
        'task_created_before': 'taskCreatedBefore',
        'task_created_after': 'taskCreatedAfter',
        'task_completed_on': 'taskCompletedOn',
        'task_completed_before': 'taskCompletedBefore',
        'task_completed_after': 'taskCompletedAfter',
        'include_task_local_variables': 'includeTaskLocalVariables',
        'include_process_variables': 'includeProcessVariables',
        'task_variables': 'taskVariables',
        'process_variables': 'processVariables',
        'scope_definition_id': 'scopeDefinitionId',
        'scope_id': 'scopeId',
        'scope_type': 'scopeType',
        'tenant_id': 'tenantId',
        'tenant_id_like': 'tenantIdLike',
        'without_tenant_id': 'withoutTenantId',
        'task_candidate_group': 'taskCandidateGroup'
    }

    def __init__(self, start=None, size=None, sort=None, order=None, task_id=None, process_instance_id=None, process_instance_id_with_children=None, process_business_key=None, process_business_key_like=None, process_definition_id=None, process_definition_key=None, process_definition_key_like=None, process_definition_name=None, process_definition_name_like=None, execution_id=None, task_name=None, task_name_like=None, task_description=None, task_description_like=None, task_definition_key=None, task_definition_key_like=None, task_category=None, task_delete_reason=None, task_delete_reason_like=None, task_assignee=None, task_assignee_like=None, task_owner=None, task_owner_like=None, task_involved_user=None, task_priority=None, task_min_priority=None, task_max_priority=None, finished=None, process_finished=None, parent_task_id=None, due_date=None, due_date_after=None, due_date_before=None, without_due_date=None, task_created_on=None, task_created_before=None, task_created_after=None, task_completed_on=None, task_completed_before=None, task_completed_after=None, include_task_local_variables=None, include_process_variables=None, task_variables=None, process_variables=None, scope_definition_id=None, scope_id=None, scope_type=None, tenant_id=None, tenant_id_like=None, without_tenant_id=None, task_candidate_group=None):  # noqa: E501
        """HistoricTaskInstanceQueryRequest - a model defined in Swagger"""  # noqa: E501

        self._start = None
        self._size = None
        self._sort = None
        self._order = None
        self._task_id = None
        self._process_instance_id = None
        self._process_instance_id_with_children = None
        self._process_business_key = None
        self._process_business_key_like = None
        self._process_definition_id = None
        self._process_definition_key = None
        self._process_definition_key_like = None
        self._process_definition_name = None
        self._process_definition_name_like = None
        self._execution_id = None
        self._task_name = None
        self._task_name_like = None
        self._task_description = None
        self._task_description_like = None
        self._task_definition_key = None
        self._task_definition_key_like = None
        self._task_category = None
        self._task_delete_reason = None
        self._task_delete_reason_like = None
        self._task_assignee = None
        self._task_assignee_like = None
        self._task_owner = None
        self._task_owner_like = None
        self._task_involved_user = None
        self._task_priority = None
        self._task_min_priority = None
        self._task_max_priority = None
        self._finished = None
        self._process_finished = None
        self._parent_task_id = None
        self._due_date = None
        self._due_date_after = None
        self._due_date_before = None
        self._without_due_date = None
        self._task_created_on = None
        self._task_created_before = None
        self._task_created_after = None
        self._task_completed_on = None
        self._task_completed_before = None
        self._task_completed_after = None
        self._include_task_local_variables = None
        self._include_process_variables = None
        self._task_variables = None
        self._process_variables = None
        self._scope_definition_id = None
        self._scope_id = None
        self._scope_type = None
        self._tenant_id = None
        self._tenant_id_like = None
        self._without_tenant_id = None
        self._task_candidate_group = None
        self.discriminator = None

        if start is not None:
            self.start = start
        if size is not None:
            self.size = size
        if sort is not None:
            self.sort = sort
        if order is not None:
            self.order = order
        if task_id is not None:
            self.task_id = task_id
        if process_instance_id is not None:
            self.process_instance_id = process_instance_id
        if process_instance_id_with_children is not None:
            self.process_instance_id_with_children = process_instance_id_with_children
        if process_business_key is not None:
            self.process_business_key = process_business_key
        if process_business_key_like is not None:
            self.process_business_key_like = process_business_key_like
        if process_definition_id is not None:
            self.process_definition_id = process_definition_id
        if process_definition_key is not None:
            self.process_definition_key = process_definition_key
        if process_definition_key_like is not None:
            self.process_definition_key_like = process_definition_key_like
        if process_definition_name is not None:
            self.process_definition_name = process_definition_name
        if process_definition_name_like is not None:
            self.process_definition_name_like = process_definition_name_like
        if execution_id is not None:
            self.execution_id = execution_id
        if task_name is not None:
            self.task_name = task_name
        if task_name_like is not None:
            self.task_name_like = task_name_like
        if task_description is not None:
            self.task_description = task_description
        if task_description_like is not None:
            self.task_description_like = task_description_like
        if task_definition_key is not None:
            self.task_definition_key = task_definition_key
        if task_definition_key_like is not None:
            self.task_definition_key_like = task_definition_key_like
        if task_category is not None:
            self.task_category = task_category
        if task_delete_reason is not None:
            self.task_delete_reason = task_delete_reason
        if task_delete_reason_like is not None:
            self.task_delete_reason_like = task_delete_reason_like
        if task_assignee is not None:
            self.task_assignee = task_assignee
        if task_assignee_like is not None:
            self.task_assignee_like = task_assignee_like
        if task_owner is not None:
            self.task_owner = task_owner
        if task_owner_like is not None:
            self.task_owner_like = task_owner_like
        if task_involved_user is not None:
            self.task_involved_user = task_involved_user
        if task_priority is not None:
            self.task_priority = task_priority
        if task_min_priority is not None:
            self.task_min_priority = task_min_priority
        if task_max_priority is not None:
            self.task_max_priority = task_max_priority
        if finished is not None:
            self.finished = finished
        if process_finished is not None:
            self.process_finished = process_finished
        if parent_task_id is not None:
            self.parent_task_id = parent_task_id
        if due_date is not None:
            self.due_date = due_date
        if due_date_after is not None:
            self.due_date_after = due_date_after
        if due_date_before is not None:
            self.due_date_before = due_date_before
        if without_due_date is not None:
            self.without_due_date = without_due_date
        if task_created_on is not None:
            self.task_created_on = task_created_on
        if task_created_before is not None:
            self.task_created_before = task_created_before
        if task_created_after is not None:
            self.task_created_after = task_created_after
        if task_completed_on is not None:
            self.task_completed_on = task_completed_on
        if task_completed_before is not None:
            self.task_completed_before = task_completed_before
        if task_completed_after is not None:
            self.task_completed_after = task_completed_after
        if include_task_local_variables is not None:
            self.include_task_local_variables = include_task_local_variables
        if include_process_variables is not None:
            self.include_process_variables = include_process_variables
        if task_variables is not None:
            self.task_variables = task_variables
        if process_variables is not None:
            self.process_variables = process_variables
        if scope_definition_id is not None:
            self.scope_definition_id = scope_definition_id
        if scope_id is not None:
            self.scope_id = scope_id
        if scope_type is not None:
            self.scope_type = scope_type
        if tenant_id is not None:
            self.tenant_id = tenant_id
        if tenant_id_like is not None:
            self.tenant_id_like = tenant_id_like
        if without_tenant_id is not None:
            self.without_tenant_id = without_tenant_id
        if task_candidate_group is not None:
            self.task_candidate_group = task_candidate_group

    @property
    def start(self):
        """Gets the start of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The start of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: int
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this HistoricTaskInstanceQueryRequest.


        :param start: The start of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: int
        """

        self._start = start

    @property
    def size(self):
        """Gets the size of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The size of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this HistoricTaskInstanceQueryRequest.


        :param size: The size of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def sort(self):
        """Gets the sort of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The sort of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._sort

    @sort.setter
    def sort(self, sort):
        """Sets the sort of this HistoricTaskInstanceQueryRequest.


        :param sort: The sort of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._sort = sort

    @property
    def order(self):
        """Gets the order of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The order of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this HistoricTaskInstanceQueryRequest.


        :param order: The order of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._order = order

    @property
    def task_id(self):
        """Gets the task_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this HistoricTaskInstanceQueryRequest.


        :param task_id: The task_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_id = task_id

    @property
    def process_instance_id(self):
        """Gets the process_instance_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The process_instance_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._process_instance_id

    @process_instance_id.setter
    def process_instance_id(self, process_instance_id):
        """Sets the process_instance_id of this HistoricTaskInstanceQueryRequest.


        :param process_instance_id: The process_instance_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._process_instance_id = process_instance_id

    @property
    def process_instance_id_with_children(self):
        """Gets the process_instance_id_with_children of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The process_instance_id_with_children of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._process_instance_id_with_children

    @process_instance_id_with_children.setter
    def process_instance_id_with_children(self, process_instance_id_with_children):
        """Sets the process_instance_id_with_children of this HistoricTaskInstanceQueryRequest.


        :param process_instance_id_with_children: The process_instance_id_with_children of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._process_instance_id_with_children = process_instance_id_with_children

    @property
    def process_business_key(self):
        """Gets the process_business_key of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The process_business_key of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._process_business_key

    @process_business_key.setter
    def process_business_key(self, process_business_key):
        """Sets the process_business_key of this HistoricTaskInstanceQueryRequest.


        :param process_business_key: The process_business_key of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._process_business_key = process_business_key

    @property
    def process_business_key_like(self):
        """Gets the process_business_key_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The process_business_key_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._process_business_key_like

    @process_business_key_like.setter
    def process_business_key_like(self, process_business_key_like):
        """Sets the process_business_key_like of this HistoricTaskInstanceQueryRequest.


        :param process_business_key_like: The process_business_key_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._process_business_key_like = process_business_key_like

    @property
    def process_definition_id(self):
        """Gets the process_definition_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The process_definition_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._process_definition_id

    @process_definition_id.setter
    def process_definition_id(self, process_definition_id):
        """Sets the process_definition_id of this HistoricTaskInstanceQueryRequest.


        :param process_definition_id: The process_definition_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._process_definition_id = process_definition_id

    @property
    def process_definition_key(self):
        """Gets the process_definition_key of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The process_definition_key of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._process_definition_key

    @process_definition_key.setter
    def process_definition_key(self, process_definition_key):
        """Sets the process_definition_key of this HistoricTaskInstanceQueryRequest.


        :param process_definition_key: The process_definition_key of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._process_definition_key = process_definition_key

    @property
    def process_definition_key_like(self):
        """Gets the process_definition_key_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The process_definition_key_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._process_definition_key_like

    @process_definition_key_like.setter
    def process_definition_key_like(self, process_definition_key_like):
        """Sets the process_definition_key_like of this HistoricTaskInstanceQueryRequest.


        :param process_definition_key_like: The process_definition_key_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._process_definition_key_like = process_definition_key_like

    @property
    def process_definition_name(self):
        """Gets the process_definition_name of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The process_definition_name of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._process_definition_name

    @process_definition_name.setter
    def process_definition_name(self, process_definition_name):
        """Sets the process_definition_name of this HistoricTaskInstanceQueryRequest.


        :param process_definition_name: The process_definition_name of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._process_definition_name = process_definition_name

    @property
    def process_definition_name_like(self):
        """Gets the process_definition_name_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The process_definition_name_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._process_definition_name_like

    @process_definition_name_like.setter
    def process_definition_name_like(self, process_definition_name_like):
        """Sets the process_definition_name_like of this HistoricTaskInstanceQueryRequest.


        :param process_definition_name_like: The process_definition_name_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._process_definition_name_like = process_definition_name_like

    @property
    def execution_id(self):
        """Gets the execution_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The execution_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._execution_id

    @execution_id.setter
    def execution_id(self, execution_id):
        """Sets the execution_id of this HistoricTaskInstanceQueryRequest.


        :param execution_id: The execution_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._execution_id = execution_id

    @property
    def task_name(self):
        """Gets the task_name of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_name of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_name

    @task_name.setter
    def task_name(self, task_name):
        """Sets the task_name of this HistoricTaskInstanceQueryRequest.


        :param task_name: The task_name of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_name = task_name

    @property
    def task_name_like(self):
        """Gets the task_name_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_name_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_name_like

    @task_name_like.setter
    def task_name_like(self, task_name_like):
        """Sets the task_name_like of this HistoricTaskInstanceQueryRequest.


        :param task_name_like: The task_name_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_name_like = task_name_like

    @property
    def task_description(self):
        """Gets the task_description of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_description of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_description

    @task_description.setter
    def task_description(self, task_description):
        """Sets the task_description of this HistoricTaskInstanceQueryRequest.


        :param task_description: The task_description of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_description = task_description

    @property
    def task_description_like(self):
        """Gets the task_description_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_description_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_description_like

    @task_description_like.setter
    def task_description_like(self, task_description_like):
        """Sets the task_description_like of this HistoricTaskInstanceQueryRequest.


        :param task_description_like: The task_description_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_description_like = task_description_like

    @property
    def task_definition_key(self):
        """Gets the task_definition_key of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_definition_key of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_definition_key

    @task_definition_key.setter
    def task_definition_key(self, task_definition_key):
        """Sets the task_definition_key of this HistoricTaskInstanceQueryRequest.


        :param task_definition_key: The task_definition_key of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_definition_key = task_definition_key

    @property
    def task_definition_key_like(self):
        """Gets the task_definition_key_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_definition_key_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_definition_key_like

    @task_definition_key_like.setter
    def task_definition_key_like(self, task_definition_key_like):
        """Sets the task_definition_key_like of this HistoricTaskInstanceQueryRequest.


        :param task_definition_key_like: The task_definition_key_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_definition_key_like = task_definition_key_like

    @property
    def task_category(self):
        """Gets the task_category of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_category of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_category

    @task_category.setter
    def task_category(self, task_category):
        """Sets the task_category of this HistoricTaskInstanceQueryRequest.


        :param task_category: The task_category of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_category = task_category

    @property
    def task_delete_reason(self):
        """Gets the task_delete_reason of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_delete_reason of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_delete_reason

    @task_delete_reason.setter
    def task_delete_reason(self, task_delete_reason):
        """Sets the task_delete_reason of this HistoricTaskInstanceQueryRequest.


        :param task_delete_reason: The task_delete_reason of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_delete_reason = task_delete_reason

    @property
    def task_delete_reason_like(self):
        """Gets the task_delete_reason_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_delete_reason_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_delete_reason_like

    @task_delete_reason_like.setter
    def task_delete_reason_like(self, task_delete_reason_like):
        """Sets the task_delete_reason_like of this HistoricTaskInstanceQueryRequest.


        :param task_delete_reason_like: The task_delete_reason_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_delete_reason_like = task_delete_reason_like

    @property
    def task_assignee(self):
        """Gets the task_assignee of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_assignee of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_assignee

    @task_assignee.setter
    def task_assignee(self, task_assignee):
        """Sets the task_assignee of this HistoricTaskInstanceQueryRequest.


        :param task_assignee: The task_assignee of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_assignee = task_assignee

    @property
    def task_assignee_like(self):
        """Gets the task_assignee_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_assignee_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_assignee_like

    @task_assignee_like.setter
    def task_assignee_like(self, task_assignee_like):
        """Sets the task_assignee_like of this HistoricTaskInstanceQueryRequest.


        :param task_assignee_like: The task_assignee_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_assignee_like = task_assignee_like

    @property
    def task_owner(self):
        """Gets the task_owner of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_owner of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_owner

    @task_owner.setter
    def task_owner(self, task_owner):
        """Sets the task_owner of this HistoricTaskInstanceQueryRequest.


        :param task_owner: The task_owner of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_owner = task_owner

    @property
    def task_owner_like(self):
        """Gets the task_owner_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_owner_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_owner_like

    @task_owner_like.setter
    def task_owner_like(self, task_owner_like):
        """Sets the task_owner_like of this HistoricTaskInstanceQueryRequest.


        :param task_owner_like: The task_owner_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_owner_like = task_owner_like

    @property
    def task_involved_user(self):
        """Gets the task_involved_user of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_involved_user of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_involved_user

    @task_involved_user.setter
    def task_involved_user(self, task_involved_user):
        """Sets the task_involved_user of this HistoricTaskInstanceQueryRequest.


        :param task_involved_user: The task_involved_user of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_involved_user = task_involved_user

    @property
    def task_priority(self):
        """Gets the task_priority of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_priority of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: int
        """
        return self._task_priority

    @task_priority.setter
    def task_priority(self, task_priority):
        """Sets the task_priority of this HistoricTaskInstanceQueryRequest.


        :param task_priority: The task_priority of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: int
        """

        self._task_priority = task_priority

    @property
    def task_min_priority(self):
        """Gets the task_min_priority of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_min_priority of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: int
        """
        return self._task_min_priority

    @task_min_priority.setter
    def task_min_priority(self, task_min_priority):
        """Sets the task_min_priority of this HistoricTaskInstanceQueryRequest.


        :param task_min_priority: The task_min_priority of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: int
        """

        self._task_min_priority = task_min_priority

    @property
    def task_max_priority(self):
        """Gets the task_max_priority of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_max_priority of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: int
        """
        return self._task_max_priority

    @task_max_priority.setter
    def task_max_priority(self, task_max_priority):
        """Sets the task_max_priority of this HistoricTaskInstanceQueryRequest.


        :param task_max_priority: The task_max_priority of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: int
        """

        self._task_max_priority = task_max_priority

    @property
    def finished(self):
        """Gets the finished of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The finished of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: bool
        """
        return self._finished

    @finished.setter
    def finished(self, finished):
        """Sets the finished of this HistoricTaskInstanceQueryRequest.


        :param finished: The finished of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: bool
        """

        self._finished = finished

    @property
    def process_finished(self):
        """Gets the process_finished of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The process_finished of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: bool
        """
        return self._process_finished

    @process_finished.setter
    def process_finished(self, process_finished):
        """Sets the process_finished of this HistoricTaskInstanceQueryRequest.


        :param process_finished: The process_finished of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: bool
        """

        self._process_finished = process_finished

    @property
    def parent_task_id(self):
        """Gets the parent_task_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The parent_task_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._parent_task_id

    @parent_task_id.setter
    def parent_task_id(self, parent_task_id):
        """Sets the parent_task_id of this HistoricTaskInstanceQueryRequest.


        :param parent_task_id: The parent_task_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._parent_task_id = parent_task_id

    @property
    def due_date(self):
        """Gets the due_date of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The due_date of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._due_date

    @due_date.setter
    def due_date(self, due_date):
        """Sets the due_date of this HistoricTaskInstanceQueryRequest.


        :param due_date: The due_date of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: datetime
        """

        self._due_date = due_date

    @property
    def due_date_after(self):
        """Gets the due_date_after of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The due_date_after of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._due_date_after

    @due_date_after.setter
    def due_date_after(self, due_date_after):
        """Sets the due_date_after of this HistoricTaskInstanceQueryRequest.


        :param due_date_after: The due_date_after of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: datetime
        """

        self._due_date_after = due_date_after

    @property
    def due_date_before(self):
        """Gets the due_date_before of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The due_date_before of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._due_date_before

    @due_date_before.setter
    def due_date_before(self, due_date_before):
        """Sets the due_date_before of this HistoricTaskInstanceQueryRequest.


        :param due_date_before: The due_date_before of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: datetime
        """

        self._due_date_before = due_date_before

    @property
    def without_due_date(self):
        """Gets the without_due_date of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The without_due_date of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: bool
        """
        return self._without_due_date

    @without_due_date.setter
    def without_due_date(self, without_due_date):
        """Sets the without_due_date of this HistoricTaskInstanceQueryRequest.


        :param without_due_date: The without_due_date of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: bool
        """

        self._without_due_date = without_due_date

    @property
    def task_created_on(self):
        """Gets the task_created_on of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_created_on of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._task_created_on

    @task_created_on.setter
    def task_created_on(self, task_created_on):
        """Sets the task_created_on of this HistoricTaskInstanceQueryRequest.


        :param task_created_on: The task_created_on of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: datetime
        """

        self._task_created_on = task_created_on

    @property
    def task_created_before(self):
        """Gets the task_created_before of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_created_before of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._task_created_before

    @task_created_before.setter
    def task_created_before(self, task_created_before):
        """Sets the task_created_before of this HistoricTaskInstanceQueryRequest.


        :param task_created_before: The task_created_before of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: datetime
        """

        self._task_created_before = task_created_before

    @property
    def task_created_after(self):
        """Gets the task_created_after of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_created_after of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._task_created_after

    @task_created_after.setter
    def task_created_after(self, task_created_after):
        """Sets the task_created_after of this HistoricTaskInstanceQueryRequest.


        :param task_created_after: The task_created_after of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: datetime
        """

        self._task_created_after = task_created_after

    @property
    def task_completed_on(self):
        """Gets the task_completed_on of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_completed_on of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._task_completed_on

    @task_completed_on.setter
    def task_completed_on(self, task_completed_on):
        """Sets the task_completed_on of this HistoricTaskInstanceQueryRequest.


        :param task_completed_on: The task_completed_on of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: datetime
        """

        self._task_completed_on = task_completed_on

    @property
    def task_completed_before(self):
        """Gets the task_completed_before of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_completed_before of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._task_completed_before

    @task_completed_before.setter
    def task_completed_before(self, task_completed_before):
        """Sets the task_completed_before of this HistoricTaskInstanceQueryRequest.


        :param task_completed_before: The task_completed_before of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: datetime
        """

        self._task_completed_before = task_completed_before

    @property
    def task_completed_after(self):
        """Gets the task_completed_after of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_completed_after of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._task_completed_after

    @task_completed_after.setter
    def task_completed_after(self, task_completed_after):
        """Sets the task_completed_after of this HistoricTaskInstanceQueryRequest.


        :param task_completed_after: The task_completed_after of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: datetime
        """

        self._task_completed_after = task_completed_after

    @property
    def include_task_local_variables(self):
        """Gets the include_task_local_variables of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The include_task_local_variables of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: bool
        """
        return self._include_task_local_variables

    @include_task_local_variables.setter
    def include_task_local_variables(self, include_task_local_variables):
        """Sets the include_task_local_variables of this HistoricTaskInstanceQueryRequest.


        :param include_task_local_variables: The include_task_local_variables of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: bool
        """

        self._include_task_local_variables = include_task_local_variables

    @property
    def include_process_variables(self):
        """Gets the include_process_variables of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The include_process_variables of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: bool
        """
        return self._include_process_variables

    @include_process_variables.setter
    def include_process_variables(self, include_process_variables):
        """Sets the include_process_variables of this HistoricTaskInstanceQueryRequest.


        :param include_process_variables: The include_process_variables of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: bool
        """

        self._include_process_variables = include_process_variables

    @property
    def task_variables(self):
        """Gets the task_variables of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_variables of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: list[QueryVariable]
        """
        return self._task_variables

    @task_variables.setter
    def task_variables(self, task_variables):
        """Sets the task_variables of this HistoricTaskInstanceQueryRequest.


        :param task_variables: The task_variables of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: list[QueryVariable]
        """

        self._task_variables = task_variables

    @property
    def process_variables(self):
        """Gets the process_variables of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The process_variables of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: list[QueryVariable]
        """
        return self._process_variables

    @process_variables.setter
    def process_variables(self, process_variables):
        """Sets the process_variables of this HistoricTaskInstanceQueryRequest.


        :param process_variables: The process_variables of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: list[QueryVariable]
        """

        self._process_variables = process_variables

    @property
    def scope_definition_id(self):
        """Gets the scope_definition_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The scope_definition_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._scope_definition_id

    @scope_definition_id.setter
    def scope_definition_id(self, scope_definition_id):
        """Sets the scope_definition_id of this HistoricTaskInstanceQueryRequest.


        :param scope_definition_id: The scope_definition_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._scope_definition_id = scope_definition_id

    @property
    def scope_id(self):
        """Gets the scope_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The scope_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._scope_id

    @scope_id.setter
    def scope_id(self, scope_id):
        """Sets the scope_id of this HistoricTaskInstanceQueryRequest.


        :param scope_id: The scope_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._scope_id = scope_id

    @property
    def scope_type(self):
        """Gets the scope_type of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The scope_type of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._scope_type

    @scope_type.setter
    def scope_type(self, scope_type):
        """Sets the scope_type of this HistoricTaskInstanceQueryRequest.


        :param scope_type: The scope_type of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._scope_type = scope_type

    @property
    def tenant_id(self):
        """Gets the tenant_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The tenant_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this HistoricTaskInstanceQueryRequest.


        :param tenant_id: The tenant_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._tenant_id = tenant_id

    @property
    def tenant_id_like(self):
        """Gets the tenant_id_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The tenant_id_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id_like

    @tenant_id_like.setter
    def tenant_id_like(self, tenant_id_like):
        """Sets the tenant_id_like of this HistoricTaskInstanceQueryRequest.


        :param tenant_id_like: The tenant_id_like of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._tenant_id_like = tenant_id_like

    @property
    def without_tenant_id(self):
        """Gets the without_tenant_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The without_tenant_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: bool
        """
        return self._without_tenant_id

    @without_tenant_id.setter
    def without_tenant_id(self, without_tenant_id):
        """Sets the without_tenant_id of this HistoricTaskInstanceQueryRequest.


        :param without_tenant_id: The without_tenant_id of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: bool
        """

        self._without_tenant_id = without_tenant_id

    @property
    def task_candidate_group(self):
        """Gets the task_candidate_group of this HistoricTaskInstanceQueryRequest.  # noqa: E501


        :return: The task_candidate_group of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_candidate_group

    @task_candidate_group.setter
    def task_candidate_group(self, task_candidate_group):
        """Sets the task_candidate_group of this HistoricTaskInstanceQueryRequest.


        :param task_candidate_group: The task_candidate_group of this HistoricTaskInstanceQueryRequest.  # noqa: E501
        :type: str
        """

        self._task_candidate_group = task_candidate_group

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HistoricTaskInstanceQueryRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HistoricTaskInstanceQueryRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
