# coding: utf-8

"""
    Flowable REST API

    # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class HistoricVariableInstanceResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'process_instance_id': 'str',
        'process_instance_url': 'str',
        'task_id': 'str',
        'variable': 'RestVariable'
    }

    attribute_map = {
        'id': 'id',
        'process_instance_id': 'processInstanceId',
        'process_instance_url': 'processInstanceUrl',
        'task_id': 'taskId',
        'variable': 'variable'
    }

    def __init__(self, id=None, process_instance_id=None, process_instance_url=None, task_id=None, variable=None):  # noqa: E501
        """HistoricVariableInstanceResponse - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._process_instance_id = None
        self._process_instance_url = None
        self._task_id = None
        self._variable = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if process_instance_id is not None:
            self.process_instance_id = process_instance_id
        if process_instance_url is not None:
            self.process_instance_url = process_instance_url
        if task_id is not None:
            self.task_id = task_id
        if variable is not None:
            self.variable = variable

    @property
    def id(self):
        """Gets the id of this HistoricVariableInstanceResponse.  # noqa: E501


        :return: The id of this HistoricVariableInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this HistoricVariableInstanceResponse.


        :param id: The id of this HistoricVariableInstanceResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def process_instance_id(self):
        """Gets the process_instance_id of this HistoricVariableInstanceResponse.  # noqa: E501


        :return: The process_instance_id of this HistoricVariableInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_instance_id

    @process_instance_id.setter
    def process_instance_id(self, process_instance_id):
        """Sets the process_instance_id of this HistoricVariableInstanceResponse.


        :param process_instance_id: The process_instance_id of this HistoricVariableInstanceResponse.  # noqa: E501
        :type: str
        """

        self._process_instance_id = process_instance_id

    @property
    def process_instance_url(self):
        """Gets the process_instance_url of this HistoricVariableInstanceResponse.  # noqa: E501


        :return: The process_instance_url of this HistoricVariableInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._process_instance_url

    @process_instance_url.setter
    def process_instance_url(self, process_instance_url):
        """Sets the process_instance_url of this HistoricVariableInstanceResponse.


        :param process_instance_url: The process_instance_url of this HistoricVariableInstanceResponse.  # noqa: E501
        :type: str
        """

        self._process_instance_url = process_instance_url

    @property
    def task_id(self):
        """Gets the task_id of this HistoricVariableInstanceResponse.  # noqa: E501


        :return: The task_id of this HistoricVariableInstanceResponse.  # noqa: E501
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this HistoricVariableInstanceResponse.


        :param task_id: The task_id of this HistoricVariableInstanceResponse.  # noqa: E501
        :type: str
        """

        self._task_id = task_id

    @property
    def variable(self):
        """Gets the variable of this HistoricVariableInstanceResponse.  # noqa: E501


        :return: The variable of this HistoricVariableInstanceResponse.  # noqa: E501
        :rtype: RestVariable
        """
        return self._variable

    @variable.setter
    def variable(self, variable):
        """Sets the variable of this HistoricVariableInstanceResponse.


        :param variable: The variable of this HistoricVariableInstanceResponse.  # noqa: E501
        :type: RestVariable
        """

        self._variable = variable

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HistoricVariableInstanceResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HistoricVariableInstanceResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
