# coding: utf-8

"""
    Flowable REST API

    # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ProcessEngineInfoResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'resource_url': 'str',
        'exception': 'str',
        'version': 'str'
    }

    attribute_map = {
        'name': 'name',
        'resource_url': 'resourceUrl',
        'exception': 'exception',
        'version': 'version'
    }

    def __init__(self, name=None, resource_url=None, exception=None, version=None):  # noqa: E501
        """ProcessEngineInfoResponse - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._resource_url = None
        self._exception = None
        self._version = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if resource_url is not None:
            self.resource_url = resource_url
        if exception is not None:
            self.exception = exception
        if version is not None:
            self.version = version

    @property
    def name(self):
        """Gets the name of this ProcessEngineInfoResponse.  # noqa: E501


        :return: The name of this ProcessEngineInfoResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProcessEngineInfoResponse.


        :param name: The name of this ProcessEngineInfoResponse.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def resource_url(self):
        """Gets the resource_url of this ProcessEngineInfoResponse.  # noqa: E501


        :return: The resource_url of this ProcessEngineInfoResponse.  # noqa: E501
        :rtype: str
        """
        return self._resource_url

    @resource_url.setter
    def resource_url(self, resource_url):
        """Sets the resource_url of this ProcessEngineInfoResponse.


        :param resource_url: The resource_url of this ProcessEngineInfoResponse.  # noqa: E501
        :type: str
        """

        self._resource_url = resource_url

    @property
    def exception(self):
        """Gets the exception of this ProcessEngineInfoResponse.  # noqa: E501


        :return: The exception of this ProcessEngineInfoResponse.  # noqa: E501
        :rtype: str
        """
        return self._exception

    @exception.setter
    def exception(self, exception):
        """Sets the exception of this ProcessEngineInfoResponse.


        :param exception: The exception of this ProcessEngineInfoResponse.  # noqa: E501
        :type: str
        """

        self._exception = exception

    @property
    def version(self):
        """Gets the version of this ProcessEngineInfoResponse.  # noqa: E501


        :return: The version of this ProcessEngineInfoResponse.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ProcessEngineInfoResponse.


        :param version: The version of this ProcessEngineInfoResponse.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProcessEngineInfoResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProcessEngineInfoResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
