# coding: utf-8

"""
    Flowable REST API

    # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class QueryVariable(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'operation': 'str',
        'value': 'object',
        'type': 'str',
        'variable_operation': 'str'
    }

    attribute_map = {
        'name': 'name',
        'operation': 'operation',
        'value': 'value',
        'type': 'type',
        'variable_operation': 'variableOperation'
    }

    def __init__(self, name=None, operation=None, value=None, type=None, variable_operation=None):  # noqa: E501
        """QueryVariable - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._operation = None
        self._value = None
        self._type = None
        self._variable_operation = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if operation is not None:
            self.operation = operation
        if value is not None:
            self.value = value
        if type is not None:
            self.type = type
        if variable_operation is not None:
            self.variable_operation = variable_operation

    @property
    def name(self):
        """Gets the name of this QueryVariable.  # noqa: E501


        :return: The name of this QueryVariable.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this QueryVariable.


        :param name: The name of this QueryVariable.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def operation(self):
        """Gets the operation of this QueryVariable.  # noqa: E501


        :return: The operation of this QueryVariable.  # noqa: E501
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this QueryVariable.


        :param operation: The operation of this QueryVariable.  # noqa: E501
        :type: str
        """

        self._operation = operation

    @property
    def value(self):
        """Gets the value of this QueryVariable.  # noqa: E501


        :return: The value of this QueryVariable.  # noqa: E501
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this QueryVariable.


        :param value: The value of this QueryVariable.  # noqa: E501
        :type: object
        """

        self._value = value

    @property
    def type(self):
        """Gets the type of this QueryVariable.  # noqa: E501


        :return: The type of this QueryVariable.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this QueryVariable.


        :param type: The type of this QueryVariable.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def variable_operation(self):
        """Gets the variable_operation of this QueryVariable.  # noqa: E501


        :return: The variable_operation of this QueryVariable.  # noqa: E501
        :rtype: str
        """
        return self._variable_operation

    @variable_operation.setter
    def variable_operation(self, variable_operation):
        """Sets the variable_operation of this QueryVariable.


        :param variable_operation: The variable_operation of this QueryVariable.  # noqa: E501
        :type: str
        """
        allowed_values = ["EQUALS", "NOT_EQUALS", "EQUALS_IGNORE_CASE", "NOT_EQUALS_IGNORE_CASE", "LIKE", "LIKE_IGNORE_CASE", "GREATER_THAN", "GREATER_THAN_OR_EQUALS", "LESS_THAN", "LESS_THAN_OR_EQUALS"]  # noqa: E501
        if variable_operation not in allowed_values:
            raise ValueError(
                "Invalid value for `variable_operation` ({0}), must be one of {1}"  # noqa: E501
                .format(variable_operation, allowed_values)
            )

        self._variable_operation = variable_operation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QueryVariable, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QueryVariable):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
