# coding: utf-8

"""
    Flowable REST API

    # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RestVariable(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'type': 'str',
        'value': 'object',
        'value_url': 'str',
        'scope': 'str'
    }

    attribute_map = {
        'name': 'name',
        'type': 'type',
        'value': 'value',
        'value_url': 'valueUrl',
        'scope': 'scope'
    }

    def __init__(self, name=None, type=None, value=None, value_url=None, scope=None):  # noqa: E501
        """RestVariable - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._type = None
        self._value = None
        self._value_url = None
        self._scope = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if value is not None:
            self.value = value
        if value_url is not None:
            self.value_url = value_url
        if scope is not None:
            self.scope = scope

    @property
    def name(self):
        """Gets the name of this RestVariable.  # noqa: E501

        Name of the variable  # noqa: E501

        :return: The name of this RestVariable.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RestVariable.

        Name of the variable  # noqa: E501

        :param name: The name of this RestVariable.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this RestVariable.  # noqa: E501

        Type of the variable.  # noqa: E501

        :return: The type of this RestVariable.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RestVariable.

        Type of the variable.  # noqa: E501

        :param type: The type of this RestVariable.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def value(self):
        """Gets the value of this RestVariable.  # noqa: E501

        Value of the variable.  # noqa: E501

        :return: The value of this RestVariable.  # noqa: E501
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this RestVariable.

        Value of the variable.  # noqa: E501

        :param value: The value of this RestVariable.  # noqa: E501
        :type: object
        """

        self._value = value

    @property
    def value_url(self):
        """Gets the value_url of this RestVariable.  # noqa: E501


        :return: The value_url of this RestVariable.  # noqa: E501
        :rtype: str
        """
        return self._value_url

    @value_url.setter
    def value_url(self, value_url):
        """Sets the value_url of this RestVariable.


        :param value_url: The value_url of this RestVariable.  # noqa: E501
        :type: str
        """

        self._value_url = value_url

    @property
    def scope(self):
        """Gets the scope of this RestVariable.  # noqa: E501


        :return: The scope of this RestVariable.  # noqa: E501
        :rtype: str
        """
        return self._scope

    @scope.setter
    def scope(self, scope):
        """Sets the scope of this RestVariable.


        :param scope: The scope of this RestVariable.  # noqa: E501
        :type: str
        """

        self._scope = scope

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RestVariable, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RestVariable):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
