# coding: utf-8

"""
    Flowable REST API

    # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RestFormProperty(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'type': 'str',
        'value': 'str',
        'readable': 'bool',
        'writable': 'bool',
        'required': 'bool',
        'date_pattern': 'str',
        'enum_values': 'list[RestEnumFormProperty]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'type': 'type',
        'value': 'value',
        'readable': 'readable',
        'writable': 'writable',
        'required': 'required',
        'date_pattern': 'datePattern',
        'enum_values': 'enumValues'
    }

    def __init__(self, id=None, name=None, type=None, value=None, readable=None, writable=None, required=None, date_pattern=None, enum_values=None):  # noqa: E501
        """RestFormProperty - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._type = None
        self._value = None
        self._readable = None
        self._writable = None
        self._required = None
        self._date_pattern = None
        self._enum_values = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if value is not None:
            self.value = value
        if readable is not None:
            self.readable = readable
        if writable is not None:
            self.writable = writable
        if required is not None:
            self.required = required
        if date_pattern is not None:
            self.date_pattern = date_pattern
        if enum_values is not None:
            self.enum_values = enum_values

    @property
    def id(self):
        """Gets the id of this RestFormProperty.  # noqa: E501


        :return: The id of this RestFormProperty.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RestFormProperty.


        :param id: The id of this RestFormProperty.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this RestFormProperty.  # noqa: E501


        :return: The name of this RestFormProperty.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RestFormProperty.


        :param name: The name of this RestFormProperty.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this RestFormProperty.  # noqa: E501


        :return: The type of this RestFormProperty.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RestFormProperty.


        :param type: The type of this RestFormProperty.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def value(self):
        """Gets the value of this RestFormProperty.  # noqa: E501


        :return: The value of this RestFormProperty.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this RestFormProperty.


        :param value: The value of this RestFormProperty.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def readable(self):
        """Gets the readable of this RestFormProperty.  # noqa: E501


        :return: The readable of this RestFormProperty.  # noqa: E501
        :rtype: bool
        """
        return self._readable

    @readable.setter
    def readable(self, readable):
        """Sets the readable of this RestFormProperty.


        :param readable: The readable of this RestFormProperty.  # noqa: E501
        :type: bool
        """

        self._readable = readable

    @property
    def writable(self):
        """Gets the writable of this RestFormProperty.  # noqa: E501


        :return: The writable of this RestFormProperty.  # noqa: E501
        :rtype: bool
        """
        return self._writable

    @writable.setter
    def writable(self, writable):
        """Sets the writable of this RestFormProperty.


        :param writable: The writable of this RestFormProperty.  # noqa: E501
        :type: bool
        """

        self._writable = writable

    @property
    def required(self):
        """Gets the required of this RestFormProperty.  # noqa: E501


        :return: The required of this RestFormProperty.  # noqa: E501
        :rtype: bool
        """
        return self._required

    @required.setter
    def required(self, required):
        """Sets the required of this RestFormProperty.


        :param required: The required of this RestFormProperty.  # noqa: E501
        :type: bool
        """

        self._required = required

    @property
    def date_pattern(self):
        """Gets the date_pattern of this RestFormProperty.  # noqa: E501


        :return: The date_pattern of this RestFormProperty.  # noqa: E501
        :rtype: str
        """
        return self._date_pattern

    @date_pattern.setter
    def date_pattern(self, date_pattern):
        """Sets the date_pattern of this RestFormProperty.


        :param date_pattern: The date_pattern of this RestFormProperty.  # noqa: E501
        :type: str
        """

        self._date_pattern = date_pattern

    @property
    def enum_values(self):
        """Gets the enum_values of this RestFormProperty.  # noqa: E501


        :return: The enum_values of this RestFormProperty.  # noqa: E501
        :rtype: list[RestEnumFormProperty]
        """
        return self._enum_values

    @enum_values.setter
    def enum_values(self, enum_values):
        """Sets the enum_values of this RestFormProperty.


        :param enum_values: The enum_values of this RestFormProperty.  # noqa: E501
        :type: list[RestEnumFormProperty]
        """

        self._enum_values = enum_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RestFormProperty, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RestFormProperty):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
