# coding: utf-8

"""
    Flowable REST API

    # flowable / flowəb(ə)l /    - a compact and highly efficient workflow and Business Process Management (BPM) platform for developers, system admins and business users.  - a lightning fast, tried and tested BPMN 2 process engine written in Java. It is Apache 2.0 licensed open source, with a committed community.  - can run embedded in a Java application, or as a service on a server, a cluster, and in the cloud. It integrates perfectly with Spring. With a rich Java and REST API, it is the ideal engine for orchestrating human or system activities.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SignalEventReceivedRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'signal_name': 'str',
        'variables': 'list[RestVariable]',
        'tenant_id': 'str',
        '_async': 'bool'
    }

    attribute_map = {
        'signal_name': 'signalName',
        'variables': 'variables',
        'tenant_id': 'tenantId',
        '_async': 'async'
    }

    def __init__(self, signal_name=None, variables=None, tenant_id=None, _async=None):  # noqa: E501
        """SignalEventReceivedRequest - a model defined in Swagger"""  # noqa: E501

        self._signal_name = None
        self._variables = None
        self._tenant_id = None
        self.__async = None
        self.discriminator = None

        if signal_name is not None:
            self.signal_name = signal_name
        if variables is not None:
            self.variables = variables
        if tenant_id is not None:
            self.tenant_id = tenant_id
        if _async is not None:
            self._async = _async

    @property
    def signal_name(self):
        """Gets the signal_name of this SignalEventReceivedRequest.  # noqa: E501

        Name of the signal  # noqa: E501

        :return: The signal_name of this SignalEventReceivedRequest.  # noqa: E501
        :rtype: str
        """
        return self._signal_name

    @signal_name.setter
    def signal_name(self, signal_name):
        """Sets the signal_name of this SignalEventReceivedRequest.

        Name of the signal  # noqa: E501

        :param signal_name: The signal_name of this SignalEventReceivedRequest.  # noqa: E501
        :type: str
        """

        self._signal_name = signal_name

    @property
    def variables(self):
        """Gets the variables of this SignalEventReceivedRequest.  # noqa: E501

        Array of variables (in the general variables format) to use as payload to pass along with the signal. Cannot be used in case async is set to true, this will result in an error.  # noqa: E501

        :return: The variables of this SignalEventReceivedRequest.  # noqa: E501
        :rtype: list[RestVariable]
        """
        return self._variables

    @variables.setter
    def variables(self, variables):
        """Sets the variables of this SignalEventReceivedRequest.

        Array of variables (in the general variables format) to use as payload to pass along with the signal. Cannot be used in case async is set to true, this will result in an error.  # noqa: E501

        :param variables: The variables of this SignalEventReceivedRequest.  # noqa: E501
        :type: list[RestVariable]
        """

        self._variables = variables

    @property
    def tenant_id(self):
        """Gets the tenant_id of this SignalEventReceivedRequest.  # noqa: E501

        ID of the tenant that the signal event should be processed in  # noqa: E501

        :return: The tenant_id of this SignalEventReceivedRequest.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this SignalEventReceivedRequest.

        ID of the tenant that the signal event should be processed in  # noqa: E501

        :param tenant_id: The tenant_id of this SignalEventReceivedRequest.  # noqa: E501
        :type: str
        """

        self._tenant_id = tenant_id

    @property
    def _async(self):
        """Gets the _async of this SignalEventReceivedRequest.  # noqa: E501

        If true, handling of the signal will happen asynchronously. Return code will be 202 - Accepted to indicate the request is accepted but not yet executed. If false,                     handling the signal will be done immediately and result (200 - OK) will only return after this completed successfully. Defaults to false if omitted.  # noqa: E501

        :return: The _async of this SignalEventReceivedRequest.  # noqa: E501
        :rtype: bool
        """
        return self.__async

    @_async.setter
    def _async(self, _async):
        """Sets the _async of this SignalEventReceivedRequest.

        If true, handling of the signal will happen asynchronously. Return code will be 202 - Accepted to indicate the request is accepted but not yet executed. If false,                     handling the signal will be done immediately and result (200 - OK) will only return after this completed successfully. Defaults to false if omitted.  # noqa: E501

        :param _async: The _async of this SignalEventReceivedRequest.  # noqa: E501
        :type: bool
        """

        self.__async = _async

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SignalEventReceivedRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SignalEventReceivedRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
