organisations_errors = {
    24001:["Failed to get Organisation data."],
    24002:["Failed to get Organisation data.", " Exception: {} "],
    24003:["Failed to onboard your Organisation.", " Error: {} "],
    24004:["Failed to onboard your Organisation.", " Exception: {} "],
    24005:["ID not found.", " Failed to retrieve Organisation details, Error: {} "],
    24006:["Failed to retrieve Organisation details.", " Exception: {} "],
    24007:["ID not found.", " Failed to partial update Organisation details, Error: {} "],
    24008:["Failed to update your Organisation details.", " Exception: {} "],
    24009:["Failed to update Organisation details.", " Exception: {} "],
    24010:["ID not found.", " Failed to retrieve logo for id : {}, due to: {} "],
    24011:["Failed to retrieve logo.", "id: {}, Exception: {} "],
    24012:["Failed to get organisation license data."],
    24013:["Failed to get organisation license data", " Exception: {} "],
    24014:["ID not found.", "Failed to update Organisation details, Error: {} "],
    24015:["Failed to update organisation license details. "],
    24016:["Failed to update organisation license details.", " Exception: {} "],
    24017:["Failed to retrieve Organisation details.", " Exception: {} "],
    24018:["Scheduled Report not found.", " User: {}, Error: {} "],
    24019:["Failed to get scheduler.", " Exception: {} "],
    24020:["ID not found.", " {} Failed to delete scheduler , Error: {} "],
    24021:["Failed to delete scheduler.", " User: {}, Exception: {} "],
    24022:["Scheduled Report not found.", " {}, Failed to update Scheduled Report, Error: {} "],
    24023:["Failed to update Scheduler.", " User:{}, Exception: {} "],
    24024:["Failed to update Scheduler.", " User: {}, Exception: {} "],
    24025:["Failed to add scheduler."],
    24026:["Failed to add scheduler.", " Exception: {} "],
    24027:["Failed to get BGV mapping data.", "Exception: {}"]

}
