# Generated by Django 3.1.4 on 2022-07-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshortner',
            name='tenant',
        ),
    ]
