# Generated by Django 3.1.4 on 2022-06-27 12:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+[,0-9a-zA-Z_\\-\\s]*[0-9a-zA-Z]$', 'Special Characters are not allowed except Comma, Underscore, Hyphen and the name can not start and end with any special character or space.')])),
                ('slug', models.SlugField(blank=True, null=True)),
                ('extra_fields', models.JSONField(blank=True, default=dict, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='LocationDetail',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='org_location.location')),
            ],
            options={
                'verbose_name': 'Location Detail',
                'verbose_name_plural': 'Location Details',
            },
        ),
    ]
