# Generated by Django 3.1.4 on 2022-06-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_users', '0001_initial'),
        ('org_location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdetail',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_users.organisationuser'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'tenant'), ('slug', 'tenant')},
        ),
    ]
