# Generated by Django 3.1.4 on 2022-07-21 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_location', '0002_auto_20220627_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+[,0-9a-zA-Z_\\-\\s]*[0-9a-zA-Z]$', 'Special Characters are not allowed except Comma, Underscore, Hyphen and the name can not start and end with any special character or space.')]),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, choices=[('India', 'India')], max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Chandigarh', 'Chandigarh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry'), ('Delhi', 'Delhi'), ('Ladakh', 'Ladakh'), ('Jammu and Kashmir', 'Jammu and Kashmir')], max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, choices=[('Both', 'Both'), ('Interview Location', 'Interview Location'), ('Job Location', 'Job Location')], max_length=50),
        ),
        migrations.DeleteModel(
            name='LocationDetail',
        ),
    ]
