# Generated by Django 3.1.4 on 2022-08-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_location', '0003_auto_20220721_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, choices=[('Both', 'Both'), ('Interview Location', 'Interview Location'), ('Work Location', 'Work Location')], max_length=50),
        ),
    ]
