# Generated by Django 3.1.4 on 2022-09-23 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org_location', '0004_auto_20220804_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='platform_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
