# Generated by Django 3.1.4 on 2023-01-04 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org_location', '0005_update_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='platform_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
