# Generated by Django 3.1.4 on 2023-01-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_location', '0006_auto_20230104_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='locality',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
