apiVersion: v1
data:
  AZURE_ACCOUNT_KEY: RWdOdTdpWEVjaFNqNXc4MHhHb2kxMXVOVytGUlJLNkJEbHFHR2U0R01OUk5ydmpMTkwyWUVCVnhFdTRwVit6aWxEYkd1SmpxZkFDQStBU3ROQlRKZkE9PQ==
  BROKER_URL: YW1xcDovL21vbml0b3I6bW9uaXRvciU0MDEyM0AxMC4xNzMuMTczLjU6NTY3Mi8=
  CELERY_BROKER_URL: YW1xcDovL21vbml0b3I6bW9uaXRvciU0MDEyM0AxMC4xNzMuMTczLjU6NTY3Mi8=
  YW1xcDovL21vbml0b3I6bW9uaXRvciU0MDEyM0AxMC4xNzMuMTczLjU6NTY3Mi87YW1xcDovL21vbml0b3I6bW9uaXRvciU0MDEyM0AxMC4xNzMuMTczLjY6NTY3Mi8=
  CELERY_RESULT_BACKEND: cmVkaXM6Ly86UEtEU3pDbW9WOXVaWUtnNGhCeWZ2SzVzbFBtRjdtMHJHVnNGazRWZEpQRW1lNWQyTktrWWNNQnVCVHdsMkpLQDEwLjE3My4xNzMuMTk6OTk5OS8x
  CHANNEL_LAYER_URL: cmVkaXM6Ly86UEtEU3pDbW9WOXVaWUtnNGhCeWZ2SzVzbFBtRjdtMHJHVnNGazRWZEpQRW1lNWQyTktrWWNNQnVCVHdsMkpLQDEwLjE3My4xNzMuMTk6OTk5OS8w
  DJANGO_SECRET_KEY: NWt4NUs4TzBIeVFlcHNkc2RlbzQzMDQwMy0zNC0wMzQwLTA=
  ENCRYPTION_KEY: MzAzNDhkZjQ1MGEwLTNmNmQtNDlkZGZmZzQ1NDViLThhYjAtOGMyYWUyZDkyYWUw
  EZEDOX_ADMIN_PASSWORD: MTIzNDU2Nzg=
  INTEGRATION_INTERNAL_TOKEN: ZmJTbmNvem9CTU5aU3RfbWZUeGxFSjd2Mkd3cWFyMmRELTFFNHRnS2pUaz0=
  PLATFORM_INTERNAL_TOKEN: ZmJTbmNvem9CTU5aU3RfbWZUeGxFSjd2Mkd3cWFyMmRELTFFNHRnS2pUaz0=
  POSTGRES_PASSWORD: Q3dtU3NpdGFBZG0xbg==
  PROCESS_ENGINE_PASSWORD: Vlp4SlprUCE4a0Ih
  RABBITMQ_HTTP_USER_PASSWORD: bW9uaXRvckAxMjM=
  REDIS_CACHE_URL: cmVkaXM6Ly86UEtEU3pDbW9WOXVaWUtnNGhCeWZ2SzVzbFBtRjdtMHJHVnNGazRWZEpQRW1lNWQyTktrWWNNQnVCVHdsMkpLQDEwLjE3My4xNzMuMTk6OTk5OS8z
  SALT_FOR_PASSWORD: cDh0Z2dRT2FCcFFGTDR4YWtzZDM0SHhxUzdYVDQ=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"AZURE_ACCOUNT_KEY":"RWdOdTdpWEVjaFNqNXc4MHhHb2kxMXVOVytGUlJLNkJEbHFHR2U0R01OUk5ydmpMTkwyWUVCVnhFdTRwVit6aWxEYkd1SmpxZkFDQStBU3ROQlRKZkE9PQ==","BROKER_URL":"YW1xcDovL21vbml0b3I6bW9uaXRvciU0MDEyM0AxMC4xNzMuMTczLjU6NTY3Mi8=","CELERY_BROKER_URL":"YW1xcDovL21vbml0b3I6bW9uaXRvciU0MDEyM0AxMC4xNzMuMTczLjU6NTY3Mi8=","CELERY_RESULT_BACKEND":"cmVkaXM6Ly86UEtEU3pDbW9WOXVaWUtnNGhCeWZ2SzVzbFBtRjdtMHJHVnNGazRWZEpQRW1lNWQyTktrWWNNQnVCVHdsMkpLQDEwLjE3My4xNzMuMTk6OTk5OS8x","CHANNEL_LAYER_URL":"cmVkaXM6Ly86UEtEU3pDbW9WOXVaWUtnNGhCeWZ2SzVzbFBtRjdtMHJHVnNGazRWZEpQRW1lNWQyTktrWWNNQnVCVHdsMkpLQDEwLjE3My4xNzMuMTk6OTk5OS8w","DJANGO_SECRET_KEY":"NWt4NUs4TzBIeVFlcHNkc2RlbzQzMDQwMy0zNC0wMzQwLTA=","ENCRYPTION_KEY":"MzAzNDhkZjQ1MGEwLTNmNmQtNDlkZGZmZzQ1NDViLThhYjAtOGMyYWUyZDkyYWUw","EZEDOX_ADMIN_PASSWORD":"MTIzNDU2Nzg=","INTEGRATION_INTERNAL_TOKEN":"ZmJTbmNvem9CTU5aU3RfbWZUeGxFSjd2Mkd3cWFyMmRELTFFNHRnS2pUaz0=","PLATFORM_INTERNAL_TOKEN":"ZmJTbmNvem9CTU5aU3RfbWZUeGxFSjd2Mkd3cWFyMmRELTFFNHRnS2pUaz0=","POSTGRES_PASSWORD":"Q3dtU3NpdGFBZG0xbg==","PROCESS_ENGINE_PASSWORD":"Vlp4SlprUCE4a0Ih","RABBITMQ_HTTP_USER_PASSWORD":"bW9uaXRvckAxMjM=","REDIS_CACHE_URL":"cmVkaXM6Ly86UEtEU3pDbW9WOXVaWUtnNGhCeWZ2SzVzbFBtRjdtMHJHVnNGazRWZEpQRW1lNWQyTktrWWNNQnVCVHdsMkpLQDEwLjE3My4xNzMuMTk6OTk5OS8z","SALT_FOR_PASSWORD":"cDh0Z2dRT2FCcFFGTDR4YWtzZDM0SHhxUzdYVDQ="},"kind":"Secret","metadata":{"annotations":{},"name":"cw-sit-secret","namespace":"cw"}}
  creationTimestamp: "2024-08-27T10:34:06Z"
  name: cw-sit-secret
  namespace: cw
  resourceVersion: "161108973"
  uid: fb477d66-342d-41eb-8e5b-8f732a4010a2
type: Opaque