# Generated by Django 3.1.4 on 2022-06-27 12:44

import apps.org_apps.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order_id', models.IntegerField(default=1)),
                ('app_key', models.CharField(max_length=100, unique=True)),
                ('is_open', models.BooleanField(default=False)),
                ('is_process_initiable_from_app_context', models.BooleanField(default=False)),
                ('is_admin_initiable', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(default='This is an organisation workflow.')),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True)),
                ('process_key', models.CharField(max_length=100, unique=True)),
                ('selected_form_fields', models.JSONField(blank=True, default=dict, null=True)),
                ('selected_forms', models.JSONField(blank=True, default=dict, null=True)),
                ('bulk_sample_url', models.FileField(blank=True, max_length=256, null=True, upload_to=apps.org_apps.models.generate_path)),
                ('is_global', models.BooleanField(default=True)),
                ('bulk_support', models.BooleanField(default=False)),
                ('process_state_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None)),
                ('process_search_list', models.JSONField(blank=True, default=apps.org_apps.models.config_default_value, null=True)),
                ('enabled_for_entities_by_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('All', 'All')], default='Active', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Organisation Workflow',
                'verbose_name_plural': 'Organisation Workflows',
            },
        ),
        migrations.CreateModel(
            name='ProcessView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('selected_form_fields', models.JSONField(blank=True, default=list, null=True)),
                ('selected_forms', models.JSONField(blank=True, default=list, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_view', to='org_apps.organisationworkflow')),
                ('role', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
            options={
                'verbose_name': 'Process View',
                'verbose_name_plural': 'Process Views',
            },
        ),
    ]
