# Generated by Django 3.1.4 on 2022-06-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_apps', '0001_initial'),
        ('organisations', '0001_initial'),
        ('org_form', '0001_initial'),
        ('org_portals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationworkflow',
            name='forms',
            field=models.ManyToManyField(blank=True, to='org_form.OrganisationForm'),
        ),
        migrations.AddField(
            model_name='organisationworkflow',
            name='open_forms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='open_forms', to='org_form.organisationform'),
        ),
        migrations.AddField(
            model_name='organisationworkflow',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org_portals.portals'),
        ),
        migrations.AddField(
            model_name='organisationworkflow',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='processview',
            unique_together={('app', 'role')},
        ),
    ]
