# Generated by Django 3.1.4 on 2022-07-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('org_apps', '0002_auto_20220627_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationworkflow',
            name='app_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organisationworkflow',
            name='process_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='organisationworkflow',
            unique_together={('app_key', 'process_key', 'tenant')},
        ),
    ]
