# Generated by Django 3.1.4 on 2022-08-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0003_auto_20220719_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationworkflow',
            name='workflow_type',
            field=models.CharField(blank=True, choices=[('JOB', 'JOB'), ('JOB_CONTEXT', 'JOB_CONTEXT'), ('JOB_CANDIDATE', 'JOB_CANDIDATE'), ('JOB_CANDIDATE_CONTEXT', 'JOB_CANDIDATE_CONTEXT'), ('SLOT', 'SLOT'), ('SLOT_CONTEXT', 'SLOT_CONTEXT')], max_length=100, null=True),
        ),
    ]
