# Generated by Django 3.1.4 on 2022-08-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0010_auto_20220803_0935'),
        ('org_apps', '0004_organisationworkflow_workflow_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationworkflow',
            name='available_from_status',
            field=models.ManyToManyField(blank=True, to='org_jobs.HiringState'),
        ),
    ]
