# Generated by Django 3.1.4 on 2023-01-20 02:54

import apps.org_apps.models
from django.db import migrations, models
import ezedox.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0005_organisationworkflow_available_from_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationworkflow',
            name='bulk_sample_url',
            field=models.FileField(blank=True, max_length=256, null=True, storage=ezedox.custom_storage.OtherFileStorage(), upload_to=apps.org_apps.models.generate_path),
        ),
    ]
