# Generated by Django 3.1.4 on 2023-02-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0006_auto_20230120_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationworkflow',
            name='workflow_type',
            field=models.CharField(blank=True, choices=[('JOB', 'JOB'), ('JOB_CONTEXT', 'JOB_CONTEXT'), ('JOB_CANDIDATE', 'JOB_CANDIDATE'), ('JOB_CANDIDATE_CONTEXT', 'JOB_CANDIDATE_CONTEXT'), ('SLOT', 'SLOT'), ('SLOT_CONTEXT', 'SLOT_CONTEXT'), ('CANDIDATE', 'CANDIDATE')], max_length=100, null=True),
        ),
    ]
