# Generated by Django 3.1.4 on 2023-02-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0007_auto_20230214_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationworkflow',
            name='workflow_type',
            field=models.CharField(blank=True, choices=[('JOB', 'JOB'), ('JOB_CONTEXT', 'JOB_CONTEXT'), ('JOB_CANDIDATE', 'JOB_CANDIDATE'), ('JOB_CANDIDATE_CONTEXT', 'JOB_CANDIDATE_CONTEXT'), ('SLOT', 'SLOT'), ('SLOT_CONTEXT', 'SLOT_CONTEXT'), ('CANDIDATE', 'CANDIDATE'), ('CANDIDATE_CONTEXT', 'CANDIDATE_CONTEXT')], max_length=100, null=True),
        ),
    ]
