# Generated by Django 3.1.4 on 2023-06-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0008_auto_20230215_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationworkflow',
            name='kafka_topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
