# Generated by Django 3.1.4 on 2023-07-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0009_organisationworkflow_kafka_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationworkflow',
            name='table_view_columns',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
