# Generated by Django 3.1.4 on 2023-07-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0010_organisationworkflow_table_view_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationworkflow',
            name='filters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
