# Generated by Django 3.1.4 on 2024-01-16 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    
    dependencies = [
        ('org_apps', '0011_organisationworkflow_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_apps.organisationworkflow')),
            ],
            options={
                'verbose_name': 'Workflow Access',
                'verbose_name_plural': 'Workflow Access',
            },
        ),
    ]
