# Generated by Django 3.1.4 on 2024-01-16 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0012_workflowaccess'),
        ('org_users', '0006_auto_20240116_1252'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='workflowaccess',
            name='policy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='org_users.platformpolicy'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowaccess',
            unique_together={('app', 'policy')},
        ),
    ]
