# Generated by Django 3.1.4 on 2024-01-31 07:00
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('org_apps', '0013_auto_20240116_1252'),
    ]
    operations = [
        migrations.AddField(
            model_name='organisationworkflow',
            name='task_view_column',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
