# Generated by Django 3.1.4 on 2024-01-31 07:04
from django.db import migrations
class Migration(migrations.Migration):
    dependencies = [
        ('org_apps', '0014_organisationworkflow_task_view_column'),
    ]
    operations = [
        migrations.RenameField(
            model_name='organisationworkflow',
            old_name='table_view_columns',
            new_name='process_view_column',
        ),
    ]
