# Generated by Django 3.1.4 on 2024-02-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0015_auto_20240131_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowaccess',
            name='bulk_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowaccess',
            name='filter_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowaccess',
            name='initiate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowaccess',
            name='reassign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowaccess',
            name='upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowaccess',
            name='view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowaccess',
            name='withdraw',
            field=models.BooleanField(default=False),
        ),
    ]
