# Generated by Django 3.1.4 on 2024-03-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0016_auto_20240228_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowaccess',
            old_name='bulk_email',
            new_name='bulk_initiate',
        ),
        migrations.RemoveField(
            model_name='workflowaccess',
            name='filter_files',
        ),
    ]
