# Generated by Django 3.1.4 on 2024-03-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0017_auto_20240306_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowaccess',
            name='filter_on_task',
            field=models.BooleanField(default=False),
        ),
    ]
