# Generated by Django 3.1.4 on 2024-05-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0019_organisationworkflow_custom_default_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationworkflow',
            name='process_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
