# Generated by Django 3.1.4 on 2024-06-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0020_organisationworkflow_process_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationworkflow',
            name='available_from_status',
        ),
        migrations.RemoveField(
            model_name='organisationworkflow',
            name='workflow_type',
        ),
        migrations.AddField(
            model_name='organisationworkflow',
            name='kafka_domain_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organisationworkflow',
            name='kafka_topic_action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
