# Generated by Django 3.1.4 on 2024-12-24 11:17

import apps.org_apps.models
from django.db import migrations, models
import ezedox.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0021_auto_20240618_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationworkflow',
            name='bulk_sample_url',
            field=apps.org_apps.models.DynamicStorageFileField(blank=True, max_length=256, null=True, upload_to=apps.org_apps.models.generate_path),
        ),
    ]
