# Generated by Django 3.1.4 on 2025-07-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0022_auto_20241224_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationworkflow',
            name='app_key',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
