# Generated by Django 3.1.4 on 2025-08-28 05:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0023_auto_20250729_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessVarSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('kafka_topic', models.CharField(blank=True, max_length=100, null=True)),
                ('kafka_domain_name', models.CharField(blank=True, max_length=100, null=True)),
                ('kafka_topic_action', models.CharField(blank=True, max_length=100, null=True)),
                ('mapping', models.JSONField(blank=True, default=dict, null=True)),
                ('source', models.CharField(default='KAFKA_DATA', max_length=100)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_apps.organisationworkflow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]