# Generated by Django 3.1.4 on 2025-09-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_apps', '0024_processvarsync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationworkflow',
            name='enabled_for_entities_by_status',
        ),
        migrations.AddField(
            model_name='organisationworkflow',
            name='entity',
            field=models.CharField(blank=True, choices=[('Employee', 'Employee'), ('User', 'User'), ('Vendor', 'Vendor'), ('Tag', 'Tag')], default='Employee', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processvarsync',
            name='entity',
            field=models.CharField(blank=True, choices=[('Employee', 'Employee'), ('User', 'User'), ('Vendor', 'Vendor'), ('Tag', 'Tag')], default='Active', max_length=100, null=True),
        ),
    ]