# Generated by Django 3.1.4 on 2025-09-04 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_organisationlicense_processengine_read_replica'),
        ('org_apps', '0025_auto_20250904_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='processvarsync',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='processvarsync',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org_apps.organisationworkflow'),
        ),
    ]