apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: #{name}#
  name: #{name}#
  namespace: #{namespace}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #{name}#
  template:
    metadata:
        # annotations:
        # prometheus.io.path: /deviceSales/actuator/prometheus
        # prometheus.io.port: "8082"
        # prometheus.io.probe: "true"
        # prometheus.io.scrape: "true"
      labels:
        app: #{name}#
    spec:
      securityContext:
        privileged: true
      containers:
        - image: devopsartifact.jio.com/juni-data_orchestration__dev__dcr/data_orchestration_service/#{release_name}#:#{Build.BuildId}#
          name: #{name}#
          imagePullPolicy: Always
          #    resources:
          #  limits:
          #    memory: "768Mi"
      # nodeName: jmngd1s05siv041
      #restartPolicy: Always
      imagePullSecrets:
      - name: dosbsecret-jfrog

---

apiVersion: v1
kind: Service
metadata:
  name: #{name}#
  namespace: #{namespace}#
  labels:
    app: #{name}#
    spring-boot: "true"
spec:
  type: NodePort
  ports:
    - port: #{CPORT}#
      targetPort: #{CPORT}#
      protocol: TCP
      name: http
      nodePort: #{SITNPORT}#
  selector:
    app: #{name}#