# Generated by Django 3.1.4 on 2022-06-27 12:44

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_apps', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('charts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('HiringStatus', 'HiringStatus'), ('Source', 'Source'), ('OpenPosition', 'OpenPosition'), ('SourcingChannelEfficiency', 'SourcingChannelEfficiency'), ('TimeToHire', 'TimeToHire')], max_length=100), blank=True, default=list, null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('custom_attribute', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Custom Attribute',
                'verbose_name_plural': 'Custom Attributes',
            },
        ),
        migrations.CreateModel(
            name='DashboardView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('grid_data', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name': 'DashboardView',
                'verbose_name_plural': 'DashboardViews',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=250)),
                ('key', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('html', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
            },
        ),
        migrations.CreateModel(
            name='EmailDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('to', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True), blank=True, null=True, size=None)),
                ('msg', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_service_active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Identity',
                'verbose_name_plural': 'Email Identities',
            },
        ),
        migrations.CreateModel(
            name='EventConfigView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('grid_data', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name': 'EventConfigView',
                'verbose_name_plural': 'EventConfigViews',
            },
        ),
        migrations.CreateModel(
            name='JobConfigView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('grid_data', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name': 'JobConfigView',
                'verbose_name_plural': 'JobConfigViews',
            },
        ),
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_service_active', models.BooleanField(default=True)),
                ('host', models.CharField(max_length=250)),
                ('port', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('encryption', models.IntegerField(choices=[(1, 'TLS'), (2, 'SSL')], default=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'SMTP Setting',
                'verbose_name_plural': 'SMTP Settings',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('query', models.JSONField(default=dict)),
                ('user_filter', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True), blank=True, null=True, size=None)),
                ('is_involved', models.BooleanField(default=False)),
                ('process_type', models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('WITHDRAWN', 'WITHDRAWN')], max_length=256, null=True)),
                ('selected_fields', models.JSONField(default=dict)),
                ('prompt_variable', models.BooleanField(default=False)),
                ('report_type', models.IntegerField(choices=[(1, 'DAILY'), (2, 'WEEKLY'), (3, 'MONTHLY'), (4, 'CUSTOM')], default=4)),
                ('send_via_email', models.BooleanField(default=True)),
                ('report_on', models.CharField(choices=[('PROCESS', 'PROCESS'), ('ENTITY', 'ENTITY')], default='PROCESS', max_length=256)),
                ('apps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org_apps.organisationworkflow')),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'permissions': (('download_reporttemplate', 'Can download reports of all workflows'),),
            },
        ),
    ]
