# Generated by Django 3.1.4 on 2022-06-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_entity', '0001_initial'),
        ('org_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='entity_master_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org_entity.organisationentitymastermodel'),
        ),
    ]
