# Generated by Django 3.1.4 on 2022-06-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_users', '0001_initial'),
        ('organisations', '0001_initial'),
        ('org_config', '0002_reporttemplate_entity_master_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='roles',
            field=models.ManyToManyField(blank=True, to='org_users.Role'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='jobconfigview',
            name='role',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='org_users.role'),
        ),
        migrations.AddField(
            model_name='jobconfigview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='eventconfigview',
            name='role',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='org_users.role'),
        ),
        migrations.AddField(
            model_name='eventconfigview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='emailidentity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='emaildigest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='dashboardview',
            name='role',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='org_users.role'),
        ),
        migrations.AddField(
            model_name='dashboardview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='customattribute',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='chartname',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='jobconfigview',
            unique_together={('name', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='eventconfigview',
            unique_together={('name', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='dashboardview',
            unique_together={('name', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='customattribute',
            unique_together={('type', 'tenant')},
        ),
    ]
