# Generated by Django 3.1.4 on 2022-07-06 17:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0004_auto_20220706_1250'),
        ('organisations', '0001_initial'),
        ('org_config', '0003_auto_20220627_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('dlt_sender_id', models.CharField(max_length=250)),
                ('template_name', models.CharField(max_length=250)),
                ('dlt_id', models.CharField(max_length=250)),
                ('template', models.CharField(max_length=500)),
                ('allowed_from_status', models.ManyToManyField(blank=True, default=None, related_name='allowed_from_status', to='org_jobs.HiringState')),
                ('default_status', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_jobs.hiringstate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
