# Generated by Django 3.1.4 on 2022-07-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_config', '0004_smstemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='template',
            field=models.TextField(),
        ),
    ]
