# Generated by Django 3.1.4 on 2022-07-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_config', '0005_auto_20220706_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardview',
            name='role',
        ),
        migrations.RemoveField(
            model_name='eventconfigview',
            name='role',
        ),
        migrations.RemoveField(
            model_name='jobconfigview',
            name='role',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='roles',
        ),
    ]
