# Generated by Django 3.1.4 on 2022-07-14 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_config', '0006_auto_20220714_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInstanceCleanupConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('batch_size', models.IntegerField(default=100)),
                ('cleanup_after_days', models.IntegerField(default=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessInstanceCleanupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_process_instances', models.IntegerField(default=100)),
                ('status_code', models.IntegerField(default=200)),
                ('failure', models.IntegerField(default=0)),
                ('failure_process_instance', models.JSONField(null=True, blank=True, default=dict)),
                ('failure_text', models.TextField(blank=True, null=True))
            ],
            options={
                'verbose_name': 'Cleanup Log',
                'verbose_name_plural': 'Cleanup Logs',
            },
        ),
    ]
