org_apps_errors = {
    6001: ["expected id as query params.", " User: {}, due to: {} "],
    6002: ["Organisation Workflow not found for the app registry.", " User: {}, due to: {} "],
    6003: ["Failed to return Organisation workflow Id.", " User: {}, due to: {} "],
    6004: ["Failed to return organisation workflow data.", " User: {}, due to: {} "],
    6005: ["Failed to retrive Organisation Workflow details for id: {}, User: {} due to Permission denied, error: {}"],
    6006: ["Failed to retrive Organisation Workflow details for id: {}, User: {} is not authenticated, error: {} "],
    6007: ["ID not found.", " Failed to retrive Organisation Workflow details for id: {}, User: {}, error: {} "],
    6008: ["Failed to retrieve organisation workflow details.", "id: {}, User: {} due to Exception: {} "],
    6009: ["Failed to deploy organisation app.", " User: {}, due to: {} "],
    6010: ["Failed to deploy organisation app.", " User: {}, due to Exception: {} "],
    6011: ["ID not found", "Failed to update workflow details for id: {}, User: {} due to: {} "],
    6012: ["Failed to update workflow details.", "Id: {}, User: {}, Error: {} "],
    6013: ["Failed to return User task Lists for this organisation workflow.", "Id: {}, User:{}, Error: {} "],
    6014: ["Failed to return User task Lists for this organisation workflow.", "Id: {}, User:{}, Error: {} "],
    6015: ["Failed to return User task Lists for this organisation workflow.", "Id: {}, User:{}, Error: {} "],
    6016: ["ID not found", "Failed to return Form labels for this organisation workflow. Id: {}, User: {}, Error: {} "],
    6017: ["Failed to return Form labels for this organisation workflow.", " Id: {}, User: {}, Error: {} "],
    6018: ["Failed to return Form labels for this organisation workflow.", " Id: {}, User: {}, Error: {} "],
    6019: ["Failed to return Form labels for this organisation workflow.", " Id: {}, User: {}, Exception: {} "],
    6020: ["ID not found.", "Failed to return Form labels for this organisation workflow for id: {}, User:{} due to: {} "],
    6021: ["ID not found.", "Failed to return Form labels for this organisation workflow for id: {}, User:{} due to: {} "],
    6022: ["Failed to return Form labels for this organisation workflow."," Id: {}, User:{}, Error: {} "],
    6023: ["Failed to return Form labels for this organisation workflow."," Id: {}, User:{}, Error: {} "],
    6024: ["Failed to return Form labels for this organisation workflow."," Id: {}, User:{}, Exception: {} "],
    6025: ["Workflows does not exist in your organisation.", "User: {} "],
    6026: ["Failed to update workflows portal.", " User: {}, Error: {} "],
    6027: ["Failed to update workflows portal.", " User: {}, Exception: {} "],
    6028: ["Failed to start process", "with process Instance id: {}, User: {}, Error: {} "],
    6029: ["Failed to start process process Instance.", " Id: {}, User: {}, Error: {} "],
    6030: ["ID not found.", " Failed to search process Instance for id: {}, User:{}, Error: {} "],
    6031: ["Failed to search process Instance.", " Id:{}, User:{}, Exception: {} "],
    6032: ["ID not found.", " Failed to search process Instance for id: {}, User: {}, Error: {} "],
    6033: ["ID not found.", " Failed to search process Instance for id: {}, User: {} "],
    6034: ["Failed to apply filter for workflow.", " User: {}, Exception:{} "],
    6035: ["Your group filter is not configured properly, expected key - {}. Contact System administrator to set the value.", " User: {} "],
    6036: ["Your group filter is not configured properly, expected key - {}. Contact System administrator to set the value.", " User: {}, Exception: {} "],
    6037: ["Task Result Failed.", " User:{}, Error: 400_BAD_REQUEST "],
    6038: ["Failed to get Task Result.", " User: {}, Exception: {} "],
    6039: ["Failed to load Progress Bar for Ongoing Process.", " User:{} "],
    6040: ["Failed to load Progress Bar for Ongoing Process.", " User:{}, Exception: {} "],
    6041: ["Workflow with process Definition Key not found"," User: {}, Error: {} "],
    6042: ["No forms selected for this process", " User: {}, Error: 204_NO_CONTENT "],
    6043: ["Failed to retrieve Forms and attachments for Ongoing Process.", " User:{}, Exception: {} "],
    6044: ["ID not found.", " Id: {}, User: {}, Error: {}"],
    6045: ["Failed to start Bulk Process Initiation.", " User: {} "],
    6046: ["No start form for this process.", " Failed to start Bulk Process Initiation for Id: {}, User: {}"],
    6047: ["Bulk Import Request Failed.", " Id: {}, User: {}, Error: {} "],
    6048: ["Failed to get csv for the workflow.", " Id: {}, User: {}, Error: {} "],
    6049: ["ID not found.", " Failed to generate process diagram for id: {}, Error: {} "],
    6050: ["Failed to generate process diagram.", " Id: {}, Exception: {} "],
    6051: ["ID not found.", " Failed to search process Instance for Id: {}, User:{}, Error: {} "],
    6052: ["ID not found.", " Failed to search task count for Id: {}, User:{}, Error: Group Id not found. "],
    6053: ["ID not found.", " Failed to search task count for Id: {}, User:{}, Error: User Id: {} not found. "],
    6054: ["Failed to apply filter for workflow.", " User:{}, Exception: {} "],
    6055: ["Failed To Return Group Task Count", " User: {} Error: 400_BAD_REQUEST"],
    6056: ["Your {} is not set. Contact System administrator to set the value.", " User: {} "],
    6057: ["Failed To Return Group Task Count", " User: {}, Error: 400_BAD_REQUEST"],
    6058: ["Failed To Return Group Task Count", " User: {}, Exception: {} "],
    6059: ["Failed to retrieve count of completed and ongoing processes for an organisation.", " User: {}, Exception: {} "],
    6060: ["ID not found.", " Failed to retrieve count of completed, withdrawn and ongoing processes for organisation workflow for Id: {}, Error: {} "],
    6061: ["Failed to retrieve count of completed, withdrawn and ongoing processes for organisation workflow.", " Id: {}, Exception: {} "],
    6062: ["ID not found.", " Failed to retrieve the organisation workflow for Id: {}, User: {}, Error: {} "],
    6063: ["Failed to retrieve the organisation workflow.", " Id: {}, User: {}, Error: {} "],
    6064: ["ID not found.", " Failed to retrieve the organisation workflow for Id: {}, User: {}, Error: {} "],
    6065: ["Failed to retrieve the organisation workflow.", " Id: {}, User: {}, Error: {} "],
    6066: ["Failed to get app keys from modeler.", " User: {}, Exception: {} "],
    6067: ["Failed to do auth for modeler, User: {}, Error: {} "],
    6068: ["Failed to do auth for modeler.", " User: {}, Exception: {} "],
    6069: ["Failed to retrieve count of completed and ongoing processes for an organisation.", " User: {}, Error:{} "],
    6070: ["ID not found.", " Failed to retrieve count of completed and ongoing processes for organisation workflow for Id: {}, User: {}, Error: {} "],
    6071: ["Failed to retrieve count of completed and ongoing processes for organisation workflow.", " Id: {}, User: {}, Error: {} "],
    6072: ["ID not found.", " Failed to retrieve the organisation workflow for Id: {}, Error: {} "],
    6073: ["Failed to retrieve the organisation workflow.", " Id: {}, Error: {} "],
    6074: ["ID not found.", " Failed to retrieve  the count of completed and ongoing processes for an Organisation Workflow for Id: {}, Error: {} "],
    6075: ["Failed to retrieve  the count of completed and ongoing processes for an Organisation Workflow.", " Id: {}, Error: {} "],
    6076: ["ID not found.", " Failed to retrieve count of completed, withdrawn and ongoing processes for organisation workflow for Id: {}, Error: {} "],
    6077: ["Failed to apply filter for organisation workflow.", " Error: {}"],
    6078: ["Failed to get processes", " Error: {} "],
    6079: ["Failed to retrieve processes for organisation workflow.", " Exception: {} "],
    6080: ["Failed to create Process View for the Organisation", " User: {}, Error: {} "],
    6081: ["Failed to create Process View for the Organisation", " User: {}, Exception: {} "],
    6082: ["ID not found.", " Failed to partially update the Id: {} in Process View. User: {}, Error :{}"],
    6083: ["Failed to update Organisation Process View details.", " Id: {}, User: {}, Error: {} "],
    6084: ["Failed to update Organisation Process View details.", " Id: {}, User: {}, Exception: {} "],
    6085: ["Failed to update Organisation Process View details.", " User: {}, Exception: {} "],
    6086: ["ID not found.", "{}, Failed to send details for Id: {} from Process View. User: {}, Error: {}"],
    6087: ["Failed to retrieve Organisation Process View data.", " Id: {}, User: {}, Error: {} "],
    6088: ["ID not found.", " Failed to delete Organisation Process View for Id: {}. User: {}, Error: {} "],
    6089: ["Failed to delete Organisation Process View.", " Id: {}. User: {}, Error: {} "],
    6090: ["No records found for Row {}"],
    6091: ["Failed to send continuous progress bar data to user due to {}"],
    6092: ["Unexpected error occured : {}"],
    6093: ["Unabled to initiate Bulk process. Instance not found - {}"],
    6094: ["Error in update process instance id. Error: {}"],
    6095: ["Failed to add initiator as Involved user, processinstanceId:{}"],
    6096: ["Failed to add initiator as Involved user, processinstanceId:{}"],
    6097: ["Failed To Return System filter value, due to: {}"],
    6098: ["Failed convert task title , due to: {}"],
    6099: ["Failed to get Task Result.", " User: {}, GroupId: {}, Exception: {}"],
    6100: ["Transaction Id not found.","Error: {}"],
    6101: ["Failed to send notification,", "Error: {}"],
    6102: ["Invalid Payload for notification.", "Error: {}"],
    6103: ["Failed to submit Bulk Task"],
    6104: ["Failed to start process", "User: {}, Error: {} "],
    6105: ["Failed to fetch a list of workflow access based on policy", "Error: {} "],
    6106: ["Workflow access updation failed", "Error: {} "],
}
