IDM_AUTHENTICATION = "{}app/authentication"
APP_DEPLOYMENT = "{}app-api/app-repository/deployments"
APP_DEFINITION_DELETE = '{}app-api/app-repository/deployments/{}'
RUNTIME_PROCESS = "{}service/query/process-instances"
HISTORY_PROCESS = "{}service/history/historic-process-instances"
MONTHLY_PROCESS = "{}service/query/historic-process-instances"
IMPORT_APP = "{}app/rest/app-definitions/import?renewIdmEntries=false"
IMPORT_EXISTING_APP = "{0}app/rest/app-definitions/{1}/import?renewIdmEntries=false"
DEPLOYMENT_REPOSITORY = "{}service/repository/deployments"
GET_PROCESS_DEFINITION = "{}service/repository/process-definitions"
RETRIEVE_PROCESS_DEFINITION = "{0}service/repository/process-definitions/{1}"
START_PROCESS = "{}service/runtime/process-instances"
MODELER_APP_DEFINITION = "{}app/rest/models?filter=app&modelType=3"
MODELER_PROCESS_MODEL = "{}app/rest/models?filter=processes&modelType=0"
MODELER_DECISION_TABLE = "{}app/rest/models?filter=decisionTables&modelType=4"
MODELER_APP_DEFINITION_DELETE = "{}app/rest/models/{}?cascade=true"
MODELER_PROCESS_MODEL_DELETE = "{}app/rest/models/{}?cascade=false"
MODELER_DECISION_TABLE_DELETE = "{}app/rest/models/{}?cascade=false"
PUBLISH_APP = "{0}app/rest/app-definitions/{1}/publish"
APP_DEFINITION = "{}app-api/app-repository/app-definitions"
CREATE_USER = "{}service/identity/users"
GET_PRIVILEGES = "{}idm-api/privileges"
ADD_PRIVILEGES = "{0}idm-api/privileges/{1}/users"
GET_USER = DELETE_USER = "{0}service/identity/users/{1}"
GET_ALL_USERS = "{0}service/identity/users"
PROCESS_DEFINITION_MODEL = "{0}service/repository/process-definitions/{1}/model"
HISTORY_TASK = "{0}service/history/historic-task-instances"
PROCESS_MODEL = "{0}service/repository/process-definitions/{1}/model"
LIST_TASKS = "{0}service/runtime/tasks"
TASK_IDENTITY_LINK = "{0}service/runtime/tasks/{1}/identitylinks"
QUERY_TASKS = "{0}service/query/tasks"
START_FORM = "{0}service/repository/process-definitions/{1}/start-form2"
PROCESS_DIAGRAM = "{0}service/repository/process-definitions/{1}/image"
PROCESS_INSTANCE_UPDATE ="{0}service/runtime/process-instances/{1}/identitylinks"
GET_PROCESS_VARIABLES ="{0}service/runtime/process-instances/{1}/variables"
GET_TASK="{0}service/runtime/tasks/{1}"
 