# Generated by Django 3.1.4 on 2022-06-27 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('notification_type', models.IntegerField(choices=[(0, 'TEST_NOTIFICATION'), (1, 'REMINDER'), (2, 'REASSIGN'), (3, 'GROUP_TASK'), (4, 'INDIVIDUAL_TASK'), (5, 'OTHER_NOTIFICATION')], default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('task_id', models.UUIDField(blank=True, null=True)),
                ('meta_content', models.JSONField(blank=True, default=dict, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'unique_together': {('recipient', 'notification_type', 'task_id')},
            },
        ),
    ]
