org_config_errors = {
    8001: ["Failed to get Organisation SMTP settings.", " User: {}, Exception: {} "],
    8002: ["Failed to create Organisation SMTP settings.", " User: {}, Error: {} "],
    8003: ["Failed to create Organisation SMTP Settings", " User: {}, Error: {} "],
    8004: ["Failed to create Organisation SMTP Settings", " User: {}, Error: {} "],
    8005: ["Failed to create Organisation SMTP Settings", " User: {}, Exception: {} "],
    8006: ["Failed to test Organisation SMTP settings.", " User: {}, Error: {} "],
    8007: ["Failed to test Organisation SMTP settings.", " User: {}, Exception: {} "],
    8008: ["SMS Sending Failed.", " Exception: {} "],
    8009: ["SMS sending Failed.", " due to {} and it's content was {}"],
    8010: ["SMS sending Failed.", " Bad Request : Missing details for sending SMS "],
    8011: ["Failed to send email.", " due to {} and it's content was {} "],
    8012: ["Notification mode isn't properly passed : {}"],
    8013: ["SMS Sending Failed.", " Exception: {} "],
    8014: ["ID not found", " Id: {}, User: {}, Error: {} "],
    8015: ["{}, Failed to generate report for id: {}, Exception: {}"],
    8016: ["ID not found.", " Failed to generate entity report, User: {}, Error:{} "],
    8017: ["ID not found.", " Failed to generate entity report, User: {}, Id:{}, Error:{} "],
    8018: ["{}, Failed to generate report, Exception: {}"],
    8019: ["process Instance Id not passed.", " Id: {}, Error: {}"],
    8020: ["Failed to generate Documents.", " Exception: {} "],
    8021: ["process Instance Id not passed.", " Id: {}, Exception: {}"],
    8022: ["Failed to generate Documents.", " Exception: {} "],
    8023: ["Failed to return report templates.", " User: {}, Exception: {} "],
    8024: ["Failed to create Report templates", " User: {}, Error: {} "],
    8025: ["Failed to Report templates for the Organisation.", " User: {} Exception: {} "],
    8026: ["ID not found.", " User:{}, Failed to partially update Report templates for Id: {}, Error: {} "],
    8027: ["Failed to update Organisation Report template.", " ID: {} User: {} Error: {} "],
    8028: ["Failed to update Organisation Report template.", " ID: {} User: {} Exception: {} "],
    8029: ["ID not found.", " User: {}, Failed to retrieve data from Report templates for Id: {}, Error: {} "],
    8030: ["Failed to retrieve content details."," Id: {}, User: {}, Error: {} "],
    8031: ["ID not found.", " User: {}, Failed to delete data from Report templates for Id: {}, Error: {} "],
    8032: ["Failed to delete report template.", " Id: {}, User: {}, Exception: {} "],
    8033: ["key not found.", " Failed to retrieve data from Document templates of key: {}, Error: {} "],
    8034: ["Process Id not found.", "Failed to retrieve data from Document templates for Id: {}, Error: {} "],
    8035: ["Failed to generate Documents.", " Id: {} Error: {} "],
    8036: ["ID not found.", " Failed to retrieve data from Document templates for Id: {}, Error: {} "],
    8037: ["Process Id not found", "Failed to retrieve data from Document templates for Id: {}, Error: {}"],
    8038: ["Failed to generate Documents.", " Id: {}, Exception: {} "],
    8039: ["Failed to return template.", " Error: {} "],
    8040: ["Email Sending Failed.", " User: {}, Exception: {} "],
    8041: ["Failed to get Organisation SES settings.", " Error: {} "],
    8042: ["Failed to create Organisation SES settings.", " Error: {} "],
    8043: ["Failed to create Organisation SES Settings", " Error: {} "],
    8044: ["Failed to create Report templates", " Error: {} "],
    8045: ["Failed to create Organisation SES settings.", " Exception: {} "],
    8046: ["Failed to verify email, due to: 404_NOT_FOUND."],
    8047: ["Failed to verify email, due to: 404_NOT_FOUND."],
    8048: ["Failed to retrieve Email Details.", " Exception: {} "],
    8049: ["Failed to register email, Exception: {} "],
    8050: ["Failed to get any email settings.", " Exception: {} "],
    8051: ["Notification mode improperly passes : {}"],
    8052: ["Email Sending Failed.", " Exception: {} "],
    8053: ["Failed to create Custom Attribute for the Organisation", " User: {}, Error: {} "],
    8054: ["Failed to create Custom Attribute for the Organisation.", " User: {}, Exception: {} "],
    8055: ["Failed to get Organisation Custom Attribute data.", " User: {}, Exception: {} "],
    8056: ["ID not found.", " User: {}, Failed to retrieve Organisation Custom Attribute details for id: {}, Error: {} "],
    8057: ["Failed to retrieve Organisation Custom Attribute details.", " User: {}, Id: {}, Exception: {} "],
    8058: ["ID not found.", " User: {}, Failed to update Organisation Custom Attribute for id :{}, Error: {} "],
    8059: ["Failed to update Organisation Custom Attribute details.", " User: {}, Id: {}, Error: {}"],
    8060: ["Failed to update Organisation Custom Attribute details.", " User: {}, Id: {}, Exception: {} "],
    8061: ["Failed to retrieve Organisation Custom Attribute details.", " User: {}, type: {}, Error: {} "],
    8062: ["Failed to retrieve Organisation Custom Attribute details.", " User: {}, type: {}, Exception: {} "],
    8063: ["Failed to create Email Digest", " Error: {} "],
    8064: ["Failed to Email Digest for the Organisation.", " Exception: {} "],
    8065: ["Dashboard with this role or name already exists.", "User: {}, Failed to create Dashboard, Error: {}. "],
    8066: ["Failed to create a Dashboard.", " Exception: {} "],
    8067: ["Failed to return Dashboard data.", " User:{}, Exception: {}"],
    8068: ["ID not found.", " USer: {}, Failed to partially update the dashboard for id: {}, Error: {} "],
    8069: ["Dashboard with this role or name already exists.", "User: {}, Failed to update Dashboard Details for id {}, Error: {}. "],
    8070: ["Failed to update the dashboard details.", " User: {}, Id: {}, Exception: {} "], 
    8071: ["ID not found.", " User:{}, Failed to delete dashboard for id: {}, Error: {} "],
    8072: ["Failed to delete Dashboard.", " User: {}, Id:{}, Exception: {} "],
    8165: ["job view with this role or name already exists.", "User: {}, Failed to create job view, Error: {}. "],
    8166: ["Failed to create a job view.", " Exception: {} "],
    8167: ["Failed to return job view data.", " User:{}, Exception: {}"],
    8168: ["ID not found.", " USer: {}, Failed to partially update the job view for id: {}, Error: {} "],
    8169: ["job view with this role or name already exists.", "User: {}, Failed to update job view Details for id {}, Error: {}. "],
    8170: ["Failed to update the job view details.", " User: {}, Id: {}, Exception: {} "], 
    8171: ["ID not found.", " User:{}, Failed to delete job view for id: {}, Error: {} "],
    8172: ["Failed to delete job view.", " User: {}, Id:{}, Exception: {} "],
    8265: ["event view with this role or name already exists.", "User: {}, Failed to create event view, Error: {}. "],
    8266: ["Failed to create a event view.", " Exception: {} "],
    8267: ["Failed to return event view data.", " User:{}, Exception: {}"],
    8268: ["ID not found.", " USer: {}, Failed to partially update the event view for id: {}, Error: {} "],
    8269: ["event view with this role or name already exists.", "User: {}, Failed to update event view Details for id {}, Error: {}. "],
    8270: ["Failed to update the event view details.", " User: {}, Id: {}, Exception: {} "], 
    8271: ["ID not found.", " User:{}, Failed to delete event view for id: {}, Error: {} "],
    8272: ["Failed to delete event view.", " User: {}, Id:{}, Exception: {} "],
    8073: ["Failed to return Widget data.", " User: {}, Exception: {} "],
    8074: ["{}, The file does not exist, may have failed to get uploaded to s3. Error: {} "],
    8075: ["{}, The file does not exist, may have failed to get uploaded to s3. Error: {} "],
    8076: ["{}, Failed to generate process report, Exception: {} "],
    8077: ["The file upload in s3 failed."],
    8078: ["Failed to update custom attribute for {}"],
    8079: ["{}, Failed to generate report Excel, Exception: {}"],
    8080: ["{}, The entity file upload in s3 failed, Error:{}"],
    8081: ["{}, Failed to generate entity report, Exception: {}"],
    8082: ["{}, Failed to create report, Exception: {}"],
    8083: ["{}, Failed to create Inventory report, Exception: {}"],
    8084: ["{}, Failed to create Inventory Distribution report, Exception: {}"],
    8085: ["Failed to return chart name.", " User:{}, Exception: {}"],
    8086: ["{}, Failed to create BGV report, Exception: {}"],
}
