# Generated by Django 3.1.4 on 2023-01-20 02:54

import apps.org_import.models
from django.db import migrations, models
import ezedox.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('org_import', '0002_entityimport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityimport',
            name='file',
            field=models.FileField(blank=True, null=True, storage=ezedox.custom_storage.OtherFileStorage(), upload_to=apps.org_import.models.generate_path),
        ),
    ]
