# Generated by Django 3.1.4 on 2024-05-22 06:34

import apps.org_import.models
from django.db import migrations, models
import ezedox.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('org_import', '0004_auto_20240206_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityimport',
            name='file',
            field=models.FileField(blank=True, max_length=356, null=True, storage=ezedox.custom_storage.OtherFileStorage(), upload_to=apps.org_import.models.generate_path),
        ),
    ]
