# Generated by Django 3.1.4 on 2024-12-24 11:17

import apps.org_import.models
from django.db import migrations, models
import ezedox.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('org_import', '0005_auto_20240522_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityimport',
            name='file',
            field=models.FileField(blank=True, max_length=356, null=True, storage=ezedox.custom_storage.AzureFileStorage(), upload_to=apps.org_import.models.generate_path),
        ),
    ]
