org_users_errors = {
    23001:["SELF ONBOARDING APP INSTALLATION FAILED", " Error: {} "],
    23002:["Failed to create organisation owner.", " Error: {} "],
    23003:["Failed to create organisation owner.", " Error: {} "],
    23004:["Failed to create organisation owner.", " Error: {} "],
    23005:["Password is not provided.", " HTTP_400_BAD_REQUEST "],
    23006:["The set password link is no longer valid.", " HTTP_400_BAD_REQUEST "],
    23007:["Unable to set password.", " Error: {} "],
    23008:["Failed to send reset password email.", " Error: {} "],
    23009:["User credentials incorrect.", " User: {}, Error: HTTP_400_BAD_REQUEST "],
    23010:["Passwords does not match.", " User: {}, Error: HTTP_400_BAD_REQUEST "],
    23011:["Failed to change password.", " User: {}, Error: {} "],
    23012:["You are not intended to login into this system"," Error: HTTP_400_BAD_REQUEST"],
    23013:["Your account has been deactivated.", " HTTP_400_BAD_REQUEST "],
    23014:["Invalid Login Credentials", " Error: HTTP_400_BAD_REQUEST "],
    23015:["Failed to login.", " Your account has been deactivated, Error: {} "],
    23016:["Failed to get Organisation Users data.", " User: {}, Error: {} "],
    23017:["Failed to get Third party users data.", " Error: {} "],
    23018:["Failed to get all organisation users data.", " Error: {} "],
    23019:["Failed to get task users data.", " Error: {} "],
    23020:["User with this emailId already exists.", " User:{}, Error: HTTP_400_BAD_REQUEST "],
    23021:["Invalid Default Password, please provide one with a minimum of 8 characters.", " User: {}, is trying to add an active user without default password, Error: HTTP_400_BAD_REQUEST "],
    23022:["Failed to create organisation user.", " User: {}, Error: {} "],
    23023:["Failed to create organisation user.", " User: {}, Error: {} "],
    23024:["Failed to create organisation user.", " User: {}, Error: {} "],
    23025:["Failed to retrieve Organisation user.", " User: {}, Id: {}, Error: {} "],
    23026:["Failed to retrieve Organisation user.", " User: {}, Id: {}, Error: {} "],
    23027:["ID not found.", " User: {}, Failed to retrieve Organisation user for id: {}. Error: {} "],
    23028:["Failed to retrieve Organisation User details.", " User: {}, Id: {}, Error: {} "],
    23029:["ID not found.", " User: {}, Failed to update Organisation user for id: {}. Error: {} "],
    23030:["Failed to update Organisation User details.", " User: {}, Id: {}, Error: {} "],
    23031:["Failed to update Organisation User details.", " User: {}, Id: {}, Error: {} "],
    23032:["Failed to update Organisation User details.", " User: {}, Id: {}, Error: {} "],
    23033:["ID not found.", " User: {}, Failed to delete Organisation user for id: {}. Error: {} "],
    23034:["Failed to delete organisation user.", " User: {}, Id: {}, Error: {} "],
    23035:["Failed to delete organisation user.", " User: {}, Id: {}, Error: {} "],
    23036:["Failed to get csv.", " User: {}, Error: {} "],
    23037:["ID not found.", " Failed to retrieve display picture of id : {}. Error: {} "],
    23038:["Failed to retrieve display picture.", " Id: {}, Error: {} "],
    23039:["ID not found.", " Failed to retrieve user involved group data for id : {}. Error: {} "],
    23040:["Failed to retrieve user involved group data.", " Id :{}, Error: {} "],
    23041:["User ID not found.", " Failed to update organisation user. Error: {} "],
    23042:["Failed to update organisation user.", " Error: {} "],
    23043:["User ID not found.", " Failed to recover user for id: {}. Error: {} "],
    23044:["Failed to activate organisation users data.", " Id :{}, Error: {} "],
    23045:["Failed to get Roles data.", " User: {}, Error: {} "],
    23046:["Roles ID not found.", " User: {}, Failed to retrieve Roles details for id: {}. Error: {} "],
    23047:["Failed to retrieve Roles details.", " User: {}, Id: {}, Error: {} "],
    23048:["Failed to create Role.", " User: {}, Error: {} "],
    23049:["Failed to create Role.", " User: {}, Error: {} "],
    23050:["Failed to get External Users data.", " User: {}, Error: {} "],
    23051:["User with this email Id is already registered as Organisation User, This email Id can not be used as External User. Try registering with a different email Id.", " Failed to create External User. "],
    23052:["User with this email id or phone number already exists", " Failed to create External User. "],
    23053:["Failed to create External user.", " User: {}, Error: {} "],
    23054:["Failed to create External user.", " User: {}, Error: {} "],
    23055:["ID not found.", " User: {}, Failed to retrieve External User for id: {}. Error: {} "],
    23056:["Failed to retrieve External User details.", " User: {}, Id: {}, Error: {} "],
    23057:["ID not found.", " User: {}, Failed to update External User for id: {}. Error: {} "],
    23058:["Failed to update External User details.", " User: {}, Id: {}, Error: {} "],
    23059:["Failed to update External User details.", " User: {}, Id: {}, Error: {} "],
    23060:["ID not found.", " User: {}, Failed to delete External User for id: {}. Error: {} "],
    23061:["Failed to delete External user.", " User: {}, Id:{}, Error: {} "],
    23062:["Mobile number or email is required.", " Unable to generate OTP. "],
    23063:["User with this mobile number or email does not exist", "User with this mobile number or email does not exist "],
    23064:["More than one user with this mobile number is registered, please enter your email along with mobile number."],
    23065:["Invalid mobile number or email.", " Error: User does not exists "],
    23066:["Unable to send OTP.", " Error: {} "],
    23067:["Unable to generate OTP.", " Error: {} "],
    23068:["User with this mobile number or email does not exist"],
    23069:["More than one user with this mobile number is registered, please send your email along with mobile number."],
    23070:["Invalid mobile number or email.", " User does not exists. "],
    23071:["Your account has been deactivated, please contact your administrator."],
    23072:["You are not intented to login into this system."],
    23073:["Authentication failed!", " Unable to validate OTP."],
    23074:["Unable to validate OTP.", " Error: {} "],
    23075:["Unable to Generate login credentials.", " Error: {} "],
    23076:["mobile is required.", " OTP Failed "],
    23077:["OTP Failed", " Error: {} "],
    23078:["Failed to send activation link.", " Error: {} "],
    23079:["First Name not provided at row no. {} in user bulk import"],
    23080:["Incorrect Role Id for user {} at row no {} in user bulk import"],
    23081:["Incorrect Manager email found for user {} at row no. {} in user bulk import"],
    23082:["Incorrect Department for user {} at row no {} in user bulk import"],
    23083:["Incorrect Location for user {} at row no {} in user bulk import"],
    23084:["error for user {} is {}"],
    23085:["error for user {} is {} in user bulk import"],
    23086:["Data insufficient for user {} at row no {} in user bulk import"],
    23087:["Error occurred is {} in user bulk import"],
    23088:["Failed to create External user.", " User: {}, Error: {} "],
    23089:["Your account has been deactivated.", " HTTP_400_BAD_REQUEST "],
    23090:["Mobile number is required.", " Unable to generate OTP. "],
    23091:["Failed to create External user.", " User: {}, Error: {} "],
    23092:["Unable to send OTP.", " Error: {} "],
    23093:["Unable to generate OTP.", " Error: {} "],
    23094:["User with this mobile number does not exist"],
    23095:["Authentication failed!", " Unable to validate OTP."],
    23096:["Unable to validate OTP.", " Error: {} "],
    23097:["User with this mobile number does not exist"],
    23098:["More than one user with this mobile number is registered, please send your email along with mobile number."],
    23099:["Invalid mobile number or email.", " User does not exists. "],
    23100:["Your account has been deactivated, please contact your administrator."],
    23101:["You are not intented to login into this system."],
    23102:["Authentication failed!", " Unable to validate OTP."],
    23103:["Unable to validate OTP.", " Error: {} "],
    23104:["User with this email Id is already registered as Organisation User, This email Id can not be used as External User. Try registering with a different email Id.", " Failed to create External User. "],
    23105:["User with this email id or phone number already exists", " Failed to create External User. "],
    23106:["Failed to create External user.", " User: {}, Error: {} "],
    23107:["Unable to send OTP.", " Error: {} "],
    23108:["User already present with provided mobile number in platform.", " Error: {} "],
    23109:["Failed to fetch platform policy", " Error: {} "]
}