org_location_errors = {
    17001:["Failed to get Locations.", " User: {}, Exception: {} "],
    17002:["Location with this name already exists.", " User: {}, Error: {} "],
    17003:["Failed to create Location.", " User: {}, Error: {} "],
    17004:["Failed to create Location.", " User: {}, Exception: {} "],
    17005:["Location not found.", " User: {}, Id: {}, Error: {} "],
    17006:["Failed to retrieve Location.", " User: {}, Id: {}, Exception: {} "],
    17007:["Location not found."," {}, Failed to update Location Details for Id :{}, Error: {} "],
    17008:["Location with this name already exists.", " {}, Failed to update Location Details for Id {}, Error: {} "],
    17009:["Failed to update Location Details.", " User: {}, Id: {}, Exception: {} "],
    17010:["Failed to update Location.", " User: {},Id: {}, Exception: {} "],
    17011:["Location not found.", " Failed to delete location details. User: {},Id: {}, Error: {} "],
    17012:["Please remove the organisation users from this location and then delete it.", "User: {}, Id: {} "],
    17013:["Failed to delete Location.", "User: {},Id: {}, Exception: {} "],
    17014:["Failed to get csv.", "User: {}, Exception: {} "],
    17015:["error for Location {} is {}"],
    17016:["{} raised for location named {} in location bulk import"],
    17017:["Insufficient Data for {} in location bulk import"],
    17018:["Data not matched for {} in location bulk import"],
    17019:["Location Name is not provided at row no {} in location bulk import"],
    17020:["Unexpected error occured : {}"],
    17021:["Unexpected error occured while getting all location tags : {}"],
    17022:["Please provide expected_type in query params : {}"],
    17023:["Unexpected error occured while getting all custom tags : {}"],
}
