org_entity_errors = {
    10001:["Failed to create new Record.", " Error: {} "],
    10002:["Failed to add Record.", " Exception: {} "],
    10003:["Failed to get Record.", " Exception: {} "],
    10004:["ID not found", " Id: {}, Error: {} "],
    10005:["Failed to update Record.", " Id: {}, Error: {} "],
    10006:["Failed to update Record.", " Id: {}, Exception: {} "],
    10007:["ID not found", " Id: {}, Error: {} "],
    10008:["Failed to retrieve Record.", " Id: {}, Exception: {} "],
    10009:["Failed to create a new record.", " Exception: {} "],
    10010:["Failed to create a new record."],
    10011:["Failed to create a new record."],
    10012:["Failed to create a new record.", " Exception: {} "],
    10013:["Failed to create a new record.", " Error: {} "],
    10014:["Failed to create a new record.", " Exception: {} "],
    10015:["ID not found", " Id: {}, Error: {} "],
    10016:["No view is set for your role. Please contact your system administrator.", " Error:{} "],
    10017:["Your account is not configured correctly. Location Not set For you. Please contact the system administrator"],
    10018:["Your account is not configured correctly. Department Not set For you. Please contact the system administrator"],
    10019:["Your account is not configured correctly. Custom Attribute is not set for you. Please contact the system administrator"],
    10020:["Your account is not configured correctly. Incorrect Filter Set. Please contact the system administrator"],
    10021:["Failed to get the record", " Exception: {} "],
    10022:["Failed to get the record."],
    10023:["ID not found.", " Error: {} "],
    10024:["No view is set for your role. Please contact your system administrator."],
    10025:["Your account is not configured correctly. Location Not set For you. Please contact the system administrator"],
    10026:["Your account is not configured correctly. Department Not set For you. Please contact the system administrator"],
    10027:["Your account is not configured correctly. Custom Attribute is not set for you. Please contact the system administrator"],
    10028:["Your account is not configured correctly. Incorrect Filter Set. Please contact the system administrator"],
    10029:["Failed to get the record.", " Exception: {} "],
    10030:["ID not found.", " ID: {}, Error: {} "],
    10031:["Failed to update the Record details.", " ID: {}, Error: {} "],
    10032:["Failed to update the Record details.", " ID: {}, Exception: {} "],
    10033:["ID not found.", " ID: {}, Error: {} "],
    10034:["Failed to retrieve the Record details.", " ID: {}, Exception: {} "],
    10035:["ID not found.", " ID: {}, Error: {} "],
    10036:["Failed to retrieve Entity master Data.", " ID: {}, Exception: {} "],
    10037:["ID not found.", " ID: {}, Error: {} "],
    10038:["Failed to retrieve record", " ID: {}, Exception: {} "],
    10039:["Data not found.", " Error: {} "],
    10040:["Failed to delete a record", " Exception: {} "],
    10041:["Failed to update a new record", " Error: {} "],
    10042:["Data not passed Properly"],
    10043:["Failed to update a record", " Error: {} "],
    10044:["ID not found.", " {}, Failed to start Bulk Updation: {}, Error: {}. "],
    10045:["Failed to get csv for workflow.", " Error: {}. "],
    10046:["Failed to get csv for workflow.", " User: {}, Exception: {}. "],
    10047:["No Data available for requested Record", " Error: {}. "],
    10048:["Data not passed Properly"],
    10049:["Failed to search Record.", " Exception: {} "],
    10050:["Lookup json not configured properly."],
    10051:["Failed to update a Record.", " Exception: {} "],
    10052:["No Data available for requested Record.", " Error: {} "],
    10053:["Failed to search Record.", " Error: {} "],
    10054:["No Data available for requested Record.", " Error: {} "],
    10055:["Failed to generate Record.", " Error: {} "],
    10056:["Entity not found.", " Error: {} "],
    10057:["Failed to create a new record.", " Error: {} "],
    10058:["Failed to create a new record.", " Error: {} "],
    10059:["Failed to create a new record.", " Exception: {} "],
    10060:["ID not found.", " {}, Failed to retrive View details for id: {}, Error: {} "],
    10061:["Failed to load the view.", " Exception: {} "],
    10062:["Failed to load the view.", "{}, Failed to send list of View, Error: {}."],
    10063:["Failed to create a View.", "{}, Failed to create View due to serializer is not valid: {}."],
    10064:["Failed to create a View.", "{}, Failed to create Entity View due to: {}."],
    10065:["ID not found.", "{}, Failed to partially update for id: {} in View, Error:{}. "],
    10066:["Failed to update View details.", " {}, Failed to partial update for id: {} in View, Error: {}. "],
    10067:["Failed to update View details.", " {}, Failed to partial update for id: {} in View, Error: {}. "],
    10068:["ID not found.", " Failed to delete View. User: {}, ID: {}, Error:{}. "],
    10069:["Failed to delete a View.", " User: {}, ID: {}, Error:{}. "],
    10070:["Failed to load the View.", "ID: {}, Error:{}. "],
    10071:["Data not found.", " Error:{}. "],
    10072:["Failed to delete a Record.", " Error:{}. "],
    10073:["ID not found.", "{}, Failed to retrive Record Log, due to invalid Record id, Exception: {} "],
    10074:["Failed to add audit log.", " Error: {} "],
    10075:["Failed to add audit log.", " Exception: {} "],
    10076: ["Failed To create profile for BGV initiation for entity id: {}, due to: {}"],
    10077: ["Failed To process bgv profile creation response for entity id: {}, due to: {}"],
    10078: ["Failed To create profile for BGV initiation for entity id: {}, due to: {}"],
    10079: ["Failed To process bgv profile creation response for entity id: {}, due to: {}"],
    10080: ["Failed To initiate bgv check for entity id: {}, for check type: {}, due to: {}"],
    10081: ["Failed To process bgv initiation response for entity id: {}, for check type: {}, due to: {}"],
    10082: ["Failed To Update bgv check for entity id: {}, for check type: {}, due to: {}"],
    10083: ["Failed To process bgv update response for entity id: {}, for check type: {}, due to: {}"],
    10084: ["Failed To performe bgv action for entity id: {}, for check type: {}, due to: {}"],
    10085:['Failed to return document reference id, due to: {}'],
    10086: ["Failed To generate bgv report of type: {}, for bgv id : {}, due to: {}"],
    10087:["Failed to create candidate profile.", " User: {}, Failed to create candidate profile, due to:{} "],
    10091:["Failed to Transfer Entity from one tenant to another.", "Error : {}"],
    10092: ["Failed to get Audit History data.", "Error : {}"]
}
