org_jobs_errors = {
     26001:["Failed to get Job data.", " User: {}, Failed to get Job data, Exception :{} "],
     26003:["ID not found.", "User: {} Failed to retrieve Job details for id: {}, Error: {} "],
     26003:["Failed to retrieve Job details.", " User: {}, Failed to retrieve Job details for id: {}, Error: {} "],
     26004:["Failed to create new Job.", " User: {}, Failed to create new Job, due to:{} "],
     26005:["Failed to create new Job.", " User: {}, Failed to create new Job, due to:{} "],
     26006:["ID not found.", " User: {}, Failed to update Job for id: {}, Error: {} "],
     26007:["Failed to update Job details.", " User: {}, Failed to update Job details for id: {}, Error: {} "],
     26008:["Failed to update Job details.", " User: {}, Failed to update Job details for id: {}, Error: {} "],
     26009:["ID not found.", " User: {}, Faliled to delete Job for id: {}, Error: {} "],
     26010:["Failed to delete Job data", " User: {}, Faliled to delete Job for id: {}, Error: {} "],
     26011:["Failed to get Job Role data.", " User: {}, Failed to get Job Role data, Exception :{} "],
     26012:["ID not found.", "User: {} Failed to retrieve Job Role details for id: {}, Error: {} "],
     26013:["Failed to retrieve Job Role details.", " User: {}, Failed to retrieve Job Role details for id: {}, Error: {} "],
     26014:["Failed to create new Job Role.", " User: {}, Failed to create new Job Role, due to:{} "],
     26015:["Failed to create new Job Role.", " User: {}, Failed to create new Job Role, due to:{} "],
     26016:["ID not found.", " User: {}, Failed to update Job Role for id: {}, Error: {} "],
     26017:["Failed to update Job Role details.", " User: {}, Failed to update Job Role details for id: {}, Error: {} "],
     26018:["Failed to update Job Role details.", " User: {}, Failed to update Job Role details for id: {}, Error: {} "],
     26019:["ID not found.", " User: {}, Faliled to delete Job Role for id: {}, Error: {} "],
     26020:["Failed to delete Job Role data", " User: {}, Faliled to delete Job Role for id: {}, Error: {} "],
     26021:["Failed to get Hiring Event data.", " User: {}, Failed to get Hiring Event data, Exception :{} "],
     26022:["ID not found.", "User: {} Failed to retrieve Hiring Event details for id: {}, Error: {} "],
     26023:["Failed to retrieve Hiring Event details.", " User: {}, Failed to retrieve Hiring Event details for id: {}, Error: {} "],
     26024:["Failed to create new Hiring Event.", " User: {}, Failed to create new Hiring Event, due to:{} "],
     26025:["Failed to create new Hiring Event.", " User: {}, Failed to create new Hiring Event, due to:{} "],
     26026:["ID not found.", " User: {}, Failed to update Hiring Event for id: {}, Error: {} "],
     26027:["Failed to update Hiring Event details.", " User: {}, Failed to update Hiring Event details for id: {}, Error: {} "],
     26028:["Failed to update Hiring Event details.", " User: {}, Failed to update Hiring Event details for id: {}, Error: {} "],
     26029:["ID not found.", " User: {}, Faliled to delete Hiring Event for id: {}, Error: {} "],
     26030:["Failed to delete Hiring Event data", " User: {}, Faliled to delete Hiring Event for id: {}, Error: {} "],  
     26031:["Failed to get Hiring Partner data.", " User: {}, Failed to get Hiring Partner data, Exception :{} "],
     26032:["ID not found.", "User: {} Failed to retrieve Hiring Partner details for id: {}, Error: {} "],
     26033:["Failed to retrieve Hiring Partner details.", " User: {}, Failed to retrieve Hiring Partner details for id: {}, Error: {} "],
     26034:["Failed to create new Hiring Partner.", " User: {}, Failed to create new Hiring Partner, due to:{} "],
     26035:["Failed to create new Hiring Partner.", " User: {}, Failed to create new Hiring Partner, due to:{} "],
     26036:["ID not found.", " User: {}, Failed to update Hiring Partner for id: {}, Error: {} "],
     26037:["Failed to update Hiring Partner details.", " User: {}, Failed to update Hiring Partner details for id: {}, Error: {} "],
     26038:["Failed to update Hiring Partner details.", " User: {}, Failed to update Hiring Partner details for id: {}, Error: {} "],
     26039:["ID not found.", " User: {}, Faliled to delete Hiring Partner for id: {}, Error: {} "],
     26040:["Failed to delete Hiring Partner data", " User: {}, Faliled to delete Hiring Partner for id: {}, Error: {} "],
     26041:["Failed to get Partner data.", " User: {}, Failed to get Partner data, Exception :{} "],
     26042:["ID not found.", "User: {} Failed to retrieve Partner details for id: {}, Error: {} "],
     26043:["Failed to retrieve Partner details.", " User: {}, Failed to retrieve Partner details for id: {}, Error: {} "],
     26044:["Failed to create new Partner.", " User: {}, Failed to create new Partner, due to:{} "],
     26045:["Failed to create new Partner.", " User: {}, Failed to create new Partner, due to:{} "],
     26046:["ID not found.", " User: {}, Failed to update Partner for id: {}, Error: {} "],
     26047:["Failed to update Partner details.", " User: {}, Failed to update Partner details for id: {}, Error: {} "],
     26048:["Failed to update Partner details.", " User: {}, Failed to update Partner details for id: {}, Error: {} "],
     26049:["ID not found.", " User: {}, Faliled to delete Partner for id: {}, Error: {} "],
     26050:["Failed to delete Partner data", " User: {}, Faliled to delete Partner for id: {}, Error: {} "],
     26071:["Failed to get JobCandidate data.", " User: {}, Failed to get JobCandidate data, Exception :{} "],
     26072:["ID not found.", "User: {} Failed to retrieve JobCandidate details for id: {}, Error: {} "],
     26073:["Failed to retrieve JobCandidate details.", " User: {}, Failed to retrieve JobCandidate details for id: {}, Error: {} "],
     26074:["Failed to create new JobCandidate.", " User: {}, Failed to create new JobCandidate, due to:{} "],
     26075:["Failed to create new JobCandidate.", " User: {}, Failed to create new JobCandidate, due to:{} "],
     26076:["ID not found.", " User: {}, Failed to update JobCandidate for id: {}, Error: {} "],
     26077:["Failed to update JobCandidate details.", " User: {}, Failed to update JobCandidate details for id: {}, Error: {} "],
     26078:["Failed to update JobCandidate details.", " User: {}, Failed to update JobCandidate details for id: {}, Error: {} "],
     26079:["ID not found.", " User: {}, Faliled to delete JobCandidate for id: {}, Error: {} "],
     26080:["Failed to delete JobCandidate data", " User: {}, Faliled to delete JobCandidate for id: {}, Error: {} "],
     26081:["Failed to get HeadCountPlan data.", " User: {}, Failed to get HeadCountPlan data, Exception :{} "],
     26082:["ID not found.", "User: {} Failed to retrieve HeadCountPlan details for id: {}, Error: {} "],
     26083:["Failed to retrieve HeadCountPlan details.", " User: {}, Failed to retrieve HeadCountPlan details for id: {}, Error: {} "],
     26084:["Failed to create new HeadCountPlan.", " User: {}, Failed to create new HeadCountPlan, due to:{} "],
     26085:["Failed to create new HeadCountPlan.", " User: {}, Failed to create new HeadCountPlan, due to:{} "],
     26086:["ID not found.", " User: {}, Failed to update HeadCountPlan for id: {}, Error: {} "],
     26087:["Failed to update HeadCountPlan details.", " User: {}, Failed to update HeadCountPlan details for id: {}, Error: {} "],
     26088:["Failed to update HeadCountPlan details.", " User: {}, Failed to update HeadCountPlan details for id: {}, Error: {} "],
     26089:["ID not found.", " User: {}, Faliled to delete HeadCountPlan for id: {}, Error: {} "],
     26090:["Failed to delete HeadCountPlan data", " User: {}, Faliled to delete HeadCountPlan for id: {}, Error: {} "],
     26091:['Failed to get chart view', " User: {}, Failed to get chart view due to: {}",],
     26092:['Failed to get statistics data for job', " User: {}, Failed to get statistics data for job due to: {}",],
     26093:["Failed to get HeadCountPlan Gap data.", " User: {}, Failed to get HeadCountPlan Gap data, Exception :{} "],
     26094:["Failed to get JobCandidate data for total_applicant_in_active_event.", " User: {}, Failed to get JobCandidate data for total_applicant_in_active_event, Exception :{} "],
     26095:["Failed to get HiringState data.", " User: {}, Failed to get HiringState data, Exception :{} "],
     26096:['Failed to get dashboard statistics data for job', " User: {}, Failed to get dashboard statistics data for job due to: {}",],
     26097:["Job Role with this name already exists.", " User: {}, Error: {} "],
     26098:["Job Role with this name already exists.", " {}, Failed to update Job Role Details for Id {}, Error: {} "],
     26099:["This job role is used at multiple places to delete this role please contact the system administrator.", "User: {}, Id: {} "],
     26100:["Your account is not configured correctly. Please contact the system administrator."," User: {}, Error: {} "],
     26101:["Your account is not configured correctly. Please contact the system administrator."," User: {}, Error: {} "],
     26102:["Your account is not configured correctly. Please contact the system administrator."," User: {}, Error: {} "],
     26103:["Your account is not configured correctly. Please contact the system administrator."," User: {}, Error: {} "],
     26104:["Job with this role and location already exists.", " User: {}, Failed to create new Job, due to:{} "],
     26105:["Job with this role and location already exists.", " User: {}, Failed to create new Job, due to:{} "],
     26106:["This job is already used, to delete this job please contact the system administrator.", "User: {}, Id: {} "],
     26107:["Candidates are associated with this job, this job can not be deleted.", "User: {}, Id: {} "],
     26108:["This job is tagged with hiring event, to delete this, first remove it from hiring events.", "User: {}, Id: {} "],
     26109:["Failed to get hiring status chart data.", " User: {}, Failed to get hiring status chart data due to: {} "],
     26110:["Failed to get hiring state and status data.", " User: {}, Failed to get hiring state and status data, due to : {} "],
     26111:["No Job found with provided  job_id.", " User: {}, Error: {} "],
     26112:["No candidate found with provided id.", " User: {}, Error: {} "],
     26113: ["Failed to source candidate from candidate pool.", " User: {} due to:{} "],
     26114: ["Failed to get application history.", " User: {} due to:{} "],
}


slot_errors = {
     27001:["Failed to get Slot data.", " User: {}, Failed to get Slot data, Exception :{} "],
     27002:["Failed to get Slot data.", " User: {}, Failed to get Slot data, Exception :{} "],
     27003:["Failed to retrieve Slot details.", " User: {}, Failed to retrieve Slot details for id: {}, Error: {} "],
     27004:["Failed to retrieve Slot details.", " User: {}, Failed to retrieve Slot details for id: {}, Error: {} "],
     27005:["Failed to get Candidate-Slot data.", " User: {}, Failed to get Candidate-Slot data, Exception :{} "],
     27006:["Failed to get Candidate-Slot data.", " User: {}, Failed to get Candidate-Slot data, Exception :{} "],
     27007:["Failed to retrieve Candidate-Slot details.", " User: {}, Failed to retrieve Candidate-Slot details for id: {}, Error: {} "],
     27008:["Failed to retrieve Candidate-Slot details.", " User: {}, Failed to retrieve Candidate-Slot details for id: {}, Error: {} "],   
     27009:["Failed to create new Slot.", " User: {}, Failed to create new Slot, due to:{} "],
     27010:["Failed to create new Slot.", " User: {}, Failed to create new Slot, due to:{} "],
     27011:["ID not found.", " User: {}, Failed to update Slot for id: {}, Error: {} "],
     27012:["Failed to update Slot details.", " User: {}, Failed to update Slot details for id: {}, Error: {} "],
     27013:["Failed to update Slot details.", " User: {}, Failed to update Slot details for id: {}, Error: {} "],
     27014:["ID not found.", " User: {}, Faliled to delete Slot for id: {}, Error: {} "],
     27015:["Failed to delete Slot data", " User: {}, Faliled to delete Slot for id: {}, Error: {} "],
     27016:["Failed to create new Candidate Slot Mapping.", " User: {}, Failed to create new Candidate Slot Mapping, due to:{} "],
     27017:["Failed to create new Candidate Slot Mapping.", " User: {}, Failed to create new Candidate Slot Mapping, due to:{} "],
     27018:["ID not found.", " User: {}, Faliled to delete Candidate Slot Mapping for id: {}, Error: {} "],
     27019:["Failed to delete Candidate Slot Mapping data", " User: {}, Faliled to delete Candidate Slot Mapping for id: {}, Error: {} "],

}


hiring_request_error = {
     28001:["Failed to create new Hiring Request.", " User: {}, Failed to create hiring request, due to:{} "],
     28002:["Failed to create new Hiring Request.", " User: {}, Failed to create hiring request Exception :{} "],
     28003:["ID not found.", " User: {}, Failed to update Hiring Request for id: {}, Error: {} "],
     28004:["Failed to update Hiring Request details.", " User: {}, Failed to update Hiring Request details for id: {}, Error: {} "],
     28005:["Failed to update Hiring Request details.", " User: {}, Failed to update Hiring Request details for id: {}, Error: {} "]
}