# Generated by Django 3.1.4 on 2022-06-27 12:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('createdOn', models.DateTimeField(blank=True, default=None, null=True)),
                ('createdBefore', models.DateTimeField(blank=True, default=None, null=True)),
                ('createdAfter', models.DateTimeField(blank=True, default=None, null=True)),
                ('dueOn', models.DateTimeField(blank=True, default=None, null=True)),
                ('dueBefore', models.DateTimeField(blank=True, default=None, null=True)),
                ('dueAfter', models.DateTimeField(blank=True, default=None, null=True)),
                ('nameLike', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('processDefinitionKey', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('processStateFilter', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('filter_query', models.JSONField(blank=True, default=dict, null=True)),
                ('active_filter', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Organisation Filter',
                'verbose_name_plural': 'Organisation Filters',
            },
        ),
    ]
