apiVersion: v1
kind: ConfigMap
metadata:
  name: cw-prod-config
  namespace: cw
data:
  POSTGRES_HOST: "10.173.76.13"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "bp_ril_prod_cw_app_db"
  FLOWABLE_POSTGRES_DB: "bp_ril_prod_cw_process_db"
  POSTGRES_USER: "cwmsprodrw"
  FILE_BUCKET: "AZURE"
  AZURE_ACCOUNT_NAME: 'cwmsprdprivate'
  AZURE_CONTAINER: 'cw-backend-prod'
  KAFKA_BROKERS: "10.173.76.5:9092,10.173.76.26:9092,10.173.76.17:9092"
  TEMP_DIR: "logs/"
  ENV: "prod"
  PROD: "True"
  DEBUG: "False"
  LAUNCH_PROCESS_TOPICS: "prod-domain-updates"
  BASE_ORG_DOMAIN_URL: "kong.kong.svc"
  DJANGO_ADMIN_DOMAIN_URL: "cwms-designer.ril.com"
  CANDIDATE_DOMAIN_URL: ""
  BACKEND_DOMAIN_URL: "http://cw-web.cw.svc"
  FILE_DOMAIN_URL: "cwms.ril.com"
  CW_BASE_URL: "http://cw-web.cw.svc"
  PLATFORM_BASE_URL: "http://kong.kong.svc"
  EZEDOX_ADMIN_USERNAME: "ezedox_admin@ezedox.com"
  EZEDOX_INTERNAL_EMAIL: "contact@ezedox.com"
  PROCESS_ENGINE_URL: "http://cw-rest.cw.svc/rest/"
  PROCESS_ENGINE_READ_REPLICA_URL: "http://cw-rest-replica.cw.svc/rest/"
  PROCESS_ENGINE_USER: "prasashak"
  PROCESS_IDM_URL: "https://cwms-designer.ril.com/ui/idm/"
  PROCESS_MODELER_URL: "https://cwms-designer.ril.com/ui/modeler/"
  RABBITMQ_HTTP_PORT: ""
  RABBITMQ_HTTP_USER_NAME: ""
  RABBITMQ_HTTP_USER_PASSWORD: ""
  CELERY_BROKER_URL: "redis://10.173.76.49:6380"
  BROKER_URL: "redis://10.173.76.49:6380"
  CHANNEL_LAYER_URL: "redis://10.173.76.49:6380"
  CELERY_RESULT_BACKEND: "redis://10.173.76.49:6380"
  REDIS_CACHE_URL: "redis://10.173.76.49:6380"
  CELERY_QUEUE_COUNT: "1" 
  REPORT_BATCH_SIZE: "300"
  DEADLETTERJOBS_EMAIL: ""
  SWAGGER_VIEW: "False"
  SENDER_EMAIL_ID: "no-reply@betterplace.co.in"
  COMMUNICATION_SERVICE_TOPIC: "prod-communication-send"
  DEFAULT_SCHEME: "http"
  ALLOWED_HOST_FOR_CW_HEADERS: "cwms-designer.ril.com,cwms-admin.ril.com,cw-web.cw.svc"
  KALEYRA_OTP_TEMPLATE_ID: ""
  SSL_VERIFICATION: "False"
  LOG_LEVEL: "INFO"