apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cw-cleanup-queue
  name: cw-cleanup-queue
  namespace: cw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cw-cleanup-queue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cw-cleanup-queue
    spec:
      imagePullSecrets:
        - name: cwms-jfrog 
      containers:
        - command: ["celery"]
          args: ["-A", "ezedox", "worker", "-Q", "process_instance_history_cleanup", "--concurrency", "8"]
          image: devopsartifact.jio.com/jpf-cwms__prod__dcr/cw-backend:#{Build.BuildId}#
          imagePullPolicy: Always          
          name: cw-cleanup-queue
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cw-prod-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: POSTGRES_USER
            - name: FLOWABLE_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: POSTGRES_HOST
            - name: FLOWABLE_POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: POSTGRES_PORT
            - name: FLOWABLE_POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: FLOWABLE_POSTGRES_DB
            - name: FLOWABLE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cw-prod-secret
                  key: POSTGRES_PASSWORD
            - name: FLOWABLE_POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: POSTGRES_USER
            - name: FILE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: FILE_BUCKET
            - name: AZURE_ACCOUNT_NAME
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: AZURE_ACCOUNT_NAME
            - name: AZURE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: cw-prod-secret
                  key: AZURE_ACCOUNT_KEY
            - name: AZURE_CONTAINER
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: AZURE_CONTAINER
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: KAFKA_BROKERS
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: cw-prod-secret
                  key: ENCRYPTION_KEY
            - name: SALT_FOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cw-prod-secret
                  key: SALT_FOR_PASSWORD
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cw-prod-secret
                  key: DJANGO_SECRET_KEY
            - name: TEMP_DIR
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: TEMP_DIR
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: ENV
            - name: PROD
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: PROD
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: DEBUG
            - name: LAUNCH_PROCESS_TOPICS
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: LAUNCH_PROCESS_TOPICS
            - name: BASE_ORG_DOMAIN_URL
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: BASE_ORG_DOMAIN_URL
            - name: DJANGO_ADMIN_DOMAIN_URL
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: DJANGO_ADMIN_DOMAIN_URL
            - name: CANDIDATE_DOMAIN_URL
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: CANDIDATE_DOMAIN_URL
            - name: BACKEND_DOMAIN_URL
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: BACKEND_DOMAIN_URL
            - name: FILE_DOMAIN_URL
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: FILE_DOMAIN_URL
            - name: CW_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: CW_BASE_URL
            - name: PLATFORM_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: PLATFORM_BASE_URL
            - name: PLATFORM_INTERNAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cw-prod-secret
                  key: PLATFORM_INTERNAL_TOKEN
            - name: INTEGRATION_INTERNAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cw-prod-secret
                  key: INTEGRATION_INTERNAL_TOKEN
            - name: EZEDOX_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cw-prod-secret
                  key: EZEDOX_ADMIN_PASSWORD
            - name: EZEDOX_ADMIN_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: EZEDOX_ADMIN_USERNAME
            - name: EZEDOX_INTERNAL_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: EZEDOX_INTERNAL_EMAIL
            - name: PROCESS_ENGINE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cw-prod-secret
                  key: PROCESS_ENGINE_PASSWORD
            - name: PROCESS_ENGINE_URL
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: PROCESS_ENGINE_URL
            - name: PROCESS_ENGINE_READ_REPLICA_URL
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: PROCESS_ENGINE_READ_REPLICA_URL
            - name: PROCESS_ENGINE_USER
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: PROCESS_ENGINE_USER
            - name: PROCESS_IDM_URL
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: PROCESS_IDM_URL
            - name: PROCESS_MODELER_URL
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: PROCESS_MODELER_URL
            - name: RABBITMQ_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: RABBITMQ_HTTP_PORT
            - name: RABBITMQ_HTTP_USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: RABBITMQ_HTTP_USER_NAME
            - name: RABBITMQ_HTTP_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cw-prod-secret
                  key: RABBITMQ_HTTP_USER_PASSWORD
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: cw-prod-secret
                  key: CELERY_BROKER_URL
            - name: BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: cw-prod-secret
                  key: BROKER_URL
            - name: CHANNEL_LAYER_URL
              valueFrom:
                secretKeyRef:
                  name: cw-prod-secret
                  key: CHANNEL_LAYER_URL
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: cw-prod-secret
                  key: CELERY_RESULT_BACKEND
            - name: REDIS_CACHE_URL
              valueFrom:
                secretKeyRef:
                  name: cw-prod-secret
                  key: REDIS_CACHE_URL
            - name: CELERY_QUEUE_COUNT
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: CELERY_QUEUE_COUNT
            - name: REPORT_BATCH_SIZE
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: REPORT_BATCH_SIZE
            - name: DEADLETTERJOBS_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: DEADLETTERJOBS_EMAIL
            - name: SWAGGER_VIEW
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: SWAGGER_VIEW
            - name: SENDER_EMAIL_ID
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: SENDER_EMAIL_ID
            - name: COMMUNICATION_SERVICE_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: COMMUNICATION_SERVICE_TOPIC
            - name: DEFAULT_SCHEME
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: DEFAULT_SCHEME
            - name: ALLOWED_HOST_FOR_CW_HEADERS
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: ALLOWED_HOST_FOR_CW_HEADERS
            - name: KALEYRA_OTP_TEMPLATE_ID
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: KALEYRA_OTP_TEMPLATE_ID
            - name: SSL_VERIFICATION
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: SSL_VERIFICATION
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: cw-prod-config
                  key: LOG_LEVEL
          resources:
            requests:
              cpu: 2000m
              memory: "3Gi"
            limits:
              cpu: 3000m
              memory: "4Gi"
      volumes:
        - name: tmp-files
          emptyDir: {}
      restartPolicy: Always