
#------------------------------------------------------------------------------------

app.config.kafka.producer.success-message = Message push successfully
app.config.kafka.producer.error-message = Message push failed

logging.level.root= INFO

server.port = 9091
spring.cloud.config.name=datasource
server.error.include-stacktrace=never


#SIT
#app.config.kafka.consumer.o2c.approval.data.topic.name=sit-domain-updates

#PROD
app.config.kafka.consumer.o2c.approval.data.topic.name=prod-domain-updates



# MongoDB connection settings
#spring.data.mongodb.uri=mongodb://prod-app-user:APPuo89I9MglUSER@10.173.76.67:27017,10.173.76.35:27017,10.173.76.15:27017
#spring.data.mongodb.database=prod-customer-mgmt-db




#------------------------------------------------------------------------------------