# Generated by Django 3.1.4 on 2022-06-27 12:44

import apps.org_form.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(max_length=2048, upload_to=apps.org_form.models.generate_path)),
                ('content_type', models.CharField(max_length=100)),
                ('file_label', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_type', models.CharField(blank=True, choices=[('TASK_RELATED_DOCUMENTS', 'TASK RELATED DOCUMENTS'), ('UPLOADED_DOCUMENTS', 'UPLOADED DOCUMENTS'), ('GENERATED_DOCUMENTS', 'GENERATED DOCUMENTS'), ('REPORTS', 'REPORTS')], max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('process_instance_id', models.UUIDField(blank=True, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('process_instance_id', models.UUIDField(blank=True, default=None, null=True)),
                ('data', models.JSONField(default=dict, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='TaggedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_form.organisationfile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_form_taggedfile_items', to='taggit.tag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organisationfile',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='org_form.TaggedFile', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='organisationfile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='organisationfile',
            name='transaction_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='org_form.transaction'),
        ),
        migrations.AddField(
            model_name='organisationfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrganisationForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('keytypepair', models.JSONField(default=dict, null=True)),
                ('content', models.JSONField(default=dict, null=True)),
                ('language_option', jsonfield.fields.JSONField(blank=True, default=dict, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
                'unique_together': {('key', 'version', 'tenant')},
            },
        ),
    ]
