# Generated by Django 3.1.4 on 2023-07-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_form', '0002_remove_taggedfile_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationfile',
            name='aws_bucket',
            field=models.CharField(default='dev-customer-mgmt', max_length=64),
        ),
    ]
