# Generated by Django 3.1.4 on 2023-07-31 05:41

import apps.org_form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_form', '0003_organisationfile_aws_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationfile',
            name='file_path',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='organisationfile',
            name='file',
            field=apps.org_form.models.DynamicStorageFileField(max_length=2048, upload_to=apps.org_form.models.generate_path),
        ),
    ]
