# Generated by Django 3.1.4 on 2023-08-22 08:53

from django.db import migrations, models
from ezedox.settings import FILE_BUCKET, AWS_STORAGE_BUCKET_NAME, AZURE_CONTAINER

def get_default_bucket():
    if FILE_BUCKET == 'S3':
        return AWS_STORAGE_BUCKET_NAME
    else:
        return AZURE_CONTAINER


class Migration(migrations.Migration):

    dependencies = [
        ('org_form', '0004_auto_20230731_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationfile',
            name='aws_bucket',
            field=models.CharField(default=get_default_bucket(), max_length=64),
        ),
    ]