# Generated by Django 3.1.4 on 2023-09-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_form', '0005_auto_20230822_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationform',
            name='is_bulk_supported',
            field=models.BooleanField(default=False),
        ),
    ]
