# Generated by Django 3.1.4 on 2025-07-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_form', '0006_organisationform_is_bulk_supported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='process_instance_id',
            field=models.UUIDField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
