/* eslint-disable import/no-extraneous-dependencies */
import Base from '@ezedoxbp/formiojs/components/base/Base';

export default class ProfessionalReferences extends Base {
    static schema() {
        return Base.schema({
            "validateOn": "change",
            "labelPosition": "top",
            "widget": null,
            "customConditional": "",
            "logic": [],
            "dataGridLabel": false,
            "label": "Panel",
            "labelMargin": 3,
            "tableView": false,
            "collapsed": false,
            "allowCalculateOverride": false,
            "alwaysEnabled": false,
            "components": [
                {
                    "addAnother": "",
                    "validateOn": "change",
                    "labelPosition": "top",
                    "groupToggle": false,
                    "enableRowGroups": false,
                    "logic": [],
                    "dataGridLabel": false,
                    "label": "Data Grid",
                    "labelMargin": 3,
                    "tableView": true,
                    "layoutFixed": false,
                    "allowCalculateOverride": false,
                    "alwaysEnabled": false,
                    "components": [
                        {
                            "validate": {
                                "required": false,
                                "customPrivate": false,
                                "custom": "",
                                "json": "",
                                "customMessage": ""
                            },
                            "properties": {},
                            "row": "0-0",
                            "label": "BGV Required",
                            "type": "checkbox",
                            "alwaysEnabled": false,
                            "tags": [],
                            "logic": [],
                            "key": "bgv_required",
                            "attributes": {},
                            "mask": false,
                            "reorder": false,
                            "defaultValue": false,
                            "shortcut": "",
                            "customConditional": "",
                            "tableView": true,
                            "encrypted": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "hideLabel": true,
                            "input": true
                        },
                        {
                            "validate": {
                                "minWords": "",
                                "required": true,
                                "customMessage": "",
                                "minLength": "",
                                "customPrivate": false,
                                "pattern": "",
                                "maxWords": "",
                                "maxLength": "",
                                "custom": "",
                                "json": ""
                            },
                            "properties": {},
                            "alwaysEnabled": false,
                            "row": "0-1",
                            "label": "Reference Name",
                            "allowMultipleMasks": false,
                            "widget": {
                                "minDate": "",
                                "hourIncrement": 1,
                                "defaultDate": null,
                                "format": "dd MMM yyyy",
                                "minuteIncrement": 5,
                                "enableDate": true,
                                "timezone": "",
                                "clickOpens": true,
                                "disableMobile": true,
                                "allowInput": true,
                                "language": "us-en",
                                "dateFormat": "dd MMM yyyy",
                                "enableTime": false,
                                "time_24hr": false,
                                "type": "",
                                "useLocaleSettings": false,
                                "maxDate": "",
                                "saveAs": "date",
                                "mode": "single",
                                "altInput": true,
                                "displayInTimezone": "",
                                "noCalendar": false
                            },
                            "type": "textfield",
                            "logic": [],
                            "key": "referenceProviderName",
                            "attributes": {},
                            "customConditional": "",
                            "reorder": false,
                            "inputFormat": "plain",
                            "showWordCount": false,
                            "showCharCount": false,
                            "tableView": true,
                            "encrypted": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "input": true,
                            "defaultValue": ""
                        },
                        {
                            "validate": {
                                "minWords": "",
                                "required": true,
                                "customMessage": "",
                                "minLength": "",
                                "customPrivate": false,
                                "pattern": "",
                                "maxWords": "",
                                "maxLength": "",
                                "custom": "",
                                "json": ""
                            },
                            "properties": {},
                            "row": "0-2",
                            "label": "Reference Email",
                            "alwaysEnabled": false,
                            "type": "email",
                            "logic": [],
                            "key": "referenceProviderEmail",
                            "attributes": {},
                            "reorder": false,
                            "defaultValue": "",
                            "customConditional": "",
                            "tableView": true,
                            "encrypted": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "input": true
                        },
                        {
                            "validate": {
                                "minWords": "",
                                "required": true,
                                "customMessage": "",
                                "minLength": "",
                                "customPrivate": false,
                                "pattern": "",
                                "maxWords": "",
                                "maxLength": "",
                                "custom": "",
                                "json": ""
                            },
                            "properties": {},
                            "alwaysEnabled": false,
                            "row": "0-3",
                            "label": "Organisation",
                            "allowMultipleMasks": false,
                            "widget": {
                                "minDate": "",
                                "hourIncrement": 1,
                                "defaultDate": null,
                                "format": "dd MMM yyyy",
                                "minuteIncrement": 5,
                                "enableDate": true,
                                "timezone": "",
                                "clickOpens": true,
                                "disableMobile": true,
                                "allowInput": true,
                                "language": "us-en",
                                "dateFormat": "dd MMM yyyy",
                                "enableTime": false,
                                "time_24hr": false,
                                "type": "",
                                "useLocaleSettings": false,
                                "maxDate": "",
                                "saveAs": "date",
                                "mode": "single",
                                "altInput": true,
                                "displayInTimezone": "",
                                "noCalendar": false
                            },
                            "type": "textfield",
                            "logic": [],
                            "key": "organisation",
                            "attributes": {},
                            "customConditional": "",
                            "reorder": false,
                            "inputFormat": "plain",
                            "showWordCount": false,
                            "showCharCount": false,
                            "tableView": true,
                            "encrypted": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "input": true,
                            "defaultValue": ""
                        },
                        {
                            "validate": {
                                "customPrivate": false,
                                "select": false,
                                "customMessage": "",
                                "required": true,
                                "custom": "",
                                "json": ""
                            },
                            "row": "0-4",
                            "mask": false,
                            "data": {
                                "resource": "",
                                "values": [
                                    {
                                        "value": "Academic",
                                        "label": "Academic"
                                    },
                                    {
                                        "value": "Professional",
                                        "label": "Professional"
                                    }
                                ],
                                "custom": "",
                                "json": "",
                                "url": ""
                            },
                            "customConditional": "",
                            "logic": [],
                            "disableLimit": false,
                            "label": "Reference Type",
                            "valueProperty": "value",
                            "reference": false,
                            "tableView": true,
                            "selectValues": "",
                            "lazyLoad": false,
                            "defaultValue": "",
                            "alwaysEnabled": false,
                            "sort": "",
                            "type": "select",
                            "properties": {},
                            "key": "referenceType",
                            "attributes": {},
                            "reorder": false,
                            "selectThreshold": 0.3,
                            "encrypted": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "input": true
                        },
                        {
                            "validate": {
                                "minWords": "",
                                "required": false,
                                "customMessage": "",
                                "minLength": "",
                                "customPrivate": false,
                                "pattern": "",
                                "maxWords": "",
                                "maxLength": "",
                                "custom": "",
                                "json": ""
                            },
                            "properties": {},
                            "row": "0-5",
                            "label": "Reference Phone Number",
                            "allowMultipleMasks": false,
                            "alwaysEnabled": false,
                            "type": "phoneNumber",
                            "logic": [],
                            "key": "referenceProviderPhoneNumber",
                            "attributes": {},
                            "inputMask": "99999 99999",
                            "reorder": false,
                            "inputFormat": "plain",
                            "showWordCount": false,
                            "showCharCount": false,
                            "tableView": true,
                            "encrypted": false,
                            "customConditional": "",
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "input": true,
                            "defaultValue": ""
                        },
                        {
                            "validate": {
                                "minWords": "",
                                "required": false,
                                "customMessage": "",
                                "minLength": "",
                                "customPrivate": false,
                                "pattern": "",
                                "maxWords": "",
                                "maxLength": "",
                                "custom": "",
                                "json": ""
                            },
                            "defaultValue": "",
                            "row": "0-6",
                            "tags": [],
                            "allowMultipleMasks": false,
                            "logic": [],
                            "label": "Designation",
                            "inputFormat": "plain",
                            "customConditional": "",
                            "tableView": true,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "showWordCount": false,
                            "attributes": {},
                            "widget": {
                                "minDate": "",
                                "hourIncrement": 1,
                                "defaultDate": null,
                                "format": "dd MMM yyyy",
                                "minuteIncrement": 5,
                                "enableDate": true,
                                "timezone": "",
                                "clickOpens": true,
                                "disableMobile": true,
                                "allowInput": true,
                                "language": "us-en",
                                "dateFormat": "dd MMM yyyy",
                                "enableTime": false,
                                "time_24hr": false,
                                "type": "",
                                "useLocaleSettings": false,
                                "maxDate": "",
                                "saveAs": "date",
                                "mode": "single",
                                "altInput": true,
                                "displayInTimezone": "",
                                "noCalendar": false
                            },
                            "type": "textfield",
                            "properties": {},
                            "key": "individualDesignation",
                            "alwaysEnabled": false,
                            "reorder": false,
                            "showCharCount": false,
                            "encrypted": false,
                            "input": true
                        },
                        {
                            "validate": {
                                "customPrivate": false,
                                "step": "any",
                                "integer": "",
                                "customMessage": "",
                                "required": false,
                                "custom": "",
                                "max": 9999,
                                "min": 1000,
                                "json": ""
                            },
                            "properties": {},
                            "row": "0-7",
                            "label": "Start Year Of Association",
                            "type": "number",
                            "requireDecimal": false,
                            "alwaysEnabled": false,
                            "tags": [],
                            "logic": [],
                            "key": "startYearOfAssociation",
                            "attributes": {},
                            "mask": false,
                            "reorder": false,
                            "delimiter": false,
                            "customConditional": "",
                            "tableView": true,
                            "encrypted": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "input": true
                        },
                        {
                            "validate": {
                                "customPrivate": false,
                                "step": "any",
                                "integer": "",
                                "customMessage": "",
                                "required": false,
                                "custom": "",
                                "max": 9999,
                                "min": 1000,
                                "json": ""
                            },
                            "properties": {},
                            "row": "0-8",
                            "label": "End Year Of Association",
                            "type": "number",
                            "requireDecimal": false,
                            "alwaysEnabled": false,
                            "tags": [],
                            "logic": [],
                            "key": "endYearOfAssociation",
                            "attributes": {},
                            "mask": false,
                            "reorder": false,
                            "delimiter": false,
                            "customConditional": "",
                            "tableView": true,
                            "encrypted": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "input": true
                        }
                    ],
                    "prefix": "",
                    "widget": null,
                    "tags": [],
                    "labelWidth": 30,
                    "autofocus": false,
                    "defaultValue": [
                        {
                            "referenceProviderName": "",
                            "referenceProviderEmail": "",
                            "organisation": "",
                            "referenceType": "",
                            "referenceProviderPhoneNumber": "",
                            "individualDesignation": "",
                            "startYearOfAssociation": 0,
                            "endYearOfAssociation": 0,
                            "bgv_required": false
                        }
                    ],
                    "mask": false,
                    "customConditional": "",
                    "refreshOn": "",
                    "errorLabel": "",
                    "calculateValue": "",
                    "hideLabel": true,
                    "input": true,
                    "multiple": false,
                    "suffix": "",
                    "validate": {
                        "customPrivate": false,
                        "customMessage": "",
                        "required": false,
                        "maxLength": 5,
                        "custom": "",
                        "json": ""
                    },
                    "placeholder": "",
                    "tree": true,
                    "defaultOpen": false,
                    "clearOnRefresh": false,
                    "id": "eqzw1pb",
                    "reorder": false,
                    "protected": false,
                    "showAddRowButton": true,
                    "hidden": false,
                    "customClass": "horizontal-scroll-data-grid",
                    "encrypted": false,
                    "persistent": true,
                    "unique": false,
                    "addAnotherPosition": "bottom",
                    "dbIndex": false,
                    "description": "",
                    "disableAddingRemovingRows": false,
                    "type": "datagrid",
                    "properties": {},
                    "disabled": false,
                    "key": "professionalReferences",
                    "attributes": {},
                    "tabindex": "",
                    "conditional": {
                        "when": "",
                        "show": "",
                        "json": "",
                        "eq": ""
                    },
                    "clearOnHide": true,
                    "customDefaultValue": "",
                    "removePlacement": "col",
                    "tooltip": ""
                }
            ],
            "prefix": "",
            "theme": "default",
            "tags": [],
            "labelWidth": 30,
            "autofocus": false,
            "defaultValue": null,
            "refreshOn": "",
            "errorLabel": "",
            "calculateValue": "",
            "hideLabel": false,
            "input": false,
            "multiple": false,
            "suffix": "",
            "validate": {
                "required": false,
                "customPrivate": false,
                "custom": ""
            },
            "tooltip": "",
            "placeholder": "",
            "mask": false,
            "clearOnRefresh": false,
            "id": "exsx9ff",
            "reorder": false,
            "protected": false,
            "hidden": false,
            "customClass": "",
            "lazyLoad": false,
            "conditional": {
                "when": "",
                "show": "",
                "json": "",
                "eq": ""
            },
            "persistent": false,
            "unique": false,
            "title": "Professional References",
            "dbIndex": false,
            "description": "",
            "type": "panel",
            "properties": {},
            "disabled": false,
            "key": "professionalReferencesPanel",
            "attributes": {},
            "tabindex": "",
            "customDefaultValue": "",
            "breadcrumb": "default",
            "collapsible": false,
            "clearOnHide": false
        });
    }

    static builderInfo = {
        title: 'Professional References',
        group: 'basic',
        icon: 'fa fa-sitemap',
        weight: 70,
        documentation: 'https://formio.github.io/formio.js/app/examples/customcomponent.html',
        schema: ProfessionalReferences.schema()
    }
}
