org_form_errors = {
    12001:["Failed to get Organisation Form data.", " User:{}, Error: {} "],
    12002:["Invaild Transaction ID", " User: {}, Failed to retrieve Organisation Form details. Error: {} "],
    12003:["Failed to retrieve Organisation Form details.", " User: {}, Error: {} "],
    12004:["Invaild Transaction ID", " User: {}, Failed to retrieve Organisation Form details. Error: {} "],
    12005:["Form cannot be opened at the moment", " User: {}, Failed to retrieve Organisation Form details. Error: {} "],
    12006:["Failed to retrieve Organisation Form details.", " User: {}, Error: {} "],
    12007:["Failed to create Organisation Form.", " User: {}, Error: {} "],
    12008:["Failed to create Organisation Form.", " User: {}, Error: {} "],
    12009:["ID not found", " User: {}, Failed to retrieve Organisation Form details for Id: {}, Error: {} "],
    12010:["Failed to retrieve Organisation Form details.", " User: {}, Id: {}, Error: {} "],
    12011:["ID not found.", " User: {}, Failed to update Organisation Form details for id : {}, Error: {} "],
    12012:["Failed to update Organisation Form.", " User: {}, Id: {}, Error: {} "],
    12013:["Failed to update Organisation Form details.", " User: {}, Id: {}, Error: {} "],
    12014:["ID not found.", " User: {}, Failed to delete Organisation Form for Id : {}, Error: {} "],
    12015:["Failed to delete Organisation Form.", " User: {}, Id: {}, Error: {} "],
    12016:["ID not found.", " User: {}, Failed to retrieve Organisation Form details for key : {},  Error: {} "],
    12017:["Failed to retrieve Organisation Form details.", " User: {}, Key: {}, Error: {} "],
    12018:["ID not found.", " Failed to retrieve File for id : {}, Error: {} "],
    12019:["Failed to retrieve File.", " Id: {}, Error: {} "],
    12020:["Missing Transaction id.", " Failed to Upload file. "],
    12021:["Invalid Transaction ID.", " Failed to Upload file. "],
    12022:["Unable to check the file in S3."],
    12023:["Failed to Upload file.", " Error: {} "],
    12024:["Missing Transaction id.", " Failed to Upload file. "],
    12025:["Invalid Transaction ID", " Failed to Upload file. "],
    12026:["Unable to check the file in S3."],
    12027:["Failed to upload File.", " Error: {} "],
    12028:["Failed to Upload file.", " Error: {} "],
    12029:["ID not found", " Failed to delete File for id : {}, Error: {} "],
    12030:["Failed to delete File.", " Id: {}, Error: {} "],
    12031:["ID not found", " Failed to update File for id : {}, Error: {} "],
    12032:["Failed to update File", " Id: {}, Error: 400_BAD_REQUEST "],
    12033:["Failed to update File", " User: {}, Error: {} "],
    12034:["Unable to check the file in S3."],
    12035:["Failed to upload File.", " Error: 400_BAD_REQUEST"],
    12036:["Failed to upload File.", " Error: {} "],
    12037:["ID not found", " Failed to update File for id : {}, Error: {} "],
    12038:["Failed to update File.", " Error: {} "],
    12039:["ID not found", " Failed to retrieve File for id : {}, Error: {} "],
    12040:["Failed to retrieve File.", " Id: {}, Error: {} "],
    12041:["process Instance Id or entity ID not passed"],
    12042:["Failed to get Files.", " User: {}, Error: {} "],
    12043:["ID not found", " User: {}, Failed to retrive File for id: {}, Error: {} "],
    12044:["Failed to retrieve File.", " User: {}, Id: {}, Error: {} "],
    12045:["Failed to generate hash", " for aadhaar. Error: {} "],
    12046:["ID not found", " User: {}, Failed to retrieve Transaction details for Id: {}, Error: {} "],
    12047:["Failed to retrieve Transaction details.", " User: {}, Id: {}, Error: {} "],
    12048:["Please provide relative_path in query params : {}"],
    12049:["Please provide bucket_name in query params : {}"],
    12050:["Failed to get presigned url by file path.", " Error: {} "],
}
