# Generated by Django 3.1.4 on 2022-06-27 12:44

import apps.org_jobs.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_department', '0001_initial'),
        ('organisations', '0001_initial'),
        ('org_entity', '0002_auto_20220627_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCountPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'HeadCountPlan',
                'verbose_name_plural': 'HeadCountPlans',
            },
        ),
        migrations.CreateModel(
            name='HeadCountPlanDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_count', models.IntegerField(default=0)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=100)),
                ('year', models.IntegerField(default=apps.org_jobs.models.get_current_year)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HiringEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('event_id', models.CharField(default=apps.org_jobs.models.get_event_id, max_length=25)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_date_to_apply', models.DateTimeField()),
                ('event_start_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField()),
                ('reporting_date', models.DateField()),
                ('reporting_time', models.TimeField()),
                ('interview_location', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Hiring Event',
                'verbose_name_plural': 'Hiring Events',
            },
        ),
        migrations.CreateModel(
            name='HiringState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=250)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('fixed_status', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('job_id', models.CharField(default=apps.org_jobs.models.get_job_id, max_length=25)),
                ('job_title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_positions', models.IntegerField(default=0)),
                ('available_positions', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Inactive', 'Inactive'), ('Achieved', 'Achieved')], default='Open', max_length=100)),
                ('target_date_to_finish_hiring', models.DateField()),
                ('expire_at_target_date', models.BooleanField(default=False)),
                ('IsResumeRequired', models.BooleanField(default=False)),
                ('MinSalary', models.IntegerField(default=0)),
                ('MaxSalary', models.IntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_department.department')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=250)),
                ('partner_type', models.CharField(choices=[('Inventory Supplier', 'Inventory Supplier'), ('Hiring Agency', 'Hiring Agency'), ('Franchise', 'Franchise')], max_length=100)),
                ('short_name', models.CharField(max_length=250)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.org_jobs.models.generate_logo_path)),
                ('address', models.CharField(blank=True, max_length=120)),
                ('cin', models.CharField(blank=True, max_length=100)),
                ('pan', models.CharField(blank=True, max_length=100)),
                ('gstn', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='HiringPartner',
            fields=[
                ('partner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='org_jobs.partner')),
                ('partner_subtype', models.CharField(choices=[('Sourcing', 'Sourcing'), ('Staffing', 'Staffing'), ('Sourcing and Staffing', 'Sourcing and Staffing')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('org_jobs.partner',),
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Job Role',
                'verbose_name_plural': 'Job Roles',
            },
        ),
        migrations.CreateModel(
            name='JobCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('candidateId', models.CharField(default=apps.org_jobs.models.get_candidate_id, max_length=25)),
                ('source', models.CharField(choices=[('Sourced', 'Sourced'), ('Referral', 'Referral'), ('Walkin', 'Walkin')], default='Sourced', max_length=100)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_entity.organisationentitymasterdata')),
                ('hiring_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org_jobs.hiringevent')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_jobs.job')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org_jobs.hiringstate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Job Candidate',
                'verbose_name_plural': 'Job Candidates',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_jobs.jobrole'),
        ),
        migrations.AddField(
            model_name='job',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
    ]
