# Generated by Django 3.1.4 on 2022-06-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_jobs', '0001_initial'),
        ('organisations', '0001_initial'),
        ('org_location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_location.location'),
        ),
        migrations.AddField(
            model_name='hiringstate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='hiringevent',
            name='job',
            field=models.ManyToManyField(to='org_jobs.Job'),
        ),
        migrations.AddField(
            model_name='hiringevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='headcountplandetail',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_jobs.headcountplan'),
        ),
        migrations.AddField(
            model_name='headcountplandetail',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='headcountplan',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_location.location'),
        ),
        migrations.AddField(
            model_name='headcountplan',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_jobs.jobrole'),
        ),
        migrations.AddField(
            model_name='headcountplan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together={('name', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='jobrole',
            unique_together={('name', 'tenant', 'slug')},
        ),
        migrations.AddField(
            model_name='jobcandidate',
            name='sourcing_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org_jobs.hiringpartner'),
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to='org_jobs.HiringPartner'),
        ),
        migrations.AlterUniqueTogether(
            name='hiringstate',
            unique_together={('name', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='hiringevent',
            unique_together={('event_id', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='headcountplan',
            unique_together={('role', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='jobcandidate',
            unique_together={('candidateId', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('job_id', 'tenant')},
        ),
    ]
