# Generated by Django 3.1.4 on 2022-07-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0002_auto_20220627_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='MaxSalary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='MinSalary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='target_date_to_finish_hiring',
            field=models.DateField(blank=True, null=True),
        ),
    ]
