# Generated by Django 3.1.4 on 2022-07-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0003_auto_20220704_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringstate',
            name='fixed_status',
        ),
        migrations.RemoveField(
            model_name='jobcandidate',
            name='status',
        ),
    ]
