# Generated by Django 3.1.4 on 2022-07-11 11:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org_location', '0002_auto_20220627_1244'),
        ('org_jobs', '0004_auto_20220706_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('alloted_slots', models.PositiveIntegerField(default=0)),
                ('booked_slots', models.PositiveIntegerField(default=0)),
                ('allow_overbooking', models.BooleanField(default=False)),
                ('channel', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('f2f', 'Face To Face')], max_length=100)),
                ('interview_location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='org_location.location')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_jobs.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateSlotMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_jobs.jobcandidate')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_jobs.slot')),
            ],
        ),
    ]
