# Generated by Django 3.1.4 on 2022-07-25 09:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org_location', '0003_auto_20220721_1431'),
        ('org_jobs', '0005_candidateslotmapping_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='job',
            name='available_positions',
        ),
        migrations.RemoveField(
            model_name='job',
            name='department',
        ),
        migrations.RemoveField(
            model_name='job',
            name='total_positions',
        ),
        migrations.RemoveField(
            model_name='job',
            name='work_location',
        ),
        migrations.AddField(
            model_name='job',
            name='candidate_preferences',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_payout',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='shift_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='team_members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='job',
            name='work_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='working_hours_end',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='working_hours_start',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Achieved', 'Achieved'), ('Draft', 'Draft'), ('Closed', 'Closed'), ('Sourcing Paused', 'Sourcing Paused'), ('Hiring Paused', 'Hiring Paused')], default='Open', max_length=100),
        ),
        migrations.CreateModel(
            name='VendorWorkLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_jobs.job')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_jobs.hiringpartner')),
                ('work_location', models.ManyToManyField(to='org_location.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('associated_to', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_jobs.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobWorkLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_positions', models.PositiveIntegerField(default=0)),
                ('filled_positions', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_jobs.job')),
                ('work_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_location.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
