# Generated by Django 3.1.4 on 2022-07-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0006_auto_20220725_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='states',
            field=models.ManyToManyField(blank=True, to='org_jobs.HiringState'),
        ),
    ]
