# Generated by Django 3.1.4 on 2022-07-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0007_auto_20220725_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobworklocation',
            name='job',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='job',
        ),
        migrations.RemoveField(
            model_name='vendorworklocation',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='job_work_location',
            field=models.ManyToManyField(to='org_jobs.JobWorkLocation'),
        ),
        migrations.AddField(
            model_name='job',
            name='stage',
            field=models.ManyToManyField(to='org_jobs.Stage'),
        ),
        migrations.AddField(
            model_name='job',
            name='vendor_work_location',
            field=models.ManyToManyField(to='org_jobs.VendorWorkLocation'),
        ),
    ]
