# Generated by Django 3.1.4 on 2022-07-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0008_auto_20220726_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_type',
            new_name='jobType',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='salary_payout',
            new_name='salaryPayout',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='shift_details',
            new_name='shiftDetails',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='team_members',
            new_name='teams',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='working_hours_end',
            new_name='workEndTime',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='working_hours_start',
            new_name='workStartTime',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Achieved', 'Achieved'), ('Draft', 'Draft'), ('Closed', 'Closed'), ('Sourcing Paused', 'Sourcing Paused'), ('Hiring Paused', 'Hiring Paused')], default='Active', max_length=100),
        ),
    ]
