# Generated by Django 3.1.4 on 2022-08-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0009_auto_20220726_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='spoc_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='vendorId',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
