# Generated by Django 3.1.4 on 2022-08-23 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_registry', '0003_defaultjobrole'),
        ('org_jobs', '0010_auto_20220803_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='default_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_registry.defaultjobrole'),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='platform_role_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
