# Generated by Django 3.1.4 on 2022-08-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0011_auto_20220823_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vendor_work_location',
            field=models.ManyToManyField(blank=True, to='org_jobs.VendorWorkLocation'),
        ),
    ]
