# Generated by Django 3.1.4 on 2022-10-21 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0012_auto_20220830_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('associated_to', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('states', models.ManyToManyField(blank=True, to='org_jobs.HiringState')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='job',
            name='filter_stage',
            field=models.ManyToManyField(to='org_jobs.FilterStage'),
        ),
    ]
