# Generated by Django 3.1.4 on 2022-10-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0013_auto_20221021_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringevent',
            name='event_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='jobcandidate',
            name='candidateId',
            field=models.CharField(max_length=25),
        ),
    ]
