# Generated by Django 3.1.4 on 2022-11-16 06:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0014_auto_20221031_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCandidateStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('stage_name', models.CharField(max_length=100)),
                ('stage_assignee', models.CharField(max_length=100)),
                ('stage_date', models.DateTimeField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_jobs.jobcandidate')),
            ],
            options={
                'verbose_name': 'Job Candidate Stage',
                'verbose_name_plural': 'Job Candidates Stage',
                'unique_together': {('candidate', 'stage_name')},
            },
        ),
    ]
