# Generated by Django 3.1.4 on 2022-11-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_users', '0004_remove_organisationuser_partner'),
        ('org_jobs', '0015_jobcandidatestage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorworklocation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorworklocation',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorworklocation',
            name='user_id',
            field=models.ManyToManyField(blank=True, to='org_users.OrganisationUser'),
        ),
    ]
