# Generated by Django 3.1.4 on 2022-11-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0016_auto_20221122_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorworklocation',
            name='is_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
