# Generated by Django 3.1.4 on 2022-12-07 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_location', '0005_update_location'),
        ('org_users', '0004_remove_organisationuser_partner'),
        ('org_jobs', '0017_vendorworklocation_is_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='spoc',
            field=models.ManyToManyField(default=None, to='org_users.OrganisationUser'),
        ),
        migrations.AddField(
            model_name='slot',
            name='work_location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_location', to='org_location.location'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='interview_location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interview_location', to='org_location.location'),
        ),
    ]
