# Generated by Django 3.1.4 on 2022-12-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0018_auto_20221207_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Draft', 'Draft'), ('Paused', 'Paused')], default='Active', max_length=100),
        ),
    ]
