# Generated by Django 3.1.4 on 2022-12-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_users', '0004_remove_organisationuser_partner'),
        ('org_jobs', '0019_auto_20221213_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='spoc',
            field=models.ManyToManyField(default=None, related_name='spoc', to='org_users.OrganisationUser'),
        ),
    ]
