# Generated by Django 3.1.4 on 2023-01-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0020_auto_20221216_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
