# Generated by Django 3.1.4 on 2023-01-07 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org_location', '0007_location_locality'),
        ('org_users', '0004_remove_organisationuser_partner'),
        ('org_jobs', '0021_auto_20230104_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorWorkLocality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_notification_sent', models.BooleanField(default=False)),
                ('locality', models.ManyToManyField(to='org_location.Location')),
                ('user_id', models.ManyToManyField(blank=True, to='org_users.OrganisationUser')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_jobs.hiringpartner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobWorkLocality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_positions', models.PositiveIntegerField(default=0)),
                ('filled_positions', models.PositiveIntegerField(default=0)),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_location.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
