# Generated by Django 3.1.4 on 2023-01-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0022_jobworklocality_vendorworklocality'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_work_locality',
            field=models.ManyToManyField(to='org_jobs.JobWorkLocality'),
        ),
    ]
