# Generated by Django 3.1.4 on 2023-01-17 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_users', '0004_remove_organisationuser_partner'),
        ('org_jobs', '0023_job_job_work_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_work_location',
            field=models.ManyToManyField(blank=True, to='org_jobs.JobWorkLocation'),
        ),
        migrations.RemoveField(
            model_name='slot',
            name='spoc',
        ),
        migrations.AddField(
            model_name='slot',
            name='spoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org_users.organisationuser'),
        ),
        migrations.DeleteModel(
            name='VendorWorkLocality',
        ),
    ]
