# Generated by Django 3.1.4 on 2023-01-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0024_auto_20230117_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringpartner',
            name='partner_subtype',
            field=models.CharField(choices=[('Sourcing', 'Sourcing'), ('Staffing', 'Staffing'), ('Sourcing and Staffing', 'Sourcing and Staffing')], default='Sourcing', max_length=100),
        ),
    ]
