# Generated by Django 3.1.4 on 2023-01-31 08:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0024_auto_20230117_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBoardFieldMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('job_board_id', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('job_obj_mapping', models.JSONField(blank=True, default=dict, null=True)),
                ('applicant_obj_mapping', models.JSONField(blank=True, default=dict, null=True)),
                ('status_mapping', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Job Board Fields Mapping',
                'verbose_name_plural': 'Job Boards Fields Mapping',
            },
        ),
        migrations.AddField(
            model_name='jobcandidate',
            name='job_board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='JobBoardMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('job_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Draft', 'Draft'), ('Paused', 'Paused')], default='Draft', max_length=100)),
                ('job_board_ref_id', models.CharField(max_length=100, unique=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_jobs.job')),
                ('job_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_jobs.jobboardfieldmapping')),
            ],
            options={
                'verbose_name': 'Job Board Mapping',
                'verbose_name_plural': 'Job Boards Mapping',
                'unique_together': {('job', 'job_board')},
            },
        ),
    ]
