# Generated by Django 3.1.4 on 2023-01-31 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0025_auto_20230131_0822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobBoardFieldMapping',
            new_name='JobBoard',
        ),
        migrations.AlterModelOptions(
            name='jobboard',
            options={'verbose_name': 'Job Board', 'verbose_name_plural': 'Job Boards'},
        ),
    ]
