# Generated by Django 3.1.4 on 2023-01-31 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0025_auto_20230130_1734'),
        ('org_jobs', '0026_auto_20230131_1045'),
    ]

    operations = [
    ]
