# Generated by Django 3.1.4 on 2023-02-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0027_merge_20230131_1148'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobboardmapping',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobboardmapping',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobboardmapping',
            name='job_board',
        ),
        migrations.DeleteModel(
            name='JobBoard',
        ),
        migrations.DeleteModel(
            name='JobBoardMapping',
        ),
    ]
