# Generated by Django 3.1.4 on 2023-02-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0028_auto_20230203_0641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcandidate',
            options={'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
        migrations.AddField(
            model_name='jobcandidate',
            name='applicationId',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='jobcandidate',
            name='candidateId',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
