# Generated by Django 3.1.4 on 2023-02-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisationlicense_default_package'),
        ('org_jobs', '0029_auto_20230207_0852'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobcandidate',
            unique_together={('applicationId', 'tenant')},
        ),
    ]
