# Generated by Django 3.1.4 on 2023-02-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0030_auto_20230208_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcandidate',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
