# Generated by Django 3.1.4 on 2024-05-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_jobs', '0031_jobcandidate_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateSlotMapping',
        ),
    ]
