import Base from "@ezedoxbp/formiojs/components/base/Base";

export default class AadhaarFile extends Base {
  static schema() {
    return Base.schema({
        "buttonSettings": {
            "cancel": true,
            "next": true,
            "previous": true
        },
        "placeholder": "",
        "allowCalculateOverride": false,
        "reorder": false,
        "logic": [],
        "alwaysEnabled": false,
        "labelWidth": 30,
        "validate": {
            "custom": "",
            "customPrivate": false,
            "required": false
        },
        "autofocus": false,
        "tableView": false,
        "id": "eakph8b",
        "suffix": "",
        "unique": false,
        "breadcrumb": "default",
        "tooltip": "",
        "disabled": false,
        "description": "",
        "dataGridLabel": false,
        "type": "panel",
        "labelPosition": "top",
        "lazyLoad": false,
        "key": "panel",
        "persistent": true,
        "widget": null,
        "calculateValue": "",
        "title": "Aadhaar",
        "collapsed": false,
        "conditional": {
            "show": "",
            "json": "",
            "eq": "",
            "when": ""
        },
        "hidden": false,
        "customConditional": "",
        "clearOnHide": true,
        "input": false,
        "breadcrumbClickable": true,
        "mask": false,
        "labelMargin": 3,
        "tabindex": "",
        "nextPage": "",
        "protected": false,
        "errorLabel": "",
        "attributes": {},
        "defaultValue": null,
        "clearOnRefresh": false,
        "properties": {},
        "multiple": false,
        "hideLabel": false,
        "refreshOn": "",
        "dbIndex": false,
        "label": "Panel",
        "collapsible": false,
        "customDefaultValue": "",
        "components": [
            {
                "placeholder": "",
                "allowCalculateOverride": false,
                "reorder": false,
                "logic": [],
                "alwaysEnabled": false,
                "labelWidth": 30,
                "validate": {
                    "custom": "",
                    "customPrivate": false,
                    "required": false
                },
                "autofocus": false,
                "tableView": false,
                "id": "er6a9a",
                "suffix": "",
                "unique": false,
                "tooltip": "",
                "disabled": false,
                "description": "",
                "persistent": false,
                "type": "columns",
                "labelPosition": "top",
                "hideOnChildrenHidden": false,
                "key": "columns3",
                "dataGridLabel": false,
                "widget": null,
                "calculateValue": "",
                "autoAdjust": false,
                "conditional": {
                    "show": "",
                    "json": "",
                    "eq": "",
                    "when": ""
                },
                "hidden": false,
                "customConditional": "",
                "clearOnHide": false,
                "input": false,
                "mask": false,
                "labelMargin": 3,
                "tabindex": "",
                "defaultValue": null,
                "protected": false,
                "errorLabel": "",
                "attributes": {},
                "clearOnRefresh": false,
                "properties": {},
                "multiple": false,
                "hideLabel": false,
                "columns": [
                    {
                        "push": 0,
                        "placeholder": "",
                        "allowCalculateOverride": false,
                        "key": "column",
                        "labelWidth": 30,
                        "validate": {
                            "custom": "",
                            "customPrivate": false,
                            "required": false
                        },
                        "autofocus": false,
                        "tableView": true,
                        "id": "eeb9sgs",
                        "suffix": "",
                        "unique": false,
                        "tooltip": "",
                        "disabled": false,
                        "description": "",
                        "dataGridLabel": false,
                        "type": "column",
                        "labelPosition": "top",
                        "clearOnRefresh": false,
                        "persistent": true,
                        "widget": null,
                        "calculateValue": "",
                        "width": 6,
                        "hidden": false,
                        "clearOnHide": true,
                        "input": false,
                        "conditional": {
                            "show": null,
                            "eq": "",
                            "when": null
                        },
                        "labelMargin": 3,
                        "tabindex": "",
                        "defaultValue": null,
                        "pull": 0,
                        "errorLabel": "",
                        "offset": 0,
                        "hideOnChildrenHidden": false,
                        "multiple": false,
                        "hideLabel": false,
                        "refreshOn": "",
                        "dbIndex": false,
                        "label": "Column",
                        "customDefaultValue": "",
                        "components": [
                            {
                                "url": "/api/forms/files?token=",
                                "placeholder": "",
                                "allowCalculateOverride": false,
                                "key": "aadhaarfrontside",
                                "logic": [],
                                "alwaysEnabled": false,
                                "privateDownload": false,
                                "uploadOnly": false,
                                "labelWidth": 30,
                                "validate": {
                                    "json": "",
                                    "custom": "",
                                    "customMessage": "",
                                    "customPrivate": false,
                                    "required": true
                                },
                                "autofocus": false,
                                "tableView": true,
                                "id": "e8k45na",
                                "image": false,
                                "suffix": "",
                                "unique": false,
                                "tooltip": "",
                                "disabled": true,
                                "description": "",
                                "dataGridLabel": false,
                                "type": "file",
                                "fileMaxSize": "1GB",
                                "labelPosition": "top",
                                "reorder": false,
                                "defaultOverlayWidth": 200,
                                "persistent": true,
                                "widget": null,
                                "calculateValue": "",
                                "fileMinSize": "0KB",
                                "fileTypes": [
                                    {
                                        "value": "",
                                        "label": ""
                                    }
                                ],
                                "conditional": {
                                    "show": "",
                                    "json": "",
                                    "eq": "",
                                    "when": ""
                                },
                                "hidden": false,
                                "customConditional": "",
                                "clearOnHide": true,
                                "input": true,
                                "mask": false,
                                "labelMargin": 3,
                                "tabindex": "",
                                "storage": "url",
                                "prefix": "",
                                "defaultOverlayHeight": 200,
                                "protected": false,
                                "errorLabel": "",
                                "attributes": {},
                                "dir": "",
                                "defaultValue": [],
                                "clearOnRefresh": false,
                                "properties": {},
                                "multiple": false,
                                "hideLabel": false,
                                "refreshOn": "",
                                "dbIndex": false,
                                "options": "",
                                "label": "Aadhaar - Front Side",
                                "customDefaultValue": "",
                                "filePattern": "*",
                                "fileNameTemplate": "",
                                "webcamSize": "",
                                "webcam": false,
                                "customClass": "",
                                "imageSize": "200",
                                "encrypted": false,
                                "tags": [],
                                "validateOn": "change"
                            },
                            {
                                "url": "",
                                "placeholder": "",
                                "allowCalculateOverride": false,
                                "key": "uploadAgain",
                                "logic": [],
                                "alwaysEnabled": false,
                                "leftIcon": "",
                                "labelWidth": 30,
                                "validate": {
                                    "json": "",
                                    "custom": "",
                                    "customMessage": "",
                                    "customPrivate": false,
                                    "required": false
                                },
                                "autofocus": false,
                                "tableView": true,
                                "id": "eeqpxg",
                                "suffix": "",
                                "unique": false,
                                "tooltip": "",
                                "disabled": false,
                                "description": "",
                                "dataGridLabel": true,
                                "type": "button",
                                "reorder": false,
                                "labelPosition": "top",
                                "clearOnRefresh": false,
                                "action": "event",
                                "persistent": false,
                                "widget": null,
                                "calculateValue": "",
                                "custom": "",
                                "conditional": {
                                    "show": "",
                                    "json": "",
                                    "eq": "",
                                    "when": ""
                                },
                                "disableOnInvalid": false,
                                "hidden": false,
                                "size": "md",
                                "customConditional": "show = data && data.aadhaar_button === \"0\"",
                                "clearOnHide": true,
                                "input": true,
                                "mask": false,
                                "labelMargin": 3,
                                "tabindex": "",
                                "defaultValue": false,
                                "protected": false,
                                "errorLabel": "",
                                "attributes": {},
                                "shortcut": "",
                                "showValidations": false,
                                "properties": {},
                                "multiple": false,
                                "hideLabel": false,
                                "refreshOn": "",
                                "dbIndex": false,
                                "label": "Upload Again",
                                "rightIcon": "",
                                "customDefaultValue": "",
                                "state": "interalUploadFileForOCR",
                                "block": false,
                                "event": "",
                                "customClass": "",
                                "prefix": "",
                                "encrypted": false,
                                "tags": [
                                    "aadhaarClear"
                                ],
                                "theme": "default",
                                "validateOn": "change"
                            },
                            {
                                "url": "",
                                "placeholder": "",
                                "allowCalculateOverride": false,
                                "key": "submit2",
                                "logic": [],
                                "alwaysEnabled": false,
                                "leftIcon": "",
                                "labelWidth": 30,
                                "validate": {
                                    "json": "",
                                    "custom": "",
                                    "customMessage": "",
                                    "customPrivate": false,
                                    "required": false
                                },
                                "autofocus": false,
                                "tableView": true,
                                "id": "e5oyzra",
                                "suffix": "",
                                "unique": false,
                                "tooltip": "",
                                "disabled": false,
                                "description": "",
                                "dataGridLabel": true,
                                "type": "button",
                                "reorder": false,
                                "labelPosition": "top",
                                "clearOnRefresh": false,
                                "action": "event",
                                "persistent": false,
                                "widget": null,
                                "calculateValue": "",
                                "custom": "",
                                "conditional": {
                                    "show": "",
                                    "json": "",
                                    "eq": "",
                                    "when": ""
                                },
                                "disableOnInvalid": false,
                                "hidden": false,
                                "size": "md",
                                "customConditional": "show = data && data.aadhaar_button !== \"0\"",
                                "clearOnHide": true,
                                "input": true,
                                "mask": false,
                                "labelMargin": 3,
                                "tabindex": "",
                                "defaultValue": false,
                                "protected": false,
                                "errorLabel": "",
                                "attributes": {},
                                "shortcut": "",
                                "showValidations": false,
                                "properties": {},
                                "multiple": false,
                                "hideLabel": false,
                                "refreshOn": "",
                                "dbIndex": false,
                                "label": "Upload Aadhaar",
                                "rightIcon": "",
                                "customDefaultValue": "",
                                "state": "",
                                "block": false,
                                "event": "interalUploadFileForOCR",
                                "customClass": "",
                                "prefix": "",
                                "encrypted": false,
                                "tags": [
                                    "aadhaar"
                                ],
                                "theme": "default",
                                "validateOn": "change"
                            },
                            {
                                "placeholder": "",
                                "allowCalculateOverride": false,
                                "reorder": false,
                                "logic": [],
                                "alwaysEnabled": false,
                                "suffix": "",
                                "inputMask": "",
                                "labelWidth": 30,
                                "validate": {
                                    "pattern": "",
                                    "json": "",
                                    "maxLength": "",
                                    "customPrivate": false,
                                    "minLength": "",
                                    "minWords": "",
                                    "maxWords": "",
                                    "custom": "",
                                    "customMessage": "",
                                    "required": false
                                },
                                "autofocus": false,
                                "tableView": true,
                                "id": "e01e74",
                                "inputType": "text",
                                "unique": false,
                                "tooltip": "",
                                "disabled": false,
                                "description": "",
                                "persistent": true,
                                "type": "textfield",
                                "labelPosition": "top",
                                "showWordCount": false,
                                "key": "aadhaarOcrData",
                                "dataGridLabel": false,
                                "widget": {
                                    "saveAs": "text",
                                    "type": "",
                                    "format": "yyyy-MM-dd hh:mm a",
                                    "dateFormat": "yyyy-MM-dd hh:mm a"
                                },
                                "calculateValue": "",
                                "conditional": {
                                    "show": "",
                                    "json": "",
                                    "eq": "",
                                    "when": ""
                                },
                                "hidden": true,
                                "customConditional": "",
                                "clearOnHide": false,
                                "input": true,
                                "mask": false,
                                "labelMargin": 3,
                                "tabindex": "",
                                "defaultValue": "",
                                "protected": false,
                                "errorLabel": "",
                                "attributes": {},
                                "showCharCount": false,
                                "clearOnRefresh": false,
                                "properties": {},
                                "multiple": false,
                                "hideLabel": false,
                                "refreshOn": "",
                                "dbIndex": false,
                                "allowMultipleMasks": false,
                                "label": "aadhaarOCRData",
                                "customDefaultValue": "",
                                "inputFormat": "plain",
                                "customClass": "",
                                "prefix": "",
                                "encrypted": false,
                                "validateOn": "change"
                            }
                        ],
                        "customClass": "",
                        "prefix": "",
                        "validateOn": "change",
                        "protected": false
                    },
                    {
                        "push": 0,
                        "placeholder": "",
                        "allowCalculateOverride": false,
                        "key": "column",
                        "labelWidth": 30,
                        "validate": {
                            "custom": "",
                            "customPrivate": false,
                            "required": false
                        },
                        "autofocus": false,
                        "tableView": true,
                        "id": "enxojp6",
                        "suffix": "",
                        "unique": false,
                        "tooltip": "",
                        "disabled": false,
                        "description": "",
                        "dataGridLabel": false,
                        "type": "column",
                        "labelPosition": "top",
                        "clearOnRefresh": false,
                        "persistent": true,
                        "widget": null,
                        "calculateValue": "",
                        "width": 6,
                        "hidden": false,
                        "clearOnHide": true,
                        "input": false,
                        "conditional": {
                            "show": null,
                            "eq": "",
                            "when": null
                        },
                        "labelMargin": 3,
                        "tabindex": "",
                        "defaultValue": null,
                        "pull": 0,
                        "errorLabel": "",
                        "offset": 0,
                        "hideOnChildrenHidden": false,
                        "multiple": false,
                        "hideLabel": false,
                        "refreshOn": "",
                        "dbIndex": false,
                        "label": "Column",
                        "customDefaultValue": "",
                        "components": [
                            {
                                "url": "/api/forms/files?token=",
                                "placeholder": "",
                                "allowCalculateOverride": false,
                                "key": "aadhaarcardback",
                                "logic": [],
                                "alwaysEnabled": false,
                                "privateDownload": false,
                                "uploadOnly": false,
                                "labelWidth": 30,
                                "validate": {
                                    "json": "",
                                    "custom": "",
                                    "customMessage": "",
                                    "customPrivate": false,
                                    "required": true
                                },
                                "autofocus": false,
                                "tableView": true,
                                "id": "eu0heuq",
                                "image": false,
                                "suffix": "",
                                "unique": false,
                                "tooltip": "",
                                "disabled": true,
                                "description": "",
                                "dataGridLabel": false,
                                "type": "file",
                                "fileMaxSize": "1GB",
                                "labelPosition": "top",
                                "reorder": false,
                                "defaultOverlayWidth": 200,
                                "persistent": true,
                                "widget": null,
                                "calculateValue": "",
                                "fileMinSize": "0KB",
                                "fileTypes": [
                                    {
                                        "value": "",
                                        "label": ""
                                    }
                                ],
                                "conditional": {
                                    "show": "",
                                    "json": "",
                                    "eq": "",
                                    "when": ""
                                },
                                "hidden": false,
                                "customConditional": "",
                                "clearOnHide": true,
                                "input": true,
                                "mask": false,
                                "labelMargin": 3,
                                "tabindex": "",
                                "storage": "url",
                                "prefix": "",
                                "defaultOverlayHeight": 200,
                                "protected": false,
                                "errorLabel": "",
                                "attributes": {},
                                "dir": "",
                                "defaultValue": [],
                                "clearOnRefresh": false,
                                "properties": {},
                                "multiple": false,
                                "hideLabel": false,
                                "refreshOn": "",
                                "dbIndex": false,
                                "options": "",
                                "label": "Aadhaar - Back Side",
                                "customDefaultValue": "",
                                "filePattern": "*",
                                "fileNameTemplate": "",
                                "webcamSize": "",
                                "webcam": false,
                                "customClass": "",
                                "imageSize": "200",
                                "encrypted": false,
                                "tags": [],
                                "validateOn": "change"
                            },
                            {
                                "placeholder": "",
                                "allowCalculateOverride": false,
                                "reorder": false,
                                "logic": [],
                                "alwaysEnabled": false,
                                "suffix": "",
                                "inputMask": "",
                                "labelWidth": 30,
                                "validate": {
                                    "pattern": "",
                                    "json": "",
                                    "maxLength": "",
                                    "customPrivate": false,
                                    "minLength": "",
                                    "minWords": "",
                                    "maxWords": "",
                                    "custom": "",
                                    "customMessage": "",
                                    "required": false
                                },
                                "autofocus": false,
                                "tableView": true,
                                "id": "eq9v4uh",
                                "inputType": "text",
                                "unique": false,
                                "tooltip": "",
                                "disabled": false,
                                "description": "",
                                "dataGridLabel": false,
                                "type": "textfield",
                                "labelPosition": "top",
                                "showWordCount": false,
                                "key": "aadhaar_button",
                                "persistent": true,
                                "widget": {
                                    "saveAs": "text",
                                    "type": "",
                                    "format": "yyyy-MM-dd hh:mm a",
                                    "dateFormat": "yyyy-MM-dd hh:mm a"
                                },
                                "calculateValue": "",
                                "conditional": {
                                    "show": "",
                                    "json": "",
                                    "eq": "",
                                    "when": ""
                                },
                                "hidden": true,
                                "customConditional": "",
                                "clearOnHide": false,
                                "input": true,
                                "mask": false,
                                "labelMargin": 3,
                                "tabindex": "",
                                "defaultValue": "",
                                "protected": false,
                                "errorLabel": "",
                                "attributes": {},
                                "showCharCount": false,
                                "clearOnRefresh": false,
                                "properties": {},
                                "multiple": false,
                                "hideLabel": false,
                                "refreshOn": "",
                                "dbIndex": false,
                                "allowMultipleMasks": false,
                                "label": "data",
                                "customDefaultValue": "",
                                "inputFormat": "plain",
                                "customClass": "",
                                "prefix": "",
                                "encrypted": false,
                                "tags": [],
                                "validateOn": "change"
                            }
                        ],
                        "customClass": "",
                        "prefix": "",
                        "validateOn": "change",
                        "protected": false
                    }
                ],
                "dbIndex": false,
                "label": "Columns",
                "customDefaultValue": "",
                "refreshOn": "",
                "customClass": "",
                "prefix": "",
                "validateOn": "change"
            }
        ],
        "customClass": "",
        "prefix": "",
        "theme": "default",
        "validateOn": "change"
    });
  }

  static builderInfo = {
    title: "Aadhaar File",
    group: "basic",
    icon: "fa fa-file",
    weight: 70,
    documentation:
      "https://formio.github.io/formio.js/app/examples/customcomponent.html",
    schema: AadhaarFile.schema()
  };
}
