# Generated by Django 3.1.4 on 2024-02-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['userId'], name='user_user_userid_5f6a77_idx'),
        ),
    ]
