apiVersion: v1
kind: ConfigMap
metadata:
  name: cw-sit-config
data:
  POSTGRES_HOST: "10.173.173.14"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "bp-ril-prod-cw-app-db"
  FLOWABLE_POSTGRES_DB: "bp-ril-prod-cw-process-db"
  POSTGRES_USER: "cwmssitadmin"
  FILE_BUCKET: "AZURE"
  AZURE_ACCOUNT_NAME: 'cwmssitprivate'
  AZURE_CONTAINER: 'cw-backend-sit'
  KAFKA_BROKERS: "10.173.173.22:9092,10.173.173.23:9092,10.173.173.24:9092"
  TEMP_DIR: "logs/"
  ENV: "sit"
  PROD: "False"
  DEBUG: "False"
  LAUNCH_PROCESS_TOPICS: "sit-domain-updates"
  BASE_ORG_DOMAIN_URL: "kong.default.svc"
  DJANGO_ADMIN_DOMAIN_URL: "cwms-sit-designer.ril.com"
  CANDIDATE_DOMAIN_URL: ""
  BACKEND_DOMAIN_URL: "http://cw-web.cw.svc"
  FILE_DOMAIN_URL: "cwms-sit.ril.com"
  CW_BASE_URL: "http://cw-web.cw.svc"
  PLATFORM_BASE_URL: "http://kong.default.svc"
  EZEDOX_ADMIN_USERNAME: "ezedox_admin@ezedox.com"
  EZEDOX_INTERNAL_EMAIL: "contact@ezedox.com"
  PROCESS_ENGINE_URL: "http://cw-rest.cw.svc/rest/"
  PROCESS_ENGINE_READ_REPLICA_URL: "http://cw-rest-replica.cw.svc/rest/"
  PROCESS_ENGINE_USER: "prasashak"
  PROCESS_IDM_URL: "http://cw-ui.cw.svc/ui/idm/"
  PROCESS_MODELER_URL: "http://cw-ui.cw.svc/ui/modeler/"
  RABBITMQ_HTTP_PORT: "15672"
  RABBITMQ_HTTP_USER_NAME: "monitor"
  CELERY_QUEUE_COUNT: "1"
  REPORT_BATCH_SIZE: "300"
  DEADLETTERJOBS_EMAIL: ""
  SWAGGER_VIEW: "False"
  SENDER_EMAIL_ID: "no-reply@betterplace.co.in"
  COMMUNICATION_SERVICE_TOPIC: "sit-communication-send"
  DEFAULT_SCHEME: "http"
  ALLOWED_HOST_FOR_CW_HEADERS: "cwms-sit-designer.ril.com,cwms-sit-admin.ril.com,cwms-designer.ril.com,cwms-admin.ril.com,cwms-sit-admin-api.ril.com,10.173.173.8,10.173.173.7:5000,cw-web.cw.svc"
  KALEYRA_OTP_TEMPLATE_ID: ""
  SSL_VERIFICATION: "False"
  LOG_LEVEL: "INFO"