apiVersion: v1
kind: Service
metadata:
  labels:
    app: cw-web
  name: cw-web
  namespace: cw
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 32761
  selector:
    app: cw-web