#spring.profiles.active = prod

# server properties
#------------------------------------------------------------------------------------
server.port = 8081
server.servlet.context-path = /onboard
server.error.include-binding-errors = NEVER
server.error.include-exception = FALSE
server.error.include-stacktrace = NEVER
server.error.include-message = NEVER
server.error.whitelabel.enabled = FALSE
spring.cloud.config.name=datasource
server.error.include-stacktrace=never
#------------------------------------------------------------------------------------


# logging properties
#------------------------------------------------------------------------------------
logging.file.name = logs/server.log
logging.level.org.apache.kafka = INFO
#------------------------------------------------------------------------------------

springdoc.swagger-ui.defaultModelsExpandDepth=-1


# base 64 to image temp storage
#------------------------------------------------------------------------------------
app.config.storage.blob-temp-storage = ./
#------------------------------------------------------------------------------------


# azure properties-SIT
#------------------------------------------------------------------------------------
#app.config.azure.default-endpoint-protocol = https
#app.config.azure.account-name = cwmssitprivate
#app.config.azure.account-key = EgNu7iXEchSj5w80xGoi11uNW+FRRK6BDlqGGe4GMNRNrvjLNL2YEBVxEu4pV+zilDbGuJjqfACA+AStNBTJfA==
#app.config.azure.endpoint-suffix = core.windows.net
#app.config.azure.blob-container-name = sit-customer-mgmt/employee_profile_pictures
#app.config.azure.blob-url-path = sit-customer-mgmt/file/download/employee_profile_pictures
#------------------------------------------------------------------------------------

# azure properties-PROD
#------------------------------------------------------------------------------------
app.config.azure.default-endpoint-protocol = https
app.config.azure.account-name = cwmsprdprivate
app.config.azure.account-key = hEy1iOXy5ZVMyauPpQdez17S/EcRlKsnG64UNEz0Iq8/jvvSASdK2cOCDvvNfyGctBEVT/7A/L1U+AStodhnlw
app.config.azure.endpoint-suffix = core.windows.net
app.config.azure.blob-container-name = prod-customer-mgmt/employee_profile_pictures
app.config.azure.blob-url-path = prod-customer-mgmt/file/download/
