<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
	xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
	xmlns:tns="http://tempuri.org/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	targetNamespace="http://tempuri.org/" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">


	<xs:element name="GetToken">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" name="Username"
					type="xs:string" />
				<xs:element minOccurs="0" maxOccurs="1"
					name="Password" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	
	<xs:element name="GetTokenResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" name="Token"
					type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="clientId" type="xs:string"/>
	
	<xs:element name="GetPositionCount">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="1" name="token"
					type="xs:string" />
				<xs:element minOccurs="1" maxOccurs="1" name="typecode"
					type="xs:string" />
				<xs:element minOccurs="0" maxOccurs="1" name="SAPRoleCode" 
					type="xs:string" />
				<xs:element minOccurs="0" maxOccurs="1" name="ShortCode"
					type="xs:string" />
				<xs:element minOccurs="0" maxOccurs="1" name="PaginationDetails">
					<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" maxOccurs="1" name="pageSize" type="xs:int"/>
						<xs:element minOccurs="0" maxOccurs="1" name="pageNumber" type="xs:int"/>
					</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="1" name="filters">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="1" name="startDate" type="xs:string"/>
							<xs:element minOccurs="0" maxOccurs="1" name="endDate" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="GetPositionCountResponse"  xmlns="http://tempuri.org/">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1"
					name="GetPositionCountResult" type="xs:normalizedString" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="GetCandidateStatus">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="1" name="token"
					type="xs:string" />
				<xs:element minOccurs="1" maxOccurs="1"
					name="CandidateID" type="xs:int" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="GetCandidateStatusResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1"
					name="GetCandidateStatusResult" type="tns:ArrayOfString" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="ArrayOfString">
		<xs:sequence>
			<xs:element name="string" minOccurs="0" nillable="true"
				maxOccurs="unbounded" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="ProcessCandidate">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="1" name="token"
					type="xs:string" />
				<xs:element minOccurs="0" maxOccurs="1" name="canDetails"
					type="tns:CandidateDetails" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="CandidateDetails">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="firstName"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="lastName"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="DateOfBirth"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="phoneNo"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="EmailId"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="IDProfNo"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="middleName"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1"
				name="localAddress" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1"
				name="permanentAddress" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="LPin"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="PPin"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="Gender"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="CTC"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="CandiateID"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="SAPCode"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="JCCode"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="Designation"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="HM_ECCNO"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="HM_Name"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="HM_EmailId"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1"
				name="OnBoard_Email" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1"
				name="OnBoard_EC_NO" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1"
				name="OnBoard_Domain" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="Bank_Name"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1"
				name="Account_Number" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="IFSC_CODE"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="PAN"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1"
				name="Expected_DOJ" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1"
				name="Education_Level" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="FatherName"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="PositionCode"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="NameAsPerAadhar"
				type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="ProcessCandidateResult">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1"
					name="ProcessCandidateResult" type="tns:ArrayOfString" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="getDetails">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="1" name="token"
					type="xs:string" />
				<xs:element minOccurs="1" maxOccurs="1" name="id"
					type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="getScrumDetails">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" name="id"
					type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="getDetailsResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1"
					name="getDetailsResult" type="tns:ArrayOfString" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="GetCandidateDetails">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="id"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="Name"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="Role"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="Agency"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="PlannedDOJ"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="Status"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1"
				name="ReportingLocation" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="Designation"
				type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="ActualDOJ"
				type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="updateDOJ">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="1" name="token"
					type="xs:string" />
				<xs:element minOccurs="1" maxOccurs="1" name="id"
					type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="updateDOJResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1"
					name="updateDOJResult" type="tns:ArrayOfString" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="updatePhoto">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="1" name="token"
					type="xs:string" />
				<xs:element minOccurs="1" maxOccurs="1" name="id"
					type="xs:string" />
				<xs:element minOccurs="0" maxOccurs="1" name="photo"
					type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="updatePhotoResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1"
					name="updatePhotoResult" type="tns:ArrayOfString" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>


</xs:schema>