proxy_bpm_errors = {
    1001 : ["Failed to get list of Task.", " User: {} "],
    1002 : ["Failed to get list of Task.", " User: {}, due to Exception: {} "],
    1003 : ["Failed to get list of Task.", " Group Task, User: {} "],
    1004 : ["Failed to get list of Task.", " Group Task, User: {} due to Exception: {} "],
    1005 : ["Failed to get list of Task.", " run time task instance, User: {} "],
    1006 : ["Failed to get list of Task.", " run time task instance, User: {} due to Exception: {} "],
    1007 : ["Failed to get list of Task.", " history task instance, User: {} "],
    1008 : ["Failed to get list of Task.", " history task instance, User: {} due to Exception: {} "],
    1009 : ["failed to update user data of process identitylinks, processinstanceId:{} "],
    1010 : ["Failed to send in app notification for task reassign"],
    1011 : ["Failed to reassign Task", " User: {}, due to Exception:{} "],
    1012 : ["Failed to send in app notification for task submission"],
    1013 : ["Failed to complete Task.", " User: {} "],
    1014 : ["Failed to complete Task.", " User: {} Exception: {} "],
    1015 : ["Failed to get list of Task.", " Runtime Process Instance, User: {} "],
    1016 : ["Failed to get list of Task.", " Runtime Process Instance, User: {} due to Exception: {} "],
    1017 : ["Failed to get list of Process Instance.", " History Process Instance,  User: {} "],
    1018 : ["Failed to get list of Process Instance.", " History Process Instance,  User: {} due to Exception: {} "],
    1019 : ["Failed to Withdrawn Process."],
    1020 : ["Failed to Withdrawn Process.", ", due to Exception: {} "],
    1021 : ["Failed to get Query in process instance List.", " User: {} "],
    1022 : ["Failed to get Query in process instance List.",  " User: {}, due to Exception: {} "],
    1023 : ["Failed to get list of Process Instance.", " User: {}"],
    1024 : ["Failed to get list of Process Instance.", " User: {}, due to Exception: {} "],
    1025 : ["Failed to delete process."],
    1026 : ["Failed to delete process.", " due to Exception: {} "],
    1027 : ["Failed to get Task identity.", " User: {} "],
    1028 : ["Failed to get Task identity.", " User: {}, due to Exception: {} "],
    1029 : ["Failed to update task variables.", " User: {}, due to Exception: {} "],
    1030 : ["Failed to get Audit Log of Process instance. Due to error: {}"],
    1031 : ["Failed to get Audit Log of Process instance.", " User: {} "],
    1032 : ["Failed to get Audit Log of Process instance.", " User: {}, due to Exception: {} "],
    1033 : ["Failed to Perform Operation."],
    1034 : ["Failed to Perform Operation.", " Due to Exception: {} "],
    1035 : ["Open Form not found.", " Open Workflow - Failed to retrieve Organisation Form details of id : {}, due to: {} "],
    1036 : ["Failed to retrieve Organisation Form details.", " Open Workflow - Failed to retrieve Organisation Form details of id : {}, due to Exception: {} "],
    1037 : ["Open Form not found.", " Open Workflow - Failed to start for Form id : {}, due to: {}"],
    1038 : ["Failed to start process.", " Launch of open Workflow with form id: {} Failed, due to Exception:{} "],
    1039 : ["Failed to reassign Task."],
    1040 : ['Task was already claimed']
    }
