# Generated by Django 3.1.4 on 2022-06-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_users', '0001_initial'),
        ('org_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationgroup',
            name='users',
            field=models.ManyToManyField(to='org_users.OrganisationUser'),
        ),
        migrations.AlterUniqueTogether(
            name='organisationgroup',
            unique_together={('name', 'tenant')},
        ),
    ]
