# Generated by Django 3.1.4 on 2025-04-04 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_group', '0002_auto_20220627_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationgroup',
            name='name',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+[,0-9a-zA-Z_\\-\\s]*[0-9a-zA-Z]$', 'Special Characters are not allowed except Comma, Underscore, Hyphen and the name can not start and end with any special character or space.')]),
        ),
    ]
