# Generated by Django 3.1.4 on 2025-07-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_group', '0004_auto_20250506_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationgroup',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
    ]
