# Generated by Django 3.1.4 on 2025-05-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_group', '0003_auto_20250404_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationgroup',
            name='key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='organisationgroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
