# Generated by Django 3.1.4 on 2025-10-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_organisationlicense_processengine_read_replica'),
        ('org_group', '0003_auto_20250729_0654'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organisationgroup',
            unique_together={('name', 'key', 'tenant')},
        ),
    ]
