# Generated by Django 3.1.4 on 2022-06-27 12:44

import apps.org_entity.models
import collections
import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationEntityAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=255)),
                ('assignee', models.CharField(max_length=255, null=True)),
                ('end_time', models.DateTimeField()),
                ('event', models.CharField(blank=True, choices=[('created', 'Task Created'), ('document_added', 'Document Uploaded'), ('document_deleted', 'Document Uploaded'), ('subscriber_added', 'Subscriber Added'), ('subscriber_removed', 'Subscriber Removed'), ('comment_added', 'Commented'), ('assign', 'Assigned'), ('sign', 'Signed'), ('approve', 'Approved'), ('onhold', 'On Hold'), ('inprogress', 'In Progress'), ('reject', 'Rejected'), ('resolve', 'Resolved')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Entity Audit Log',
                'verbose_name_plural': 'Entity Audit Logs',
            },
        ),
        migrations.CreateModel(
            name='OrganisationEntityMasterData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entity_data', models.JSONField(default=dict, null=True)),
                ('entity_name', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('entity_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default=None, max_length=128, null=True, region=None, verbose_name='Mobile Number')),
                ('entity_email', models.EmailField(blank=True, db_index=True, default=None, max_length=254, null=True)),
                ('entity_photo', models.JSONField(blank=True, default=dict, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('pan', models.CharField(blank=True, max_length=255)),
                ('pan_url', models.JSONField(default=dict, null=True)),
                ('name_on_pan_card', models.CharField(blank=True, max_length=255, null=True)),
                ('pan_verified', models.BooleanField(default=False)),
                ('aadhaar', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhaar_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhaar_last_digits', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhaar_verified', models.BooleanField(default=False)),
                ('aadhaar_check_ID', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('work_location', models.CharField(blank=True, max_length=255, null=True)),
                ('present_address_line', models.CharField(blank=True, max_length=255, null=True)),
                ('present_address_city', models.CharField(blank=True, max_length=255, null=True)),
                ('present_address_district', models.CharField(blank=True, max_length=255, null=True)),
                ('present_address_state', models.CharField(blank=True, max_length=255, null=True)),
                ('present_address_locality', models.CharField(blank=True, max_length=255, null=True)),
                ('present_address_landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('present_address_pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('present_address_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('permanent_address_line', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address_city', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address_district', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address_state', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address_verified', models.BooleanField(default=False)),
                ('permanent_address_locality', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address_landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address_pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_type', models.CharField(blank=True, choices=[('Candidate', 'Candidate'), ('Employee', 'Employee'), ('Exemployee', 'Exemployee')], max_length=50, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=255)),
                ('bank_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('Interviewed', 'Interviewed'), ('Offered', 'Offered'), ('Accepted', 'Accepted'), ('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50, null=True)),
                ('in_payroll', models.BooleanField(default=False)),
                ('Height', models.CharField(blank=True, max_length=50, null=True)),
                ('Weight', models.CharField(blank=True, max_length=50, null=True)),
                ('Bloodgroup', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('employment_status', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], max_length=50, null=True)),
                ('partner_profile_id', models.IntegerField(blank=True, null=True)),
                ('voterid', models.CharField(blank=True, max_length=255)),
                ('vidUrl', models.JSONField(blank=True, default=dict, null=True)),
                ('name_on_voter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('drivingLicense', models.CharField(blank=True, max_length=255)),
                ('dlUrl', models.JSONField(blank=True, default=dict, null=True)),
                ('name_on_dl', models.CharField(blank=True, max_length=255, null=True)),
                ('blacklist_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Organisation Entity Master Data',
                'verbose_name_plural': 'Organisation Entity Master Data',
            },
        ),
        migrations.CreateModel(
            name='OrganisationEntityMasterModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('key', models.SlugField(max_length=255)),
                ('search_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None)),
                ('keyvaluepair', models.JSONField(default=collections.OrderedDict, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('model_type', models.CharField(blank=True, choices=[('master_data', 'MASTER DATA'), ('entities', 'ENTITY')], max_length=50, null=True)),
                ('unique_field', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=list, size=None)),
                ('transform_json', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Organisation Entity Master Model',
                'verbose_name_plural': 'Organisation Entity Master Models',
            },
        ),
        migrations.CreateModel(
            name='OrganisationEntityView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('view_filter', models.CharField(blank=True, max_length=256, null=True)),
                ('config_view', models.JSONField(blank=True, default=apps.org_entity.models.config_default_value, null=True)),
                ('selected_entity_forms', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name': 'Organisation Entity View',
                'verbose_name_plural': 'Organisation Entity Views',
            },
        ),
    ]
