# Generated by Django 3.1.4 on 2022-06-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_entity', '0001_initial'),
        ('org_apps', '0002_auto_20220627_1244'),
        ('org_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationentityview',
            name='entity_forms',
            field=models.ManyToManyField(blank=True, default=None, to='org_form.OrganisationForm'),
        ),
        migrations.AddField(
            model_name='organisationentityview',
            name='entity_master_model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entity_view', to='org_entity.organisationentitymastermodel'),
        ),
        migrations.AddField(
            model_name='organisationentityview',
            name='entity_workflows',
            field=models.ManyToManyField(blank=True, default=None, to='org_apps.OrganisationWorkflow'),
        ),
    ]
