# Generated by Django 3.1.4 on 2022-06-27 12:44

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_users', '0001_initial'),
        ('organisations', '0001_initial'),
        ('org_entity', '0002_auto_20220627_1244'),
        ('org_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationentityview',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='org_users.role'),
        ),
        migrations.AddField(
            model_name='organisationentityview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='organisationentitymastermodel',
            name='entity_forms',
            field=models.ManyToManyField(blank=True, default=None, to='org_form.OrganisationForm'),
        ),
        migrations.AddField(
            model_name='organisationentitymastermodel',
            name='entity_views',
            field=models.ManyToManyField(blank=True, default=None, to='org_entity.OrganisationEntityView'),
        ),
        migrations.AddField(
            model_name='organisationentitymastermodel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='organisationentitymasterdata',
            name='entity_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_entity.organisationentitymastermodel'),
        ),
        migrations.AddField(
            model_name='organisationentityauditlog',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_entity.organisationentitymasterdata'),
        ),
        migrations.AddField(
            model_name='organisationentityauditlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='organisationentityview',
            unique_together={('entity_master_model', 'role', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='organisationentitymastermodel',
            unique_together={('key', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='organisationentitymasterdata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['entity_data'], name='org_entity__entity__4fd80a_gin'),
        ),
    ]
