# Generated by Django 3.1.4 on 2022-07-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('org_entity', '0003_auto_20220627_1244'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organisationentityview',
            unique_together={('entity_master_model', 'tenant')},
        ),
        migrations.RemoveField(
            model_name='organisationentityview',
            name='role',
        ),
    ]
