# Generated by Django 3.1.4 on 2022-10-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_entity', '0004_auto_20220714_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisationentitymasterdata',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='organisationentitymasterdata',
            old_name='employee_code',
            new_name='employeeId',
        ),
        migrations.RenameField(
            model_name='organisationentitymasterdata',
            old_name='date_of_joining',
            new_name='joiningDate',
        ),
        migrations.AddField(
            model_name='organisationentitymasterdata',
            name='bpss_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organisationentitymasterdata',
            name='defaultLocation',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organisationentitymasterdata',
            name='defaultRole',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organisationentitymasterdata',
            name='employeeType',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organisationentitymasterdata',
            name='entityType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organisationentitymasterdata',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organisationentitymastermodel',
            name='platform_schema',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='organisationentitymasterdata',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
