# Generated by Django 3.1.4 on 2023-02-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_entity', '0005_auto_20221014_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationentitymasterdata',
            name='candidateId',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
