# Generated by Django 3.1.4 on 2023-02-09 17:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisationlicense_default_package'),
        ('org_entity', '0006_organisationentitymasterdata_candidateid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateHistoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('activity_type', models.CharField(blank=True, choices=[('Application created', 'Application created'), ('Edited', 'Edited'), ('Added', 'Added')], max_length=100, null=True)),
                ('owner', models.CharField(max_length=255, null=True)),
                ('job_id', models.CharField(default=None, max_length=100)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_entity.organisationentitymasterdata')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Candidate Audit Log',
                'verbose_name_plural': 'Candidate Audit Logs',
            },
        ),
    ]
