# Generated by Django 3.1.4 on 2023-02-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_entity', '0007_candidatehistorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatehistorymodel',
            name='job_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
