/* eslint-disable import/no-extraneous-dependencies */
import Base from '@ezedoxbp/formiojs/components/base/Base';

export default class EmploymentRecords extends Base {
    static schema() {
        return Base.schema({
            "validateOn": "change",
            "labelPosition": "top",
            "widget": null,
            "customConditional": "",
            "logic": [],
            "dataGridLabel": false,
            "label": "Panel",
            "labelMargin": 3,
            "tableView": false,
            "collapsed": false,
            "allowCalculateOverride": false,
            "alwaysEnabled": false,
            "components": [
                {
                    "addAnother": "",
                    "validateOn": "change",
                    "labelPosition": "top",
                    "groupToggle": false,
                    "enableRowGroups": false,
                    "logic": [],
                    "dataGridLabel": false,
                    "label": "Data Grid",
                    "labelMargin": 3,
                    "tableView": true,
                    "layoutFixed": false,
                    "allowCalculateOverride": false,
                    "alwaysEnabled": false,
                    "components": [
                        {
                            "validate": {
                                "required": false,
                                "customPrivate": false,
                                "custom": "",
                                "json": "",
                                "customMessage": ""
                            },
                            "properties": {},
                            "row": "0-0",
                            "label": "BGV Required",
                            "type": "checkbox",
                            "alwaysEnabled": false,
                            "tags": [],
                            "logic": [],
                            "key": "bgv_required",
                            "attributes": {},
                            "mask": false,
                            "reorder": false,
                            "defaultValue": false,
                            "shortcut": "",
                            "customConditional": "",
                            "tableView": true,
                            "encrypted": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "hideLabel": true,
                            "input": true
                        },
                        {
                            "validate": {
                                "required": false,
                                "customPrivate": false,
                                "custom": "",
                                "json": "",
                                "customMessage": ""
                            },
                            "defaultValue": [],
                            "row": "0-1",
                            "mask": false,
                            "type": "file",
                            "logic": [],
                            "fileTypes": [
                                {
                                    "value": "",
                                    "label": ""
                                }
                            ],
                            "url": "/api/forms/files?token=",
                            "options": "",
                            "webcamSize": "",
                            "reorder": false,
                            "dir": "",
                            "customConditional": "",
                            "tableView": true,
                            "webcam": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "fileMaxSize": "10MB",
                            "storage": "url",
                            "alwaysEnabled": false,
                            "tags": [],
                            "properties": {},
                            "key": "salaryslip",
                            "attributes": {},
                            "label": "Salary Slip",
                            "fileNameTemplate": "",
                            "encrypted": false,
                            "input": true
                        },
                        {
                            "validate": {
                                "required": false,
                                "customPrivate": false,
                                "custom": "",
                                "json": "",
                                "customMessage": ""
                            },
                            "defaultValue": [],
                            "row": "0-2",
                            "mask": false,
                            "type": "file",
                            "logic": [],
                            "fileTypes": [
                                {
                                    "value": "",
                                    "label": ""
                                }
                            ],
                            "url": "/api/forms/files?token=",
                            "options": "",
                            "webcamSize": "",
                            "reorder": false,
                            "dir": "",
                            "customConditional": "",
                            "tableView": true,
                            "webcam": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "fileMaxSize": "10MB",
                            "storage": "url",
                            "alwaysEnabled": false,
                            "tags": [],
                            "properties": {},
                            "key": "appointmentletter",
                            "attributes": {},
                            "label": "Appointment Letter",
                            "fileNameTemplate": "",
                            "encrypted": false,
                            "input": true
                        },
                        {
                            "validate": {
                                "required": false,
                                "customPrivate": false,
                                "custom": "",
                                "json": "",
                                "customMessage": ""
                            },
                            "defaultValue": [],
                            "row": "0-3",
                            "mask": false,
                            "type": "file",
                            "logic": [],
                            "fileTypes": [
                                {
                                    "value": "",
                                    "label": ""
                                }
                            ],
                            "url": "/api/forms/files?token=",
                            "options": "",
                            "webcamSize": "",
                            "reorder": false,
                            "dir": "",
                            "customConditional": "",
                            "tableView": true,
                            "webcam": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "fileMaxSize": "10MB",
                            "storage": "url",
                            "alwaysEnabled": false,
                            "tags": [],
                            "properties": {},
                            "key": "experienceletter",
                            "attributes": {},
                            "label": "Experience Letter",
                            "fileNameTemplate": "",
                            "encrypted": false,
                            "input": true
                        },
                        {
                            "validate": {
                                "minWords": "",
                                "required": true,
                                "customMessage": "",
                                "minLength": "",
                                "customPrivate": false,
                                "pattern": "",
                                "maxWords": "",
                                "maxLength": "",
                                "custom": "",
                                "json": ""
                            },
                            "defaultValue": "",
                            "row": "0-4",
                            "tags": [],
                            "allowMultipleMasks": false,
                            "logic": [],
                            "label": "Name on Employment Document",
                            "inputFormat": "plain",
                            "customConditional": "",
                            "tableView": true,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "showWordCount": false,
                            "attributes": {},
                            "widget": {
                                "minDate": "",
                                "hourIncrement": 1,
                                "defaultDate": null,
                                "format": "dd MMM yyyy",
                                "minuteIncrement": 5,
                                "enableDate": true,
                                "timezone": "",
                                "clickOpens": true,
                                "disableMobile": true,
                                "allowInput": true,
                                "language": "us-en",
                                "dateFormat": "dd MMM yyyy",
                                "enableTime": false,
                                "time_24hr": false,
                                "type": "",
                                "useLocaleSettings": false,
                                "maxDate": "",
                                "saveAs": "date",
                                "mode": "single",
                                "altInput": true,
                                "displayInTimezone": "",
                                "noCalendar": false
                            },
                            "type": "textfield",
                            "properties": {},
                            "key": "record_name",
                            "alwaysEnabled": false,
                            "reorder": false,
                            "showCharCount": false,
                            "encrypted": false,
                            "input": true
                        },
                        {
                            "validate": {
                                "minWords": "",
                                "required": true,
                                "customMessage": "",
                                "minLength": "",
                                "customPrivate": false,
                                "pattern": "",
                                "maxWords": "",
                                "maxLength": "",
                                "custom": "",
                                "json": ""
                            },
                            "properties": {},
                            "alwaysEnabled": false,
                            "row": "0-5",
                            "label": "Employer Name",
                            "allowMultipleMasks": false,
                            "widget": {
                                "minDate": "",
                                "hourIncrement": 1,
                                "defaultDate": null,
                                "format": "dd MMM yyyy",
                                "minuteIncrement": 5,
                                "enableDate": true,
                                "timezone": "",
                                "clickOpens": true,
                                "disableMobile": true,
                                "allowInput": true,
                                "language": "us-en",
                                "dateFormat": "dd MMM yyyy",
                                "enableTime": false,
                                "time_24hr": false,
                                "type": "",
                                "useLocaleSettings": false,
                                "maxDate": "",
                                "saveAs": "date",
                                "mode": "single",
                                "altInput": true,
                                "displayInTimezone": "",
                                "noCalendar": false
                            },
                            "type": "textfield",
                            "logic": [],
                            "key": "employerName",
                            "attributes": {},
                            "customConditional": "",
                            "reorder": false,
                            "inputFormat": "plain",
                            "showWordCount": false,
                            "showCharCount": false,
                            "tableView": true,
                            "encrypted": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "input": true,
                            "defaultValue": ""
                        },
                        {
                            "validate": {
                                "minWords": "",
                                "required": true,
                                "customMessage": "",
                                "minLength": "",
                                "customPrivate": false,
                                "pattern": "",
                                "maxWords": "",
                                "maxLength": "",
                                "custom": "",
                                "json": ""
                            },
                            "properties": {},
                            "alwaysEnabled": false,
                            "row": "0-6",
                            "label": "Last Designation",
                            "allowMultipleMasks": false,
                            "widget": {
                                "minDate": "",
                                "hourIncrement": 1,
                                "defaultDate": null,
                                "format": "dd MMM yyyy",
                                "minuteIncrement": 5,
                                "enableDate": true,
                                "timezone": "",
                                "clickOpens": true,
                                "disableMobile": true,
                                "allowInput": true,
                                "language": "us-en",
                                "dateFormat": "dd MMM yyyy",
                                "enableTime": false,
                                "time_24hr": false,
                                "type": "",
                                "useLocaleSettings": false,
                                "maxDate": "",
                                "saveAs": "date",
                                "mode": "single",
                                "altInput": true,
                                "displayInTimezone": "",
                                "noCalendar": false
                            },
                            "type": "textfield",
                            "logic": [],
                            "key": "lastDesignation",
                            "attributes": {},
                            "customConditional": "",
                            "reorder": false,
                            "inputFormat": "plain",
                            "showWordCount": false,
                            "showCharCount": false,
                            "tableView": true,
                            "encrypted": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "input": true,
                            "defaultValue": ""
                        },
                        {
                            "validate": {
                                "minWords": "",
                                "required": false,
                                "customMessage": "",
                                "minLength": "",
                                "customPrivate": false,
                                "pattern": "",
                                "maxWords": "",
                                "maxLength": "",
                                "custom": "",
                                "json": ""
                            },
                            "properties": {},
                            "alwaysEnabled": false,
                            "row": "0-7",
                            "label": "Last Working City",
                            "allowMultipleMasks": false,
                            "widget": {
                                "minDate": "",
                                "hourIncrement": 1,
                                "defaultDate": null,
                                "format": "dd MMM yyyy",
                                "minuteIncrement": 5,
                                "enableDate": true,
                                "timezone": "",
                                "clickOpens": true,
                                "disableMobile": true,
                                "allowInput": true,
                                "language": "us-en",
                                "dateFormat": "dd MMM yyyy",
                                "enableTime": false,
                                "time_24hr": false,
                                "type": "",
                                "useLocaleSettings": false,
                                "maxDate": "",
                                "saveAs": "date",
                                "mode": "single",
                                "altInput": true,
                                "displayInTimezone": "",
                                "noCalendar": false
                            },
                            "type": "textfield",
                            "logic": [],
                            "key": "lastWorkingCity",
                            "attributes": {},
                            "customConditional": "",
                            "reorder": false,
                            "inputFormat": "plain",
                            "showWordCount": false,
                            "showCharCount": false,
                            "tableView": true,
                            "encrypted": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "input": true,
                            "defaultValue": ""
                        },
                        {
                            "suffix": true,
                            "validate": {
                                "minWords": "",
                                "required": false,
                                "customMessage": "",
                                "minLength": "",
                                "customPrivate": false,
                                "pattern": "",
                                "maxWords": "",
                                "maxLength": "",
                                "custom": "",
                                "json": ""
                            },
                            "defaultValue": "",
                            "row": "0-8",
                            "tags": [],
                            "allowMultipleMasks": false,
                            "logic": [],
                            "label": "Joining Date",
                            "inputFormat": "plain",
                            "customConditional": "",
                            "tableView": true,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "showWordCount": false,
                            "attributes": {},
                            "widget": {
                                "icons": "",
                                "minDate": "",
                                "hourIncrement": 1,
                                "defaultDate": null,
                                "i18n": {
                                    "lng": "en",
                                    "resources": {
                                        "en": {
                                            "translation": {
                                                "minSelectedCount": "You must select at least {{minCount}} items to continue.",
                                                "cancel": "Cancel",
                                                "next": "Next",
                                                "minDate": "{{field}} should not contain date before {{- minDate}}",
                                                "month": "Month",
                                                "maxSelectedCount": "You can only select up to {{maxCount}} items to continue.",
                                                "mask": "{{field}} does not match the mask.",
                                                "day": "Day",
                                                "previous": "Previous",
                                                "year": "Year",
                                                "minWords": "{{field}} must have more than {{length}} words.",
                                                "required": "{{field}} is required",
                                                "april": "April",
                                                "invalid_email": "{{field}} must be a valid email.",
                                                "invalid_day": "{{field}} is not a valid day.",
                                                "max": "{{field}} cannot be greater than {{max}}.",
                                                "error": "Please fix the following errors before submitting.",
                                                "invalid_url": "{{field}} must be a valid url.",
                                                "january": "January",
                                                "invalid_regex": "{{field}} does not match the pattern {{regex}}.",
                                                "minLength": "{{field}} must be longer than {{length}} characters.",
                                                "complete": "Submission Complete",
                                                "pattern": "{{field}} does not match the pattern {{pattern}}",
                                                "maxWords": "{{field}} must have less than {{length}} words.",
                                                "june": "June",
                                                "november": "November",
                                                "maxLength": "{{field}} must be shorter than {{length}} characters.",
                                                "min": "{{field}} cannot be less than {{min}}.",
                                                "invalid_date": "{{field}} is not a valid date.",
                                                "maxDate": "{{field}} should not contain date after {{- maxDate}}",
                                                "august": "August",
                                                "september": "September",
                                                "submit": "Submit Form",
                                                "december": "December",
                                                "may": "May",
                                                "october": "October",
                                                "july": "July",
                                                "february": "February",
                                                "stripe": "{{stripe}}",
                                                "march": "March"
                                            }
                                        }
                                    }
                                },
                                "format": "dd MMM yyyy",
                                "minuteIncrement": 5,
                                "enableDate": true,
                                "timezone": "",
                                "clickOpens": true,
                                "disableMobile": true,
                                "allowInput": true,
                                "language": "en",
                                "dateFormat": "dd MMM yyyy",
                                "enableTime": false,
                                "time_24hr": false,
                                "type": "calendar",
                                "useLocaleSettings": false,
                                "maxDate": "",
                                "saveAs": "date",
                                "mode": "single",
                                "altInput": true,
                                "displayInTimezone": "",
                                "noCalendar": false
                            },
                            "type": "textfield",
                            "properties": {},
                            "key": "joiningDate",
                            "alwaysEnabled": false,
                            "reorder": false,
                            "showCharCount": false,
                            "encrypted": false,
                            "input": true
                        },
                        {
                            "suffix": true,
                            "validate": {
                                "minWords": "",
                                "required": false,
                                "customMessage": "",
                                "minLength": "",
                                "customPrivate": false,
                                "pattern": "",
                                "maxWords": "",
                                "maxLength": "",
                                "custom": "",
                                "json": ""
                            },
                            "defaultValue": "",
                            "row": "0-9",
                            "tags": [],
                            "allowMultipleMasks": false,
                            "logic": [],
                            "label": "Last Working Date",
                            "inputFormat": "plain",
                            "customConditional": "",
                            "tableView": true,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "showWordCount": false,
                            "attributes": {},
                            "widget": {
                                "icons": "",
                                "minDate": "",
                                "hourIncrement": 1,
                                "defaultDate": null,
                                "i18n": {
                                    "lng": "en",
                                    "resources": {
                                        "en": {
                                            "translation": {
                                                "minSelectedCount": "You must select at least {{minCount}} items to continue.",
                                                "cancel": "Cancel",
                                                "next": "Next",
                                                "minDate": "{{field}} should not contain date before {{- minDate}}",
                                                "month": "Month",
                                                "maxSelectedCount": "You can only select up to {{maxCount}} items to continue.",
                                                "mask": "{{field}} does not match the mask.",
                                                "day": "Day",
                                                "previous": "Previous",
                                                "year": "Year",
                                                "minWords": "{{field}} must have more than {{length}} words.",
                                                "required": "{{field}} is required",
                                                "april": "April",
                                                "invalid_email": "{{field}} must be a valid email.",
                                                "invalid_day": "{{field}} is not a valid day.",
                                                "max": "{{field}} cannot be greater than {{max}}.",
                                                "error": "Please fix the following errors before submitting.",
                                                "invalid_url": "{{field}} must be a valid url.",
                                                "january": "January",
                                                "invalid_regex": "{{field}} does not match the pattern {{regex}}.",
                                                "minLength": "{{field}} must be longer than {{length}} characters.",
                                                "complete": "Submission Complete",
                                                "pattern": "{{field}} does not match the pattern {{pattern}}",
                                                "maxWords": "{{field}} must have less than {{length}} words.",
                                                "june": "June",
                                                "november": "November",
                                                "maxLength": "{{field}} must be shorter than {{length}} characters.",
                                                "min": "{{field}} cannot be less than {{min}}.",
                                                "invalid_date": "{{field}} is not a valid date.",
                                                "maxDate": "{{field}} should not contain date after {{- maxDate}}",
                                                "august": "August",
                                                "september": "September",
                                                "submit": "Submit Form",
                                                "december": "December",
                                                "may": "May",
                                                "october": "October",
                                                "july": "July",
                                                "february": "February",
                                                "stripe": "{{stripe}}",
                                                "march": "March"
                                            }
                                        }
                                    }
                                },
                                "format": "dd MMM yyyy",
                                "minuteIncrement": 5,
                                "enableDate": true,
                                "timezone": "",
                                "clickOpens": true,
                                "disableMobile": true,
                                "allowInput": true,
                                "language": "en",
                                "dateFormat": "dd MMM yyyy",
                                "enableTime": false,
                                "time_24hr": false,
                                "type": "calendar",
                                "useLocaleSettings": false,
                                "maxDate": "",
                                "saveAs": "date",
                                "mode": "single",
                                "altInput": true,
                                "displayInTimezone": "",
                                "noCalendar": false
                            },
                            "type": "textfield",
                            "properties": {},
                            "key": "lastWorkingDate",
                            "alwaysEnabled": false,
                            "reorder": false,
                            "showCharCount": false,
                            "encrypted": false,
                            "input": true
                        },
                        {
                            "validate": {
                                "customPrivate": false,
                                "step": "any",
                                "integer": "",
                                "customMessage": "",
                                "required": false,
                                "custom": "",
                                "max": "",
                                "min": "",
                                "json": ""
                            },
                            "properties": {},
                            "row": "0-10",
                            "label": "Annual Compensation",
                            "type": "currency",
                            "alwaysEnabled": false,
                            "tags": [],
                            "logic": [],
                            "key": "annualCompensation",
                            "attributes": {},
                            "mask": false,
                            "reorder": false,
                            "defaultValue": 0,
                            "delimiter": true,
                            "customConditional": "",
                            "tableView": true,
                            "encrypted": false,
                            "conditional": {
                                "when": "",
                                "show": "",
                                "json": "",
                                "eq": ""
                            },
                            "currency": "INR",
                            "input": true
                        }
                    ],
                    "prefix": "",
                    "widget": null,
                    "tags": [],
                    "labelWidth": 30,
                    "autofocus": false,
                    "defaultValue": [
                        {
                            "salaryslip": [],
                            "appointmentletter": [],
                            "experienceletter": [],
                            "record_name": "",
                            "employerName": "",
                            "lastDesignation": "",
                            "lastWorkingCity": "",
                            "joiningDate": "",
                            "lastWorkingDate": "",
                            "annualCompensation": 0,
                            "bgv_required": false
                        }
                    ],
                    "mask": false,
                    "customConditional": "",
                    "refreshOn": "",
                    "errorLabel": "",
                    "calculateValue": "",
                    "hideLabel": true,
                    "input": true,
                    "multiple": false,
                    "suffix": "",
                    "validate": {
                        "customPrivate": false,
                        "customMessage": "",
                        "required": false,
                        "maxLength": 5,
                        "custom": "",
                        "json": ""
                    },
                    "placeholder": "",
                    "tree": true,
                    "defaultOpen": false,
                    "clearOnRefresh": false,
                    "id": "eiv7wc",
                    "reorder": false,
                    "protected": false,
                    "showAddRowButton": true,
                    "hidden": false,
                    "customClass": "horizontal-scroll-data-grid",
                    "encrypted": false,
                    "persistent": true,
                    "unique": false,
                    "addAnotherPosition": "bottom",
                    "dbIndex": false,
                    "description": "",
                    "disableAddingRemovingRows": false,
                    "type": "datagrid",
                    "properties": {},
                    "disabled": false,
                    "key": "employmentRecords",
                    "attributes": {},
                    "tabindex": "",
                    "conditional": {
                        "when": "",
                        "show": "",
                        "json": "",
                        "eq": ""
                    },
                    "clearOnHide": true,
                    "customDefaultValue": "",
                    "removePlacement": "col",
                    "tooltip": ""
                }
            ],
            "prefix": "",
            "theme": "default",
            "tags": [],
            "labelWidth": 30,
            "autofocus": false,
            "defaultValue": null,
            "refreshOn": "",
            "errorLabel": "",
            "calculateValue": "",
            "hideLabel": false,
            "input": false,
            "multiple": false,
            "suffix": "",
            "validate": {
                "required": false,
                "customPrivate": false,
                "custom": ""
            },
            "tooltip": "",
            "placeholder": "",
            "mask": false,
            "clearOnRefresh": false,
            "id": "eytl3xn",
            "reorder": false,
            "protected": false,
            "hidden": false,
            "customClass": "",
            "lazyLoad": false,
            "conditional": {
                "when": "",
                "show": "",
                "json": "",
                "eq": ""
            },
            "persistent": false,
            "unique": false,
            "title": "Employment Records",
            "dbIndex": false,
            "description": "",
            "type": "panel",
            "properties": {},
            "disabled": false,
            "key": "employmentRecordsPanel",
            "attributes": {},
            "tabindex": "",
            "customDefaultValue": "",
            "breadcrumb": "default",
            "collapsible": false,
            "clearOnHide": false
        });
    }

    static builderInfo = {
        title: 'Employment Records',
        group: 'basic',
        icon: 'fa fa-briefcase',
        weight: 70,
        documentation: 'https://formio.github.io/formio.js/app/examples/customcomponent.html',
        schema: EmploymentRecords.schema()
    }
}
