# Generated by Django 3.1.4 on 2022-06-27 12:44

import apps.app_registry.models
from django.db import migrations, models
import ezedox.custom_storage
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentArtifacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('Forms', 'Forms'), ('Workflow', 'Workflow'), ('DocumentTemplate', 'DocumentTemplate'), ('Location', 'Location'), ('Department', 'Department'), ('OrganisationEntityMasterModel', 'OrganisationEntityMasterModel'), ('Groups', 'Groups'), ('List', 'List'), ('AdvancedList', 'AdvancedList'), ('Sequence', 'Sequence'), ('HiringState', 'HiringState'), ('App', 'App'), ('ReportTemplate', 'ReportTemplate'), ('CustomAttribute', 'CustomAttribute'), ('EntityView', 'EntityView'), ('ProcessView', 'ProcessView'), ('ChartName', 'ChartName')], max_length=100)),
                ('file', models.FileField(max_length=356, storage=ezedox.custom_storage.FileStorage(), upload_to=apps.app_registry.models.generate_path2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeploymentFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('file_key', models.CharField(max_length=200)),
                ('deploy_file', models.FileField(max_length=356, upload_to=apps.app_registry.models.generate_path3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeploymentPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('artifacts', models.ManyToManyField(to='app_registry.DeploymentArtifacts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
