# Generated by Django 3.1.4 on 2022-06-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_registry', '0001_initial'),
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentpackage',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='license.license'),
        ),
    ]
