# Generated by Django 3.1.4 on 2022-08-22 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_registry', '0002_deploymentpackage_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultJobRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Default Job Role',
                'verbose_name_plural': 'Default Job Roles',
                'unique_together': {('name', 'slug')},
            },
        ),
    ]
