# Generated by Django 3.1.4 on 2023-01-20 02:54

import apps.app_registry.models
from django.db import migrations, models
import ezedox.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('app_registry', '0003_defaultjobrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentartifacts',
            name='file',
            field=models.FileField(max_length=356, storage=ezedox.custom_storage.OtherFileStorage(), upload_to=apps.app_registry.models.generate_path2),
        ),
        migrations.AlterField(
            model_name='deploymentfiles',
            name='deploy_file',
            field=models.FileField(max_length=356, storage=ezedox.custom_storage.OtherFileStorage(), upload_to=apps.app_registry.models.generate_path3),
        ),
    ]
