# Generated by Django 3.1.4 on 2022-06-27 12:44

import apps.organisations.models
import colorful.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, max_length=25, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.organisations.models.generate_logo_path)),
                ('icon_512_size', models.ImageField(blank=True, null=True, upload_to=apps.organisations.models.generate_logo_path, validators=[apps.organisations.models.Organisation.validate_image_512])),
                ('icon_192_size', models.ImageField(blank=True, null=True, upload_to=apps.organisations.models.generate_logo_path, validators=[apps.organisations.models.Organisation.validate_image_192])),
                ('show_org_name', models.BooleanField(default=False)),
                ('assets_opacity', models.PositiveIntegerField(default=45, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('first_primary_color', colorful.fields.RGBColorField(default='#0c60ae')),
                ('second_primary_color', colorful.fields.RGBColorField(default='#7df0ba')),
                ('first_button_color', colorful.fields.RGBColorField(default='#66aef1')),
                ('second_button_color', colorful.fields.RGBColorField(default='#267acc')),
                ('icon_color', colorful.fields.RGBColorField(default='#31a18a')),
                ('button_text_color', models.CharField(choices=[('BLACK', 'BLACK'), ('WHITE', 'WHITE')], default='WHITE', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('support_notification', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('org_address', models.CharField(blank=True, max_length=120)),
                ('cin', models.CharField(blank=True, max_length=100)),
                ('pan', models.CharField(blank=True, max_length=100)),
                ('gstn', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('cron_expression', models.CharField(max_length=200)),
                ('stop_scheduling', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('tenant_name', models.CharField(max_length=200)),
                ('report_template_id', models.UUIDField(blank=True, default=None, null=True)),
                ('report_recipients', models.TextField(blank=True, null=True)),
                ('recipients_group', models.TextField(blank=True, null=True)),
                ('timezone_offset', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
            },
        ),
        migrations.CreateModel(
            name='OrganisationSMS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('sms_body', models.TextField(default=None, max_length=100)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None, verbose_name='Mobile Number')),
                ('process_instance_id', models.UUIDField()),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('date_sent', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('partner_request_id', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_status', models.CharField(blank=True, choices=[('REJECTED', 'REJECTED'), ('DELIVERED', 'DELIVERED'), ('SUCCESS', 'SUCCESS'), ('STATUS_AWAITING', 'STATUS_AWAITING')], max_length=50, null=True)),
                ('dlt_id', models.CharField(blank=True, max_length=50, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Organisation SMS',
            },
        ),
        migrations.CreateModel(
            name='OrganisationLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('processengine', models.CharField(blank=True, max_length=100, null=True)),
                ('process_modeler', models.CharField(blank=True, max_length=100, null=True)),
                ('process_idm', models.CharField(blank=True, max_length=100, null=True)),
                ('groups_allowed', models.IntegerField(default=30)),
                ('emailer_type', models.CharField(blank=True, choices=[('ALL_TASKS', 'ALL_TASKS'), ('DUE_TODAY_AND_OVERDUE', 'DUE_TODAY_AND_OVERDUE')], default=None, max_length=32, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='license.license')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Organisation License',
                'verbose_name_plural': 'Organisations License',
                'permissions': (('theme_organisationlicense', 'Can view and change theme of organisation'), ('dynamicdashboard_organisationlicense', 'dynamic dashboard permission'), ('master_organisationlicense', 'Can view masterrecord of organisation'), ('bulkprocess_organisationlicense', 'Can do bulk process of organisation')),
            },
        ),
    ]
