# Generated by Django 3.1.4 on 2023-07-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisationlicense_default_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationlicense',
            name='show_completed_tasks',
            field=models.BooleanField(default=False),
        ),
    ]
