# Generated by Django 3.1.4 on 2023-08-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_organisationlicense_show_completed_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationlicense',
            name='task_view_columns',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
