
# Generated by Django 3.1.4 on 2023-10-26 11:34
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('organisations', '0004_organisationlicense_task_view_columns'),
    ]
    operations = [
        migrations.AddField(
            model_name='organisationlicense',
            name='processengine_read_replica',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]