# Generated by Django 3.1.4 on 2022-06-27 12:44

import apps.org_users.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_jobs', '0001_initial'),
        ('organisations', '0001_initial'),
        ('org_department', '0001_initial'),
        ('org_location', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Mobile Number')),
                ('otp_expiration_time', models.DateTimeField(blank=True, null=True, verbose_name='OTP Key Expiration DateTime')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=12, null=True)),
                ('extra_fields', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'External User',
                'verbose_name_plural': 'External Users',
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='InternalUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Internal User',
                'verbose_name_plural': 'Internal Users',
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'unique_together': {('name', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='OrganisationUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('display_picture', models.ImageField(blank=True, null=True, upload_to=apps.org_users.models.generate_display_picture_path)),
                ('signature', models.ImageField(blank=True, null=True, upload_to=apps.org_users.models.generate_signature_path)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=12, null=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None, verbose_name='Mobile Number')),
                ('extra_fields', models.JSONField(blank=True, default=dict, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_department.department')),
                ('groups', models.ManyToManyField(blank=True, to='org_users.Role')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_location.location')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org_users.organisationuser')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org_jobs.partner')),
            ],
            options={
                'verbose_name': 'Organisation User',
                'verbose_name_plural': 'Organisation Users',
            },
            bases=('user.user', models.Model),
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
