# Generated by Django 3.1.4 on 2022-07-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationuser',
            name='groups',
        ),
    ]
