# Generated by Django 3.1.4 on 2022-07-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_entity', '0004_auto_20220714_1525'),
        ('org_config', '0006_auto_20220714_1525'),
        ('org_users', '0002_remove_organisationuser_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
