# Generated by Django 3.1.4 on 2022-08-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_users', '0003_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationuser',
            name='partner',
        ),
    ]
