# Generated by Django 3.1.4 on 2023-01-18 08:49

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('org_users', '0004_remove_organisationuser_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenExternalUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Mobile Number')),
                ('otp_expiration_time', models.DateTimeField(blank=True, null=True, verbose_name='OTP Key Expiration DateTime')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=12, null=True)),
            ],
            options={
                'verbose_name': 'Open External User',
                'verbose_name_plural': 'Open External Users',
            },
            bases=('user.user',),
        ),
    ]
