# Generated by Django 3.1.4 on 2024-01-16 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_organisationlicense_task_view_columns'),
        ('org_users', '0005_openexternaluser'),
    ]
    
    operations = [
        migrations.CreateModel(
            name='PlatformPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('policy_id', models.CharField(max_length=150)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organisationuser',
            name='platform_policy',
            field=models.ManyToManyField(to='org_users.PlatformPolicy'),
        ),
    ]
