# Generated by Django 3.1.4 on 2024-05-22 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_organisationlicense_task_view_columns'),
        ('org_users', '0006_auto_20240116_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationuser',
            name='department',
        ),
        migrations.AddField(
            model_name='platformpolicy',
            name='relation',
            field=models.CharField(choices=[('MY_ORG', 'MY_ORG'), ('VENDOR_ORG', 'VENDOR_ORG'), ('CLIENT_ORG', 'CLIENT_ORG')], default='MY_ORG', max_length=256),
        ),
        migrations.AddField(
            model_name='platformpolicy',
            name='source_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_tenant', to='organisations.organisation'),
        ),
    ]
