org_list_errors = {
    16001: ["List with this key already exists.", " {} Failed to create List, due to: {}."],
    16002: ["Failed to create Lists for the Organisation.", " User: {}, Error: {}."],
    16003: ["Failed to create Lists for the Organisation.", " User: {}, Exception: {}. "],
    16004: ["Failed to return Organisation Lists.", " User: {}, Error: {}."],
    16005: ["ID not found.", " {}, Failed to update Organisation List for Id: {}, Error: {} "],
    16006: ["List with this key already exists.", " {}, Failed to update Lists details for id:{}, due to: {}."],
    16007: ["Failed to update Organisation List details.", " User: {},Id: {}, Error: {}."],
    16008: ["Failed to update list details.", " User: {}, Id: {}, Error: {} "],
    16009: ["ID not found.", " {}, Failed to retrieve of Organisation List for id: {}, Error:{} "],
    16010: ["Failed to retrieve Lists details.", " User: {}, Id: {}, Error: {} "],
    16011: ["ID not found.", " {}, Failed to delete of Organisation List for id: {}, due to: {} "],
    16012: ["This list is referred at some place, Failed to delete the list.", " User: {}, Id: {} "],
    16013: ["Failed to delete lists data.", " User: {}, Id: {}, Exception: {} "],
    16014: ["Failed to create Advanced Lists for the Organisation.", " User: {}, Error: {} "],
    16015: ["Failed to create Lists for the Organisation.", " User: {}, Exception: {} "],
    16016: ["Bad Request.", " Organisation Advanced List creation failed, User:{}, Error: {} "],
    16017: ["Failed to create Organisation Advanced Lists", " User: {} "],
    16018: ["Failed to create Advanced Lists for the Organisation", " User: {}, Error: {} "],
    16019: ["Failed to create Lists for the Organisation.", " User: {}, Error: {} "],
    16020: ["Failed to return Advanced Organisation Lists.", " User: {}, Exception: {} "],
    16021: ["Failed to return Advanced Organisation Lists.", " User: {}, Id: {}, Error: {} "],
    16022: ["ID not found.", " User: {}, Id: {}, Error: {} "],
    16023: ["Failed to update list details.", " User: {}, Id: {}, Error: {} "],
    16024: ["Failed to update list details.", " User: {}, Id: {}, Exception: {} "],
    16025: ["ID not found.", " User: {}, Id: {}, Error: {} "],
    16026: ["Bad Request.", " User: {}, Error: {} "],
    16027: ["Failed to create Organisation Advanced Lists.", " User: {} "],
    16028: ["Failed to update list details.", " User: {}, Id: {}, Error: {} "],
    16029: ["Failed to update list details.", " User: {}, Id: {}, Exception: {} "],
    16030: ["ID not found.", " {} Failed to retrieve of Organisation Advanced List for id: {}, due to :{} "],
    16031: ["Failed to retrieve Advanced Lists details.", " User: {}, Id: {}, Exception: {} "],
    16032: ["ID not found.", " {} Failed to delete of Organisation Advanced List for id: {}, due to: {} "],
    16033: ["Failed to delete Advanced lists data.", " User: {}, Id: {}, Error: {} "],
}
